// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.0
// source: client_connect_state/v1/client_connect_state.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationClientConnectStateServicePublishClientConnectState = "/api.client_connect_state.v1.ClientConnectStateService/PublishClientConnectState"

type ClientConnectStateServiceHTTPServer interface {
	// PublishClientConnectState PublishClientConnectState publishes a client connect state event to Kafka
	PublishClientConnectState(context.Context, *PublishClientConnectStateRequest) (*PublishClientConnectStateReply, error)
}

func RegisterClientConnectStateServiceHTTPServer(s *http.Server, srv ClientConnectStateServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/client-connect-state", _ClientConnectStateService_PublishClientConnectState0_HTTP_Handler(srv))
}

func _ClientConnectStateService_PublishClientConnectState0_HTTP_Handler(srv ClientConnectStateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishClientConnectStateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClientConnectStateServicePublishClientConnectState)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishClientConnectState(ctx, req.(*PublishClientConnectStateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishClientConnectStateReply)
		return ctx.Result(200, reply)
	}
}

type ClientConnectStateServiceHTTPClient interface {
	// PublishClientConnectState PublishClientConnectState publishes a client connect state event to Kafka
	PublishClientConnectState(ctx context.Context, req *PublishClientConnectStateRequest, opts ...http.CallOption) (rsp *PublishClientConnectStateReply, err error)
}

type ClientConnectStateServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewClientConnectStateServiceHTTPClient(client *http.Client) ClientConnectStateServiceHTTPClient {
	return &ClientConnectStateServiceHTTPClientImpl{client}
}

// PublishClientConnectState PublishClientConnectState publishes a client connect state event to Kafka
func (c *ClientConnectStateServiceHTTPClientImpl) PublishClientConnectState(ctx context.Context, in *PublishClientConnectStateRequest, opts ...http.CallOption) (*PublishClientConnectStateReply, error) {
	var out PublishClientConnectStateReply
	pattern := "/api/v1/client-connect-state"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationClientConnectStateServicePublishClientConnectState))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
