// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: client_connect_state/v1/client_connect_state.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientConnectStateService_PublishClientConnectState_FullMethodName = "/api.client_connect_state.v1.ClientConnectStateService/PublishClientConnectState"
)

// ClientConnectStateServiceClient is the client API for ClientConnectStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientConnectStateService provides APIs for publishing client connect state events.
type ClientConnectStateServiceClient interface {
	// PublishClientConnectState publishes a client connect state event to Kafka
	PublishClientConnectState(ctx context.Context, in *PublishClientConnectStateRequest, opts ...grpc.CallOption) (*PublishClientConnectStateReply, error)
}

type clientConnectStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientConnectStateServiceClient(cc grpc.ClientConnInterface) ClientConnectStateServiceClient {
	return &clientConnectStateServiceClient{cc}
}

func (c *clientConnectStateServiceClient) PublishClientConnectState(ctx context.Context, in *PublishClientConnectStateRequest, opts ...grpc.CallOption) (*PublishClientConnectStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishClientConnectStateReply)
	err := c.cc.Invoke(ctx, ClientConnectStateService_PublishClientConnectState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientConnectStateServiceServer is the server API for ClientConnectStateService service.
// All implementations must embed UnimplementedClientConnectStateServiceServer
// for forward compatibility.
//
// ClientConnectStateService provides APIs for publishing client connect state events.
type ClientConnectStateServiceServer interface {
	// PublishClientConnectState publishes a client connect state event to Kafka
	PublishClientConnectState(context.Context, *PublishClientConnectStateRequest) (*PublishClientConnectStateReply, error)
	mustEmbedUnimplementedClientConnectStateServiceServer()
}

// UnimplementedClientConnectStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientConnectStateServiceServer struct{}

func (UnimplementedClientConnectStateServiceServer) PublishClientConnectState(context.Context, *PublishClientConnectStateRequest) (*PublishClientConnectStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishClientConnectState not implemented")
}
func (UnimplementedClientConnectStateServiceServer) mustEmbedUnimplementedClientConnectStateServiceServer() {
}
func (UnimplementedClientConnectStateServiceServer) testEmbeddedByValue() {}

// UnsafeClientConnectStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientConnectStateServiceServer will
// result in compilation errors.
type UnsafeClientConnectStateServiceServer interface {
	mustEmbedUnimplementedClientConnectStateServiceServer()
}

func RegisterClientConnectStateServiceServer(s grpc.ServiceRegistrar, srv ClientConnectStateServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientConnectStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientConnectStateService_ServiceDesc, srv)
}

func _ClientConnectStateService_PublishClientConnectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishClientConnectStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientConnectStateServiceServer).PublishClientConnectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientConnectStateService_PublishClientConnectState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientConnectStateServiceServer).PublishClientConnectState(ctx, req.(*PublishClientConnectStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientConnectStateService_ServiceDesc is the grpc.ServiceDesc for ClientConnectStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientConnectStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.client_connect_state.v1.ClientConnectStateService",
	HandlerType: (*ClientConnectStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishClientConnectState",
			Handler:    _ClientConnectStateService_PublishClientConnectState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client_connect_state/v1/client_connect_state.proto",
}
