// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/alert.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAlertServiceInterface is a mock of AlertServiceInterface interface.
type MockAlertServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAlertServiceInterfaceMockRecorder
}

// MockAlertServiceInterfaceMockRecorder is the mock recorder for MockAlertServiceInterface.
type MockAlertServiceInterfaceMockRecorder struct {
	mock *MockAlertServiceInterface
}

// NewMockAlertServiceInterface creates a new mock instance.
func NewMockAlertServiceInterface(ctrl *gomock.Controller) *MockAlertServiceInterface {
	mock := &MockAlertServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAlertServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertServiceInterface) EXPECT() *MockAlertServiceInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAlertServiceInterface) Get(ctx context.Context, id int64) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlertServiceInterfaceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlertServiceInterface)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockAlertServiceInterface) List(ctx context.Context, page, size int, status, severity, deviceKey string) ([]model.Alert, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, status, severity, deviceKey)
	ret0, _ := ret[0].([]model.Alert)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAlertServiceInterfaceMockRecorder) List(ctx, page, size, status, severity, deviceKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertServiceInterface)(nil).List), ctx, page, size, status, severity, deviceKey)
}

// SetStatus mocks base method.
func (m *MockAlertServiceInterface) SetStatus(ctx context.Context, id int64, status string) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockAlertServiceInterfaceMockRecorder) SetStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockAlertServiceInterface)(nil).SetStatus), ctx, id, status)
}
