// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/device_group.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "aiot-backend/api/v1"
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceGroupServiceInterface is a mock of DeviceGroupServiceInterface interface.
type MockDeviceGroupServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceGroupServiceInterfaceMockRecorder
}

// MockDeviceGroupServiceInterfaceMockRecorder is the mock recorder for MockDeviceGroupServiceInterface.
type MockDeviceGroupServiceInterfaceMockRecorder struct {
	mock *MockDeviceGroupServiceInterface
}

// NewMockDeviceGroupServiceInterface creates a new mock instance.
func NewMockDeviceGroupServiceInterface(ctrl *gomock.Controller) *MockDeviceGroupServiceInterface {
	mock := &MockDeviceGroupServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeviceGroupServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceGroupServiceInterface) EXPECT() *MockDeviceGroupServiceInterfaceMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockDeviceGroupServiceInterface) AddDevices(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevices", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) AddDevices(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).AddDevices), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockDeviceGroupServiceInterface) Create(arg0 context.Context, arg1 *v1.CreateDeviceGroupRequest) (*model.DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDeviceGroupServiceInterface) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Delete), arg0, arg1)
}

// Devices mocks base method.
func (m *MockDeviceGroupServiceInterface) Devices(arg0 context.Context, arg1 string, arg2, arg3 int, arg4, arg5 string) ([]model.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]model.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Devices indicates an expected call of Devices.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Devices(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Devices), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Get mocks base method.
func (m *MockDeviceGroupServiceInterface) Get(arg0 context.Context, arg1 string) (*model.DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockDeviceGroupServiceInterface) List(arg0 context.Context, arg1, arg2 int, arg3, arg4 string) ([]model.DeviceGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]model.DeviceGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) List(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).List), arg0, arg1, arg2, arg3, arg4)
}

// Preview mocks base method.
func (m *MockDeviceGroupServiceInterface) Preview(arg0 context.Context, arg1 string) ([]model.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", arg0, arg1)
	ret0, _ := ret[0].([]model.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Preview indicates an expected call of Preview.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Preview(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Preview), arg0, arg1)
}

// RemoveDevices mocks base method.
func (m *MockDeviceGroupServiceInterface) RemoveDevices(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevices", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevices indicates an expected call of RemoveDevices.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) RemoveDevices(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevices", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).RemoveDevices), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDeviceGroupServiceInterface) Update(arg0 context.Context, arg1 string, arg2 *v1.UpdateDeviceGroupRequest) (*model.DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeviceGroupServiceInterfaceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceGroupServiceInterface)(nil).Update), arg0, arg1, arg2)
}
