// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/device_service_invocation.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	dto "aiot-backend/internal/dto"
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceServiceInvocationServiceInterface is a mock of DeviceServiceInvocationServiceInterface interface.
type MockDeviceServiceInvocationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceServiceInvocationServiceInterfaceMockRecorder
}

// MockDeviceServiceInvocationServiceInterfaceMockRecorder is the mock recorder for MockDeviceServiceInvocationServiceInterface.
type MockDeviceServiceInvocationServiceInterfaceMockRecorder struct {
	mock *MockDeviceServiceInvocationServiceInterface
}

// NewMockDeviceServiceInvocationServiceInterface creates a new mock instance.
func NewMockDeviceServiceInvocationServiceInterface(ctrl *gomock.Controller) *MockDeviceServiceInvocationServiceInterface {
	mock := &MockDeviceServiceInvocationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeviceServiceInvocationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceServiceInvocationServiceInterface) EXPECT() *MockDeviceServiceInvocationServiceInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockDeviceServiceInvocationServiceInterface) List(ctx context.Context, query dto.ListDeviceServiceInvocationsQuery) ([]model.DeviceServiceInvocation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].([]model.DeviceServiceInvocation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeviceServiceInvocationServiceInterfaceMockRecorder) List(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceServiceInvocationServiceInterface)(nil).List), ctx, query)
}
