// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/device_event.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceEventServiceInterface is a mock of DeviceEventServiceInterface interface.
type MockDeviceEventServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceEventServiceInterfaceMockRecorder
}

// MockDeviceEventServiceInterfaceMockRecorder is the mock recorder for MockDeviceEventServiceInterface.
type MockDeviceEventServiceInterfaceMockRecorder struct {
	mock *MockDeviceEventServiceInterface
}

// NewMockDeviceEventServiceInterface creates a new mock instance.
func NewMockDeviceEventServiceInterface(ctrl *gomock.Controller) *MockDeviceEventServiceInterface {
	mock := &MockDeviceEventServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeviceEventServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceEventServiceInterface) EXPECT() *MockDeviceEventServiceInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockDeviceEventServiceInterface) List(ctx context.Context, page, size int, keyword, deviceKey, eventType string, startAt, endAt *time.Time) ([]model.DeviceEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword, deviceKey, eventType, startAt, endAt)
	ret0, _ := ret[0].([]model.DeviceEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeviceEventServiceInterfaceMockRecorder) List(ctx, page, size, keyword, deviceKey, eventType, startAt, endAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceEventServiceInterface)(nil).List), ctx, page, size, keyword, deviceKey, eventType, startAt, endAt)
}

// Record mocks base method.
func (m *MockDeviceEventServiceInterface) Record(ctx context.Context, productKey, deviceKey, eventType string, timestamp int64, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, productKey, deviceKey, eventType, timestamp, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockDeviceEventServiceInterfaceMockRecorder) Record(ctx, productKey, deviceKey, eventType, timestamp, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockDeviceEventServiceInterface)(nil).Record), ctx, productKey, deviceKey, eventType, timestamp, data)
}
