// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/kafka.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKafkaServiceInterface is a mock of KafkaServiceInterface interface.
type MockKafkaServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaServiceInterfaceMockRecorder
}

// MockKafkaServiceInterfaceMockRecorder is the mock recorder for MockKafkaServiceInterface.
type MockKafkaServiceInterfaceMockRecorder struct {
	mock *MockKafkaServiceInterface
}

// NewMockKafkaServiceInterface creates a new mock instance.
func NewMockKafkaServiceInterface(ctrl *gomock.Controller) *MockKafkaServiceInterface {
	mock := &MockKafkaServiceInterface{ctrl: ctrl}
	mock.recorder = &MockKafkaServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaServiceInterface) EXPECT() *MockKafkaServiceInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockKafkaServiceInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockKafkaServiceInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKafkaServiceInterface)(nil).Close))
}

// Flush mocks base method.
func (m *MockKafkaServiceInterface) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockKafkaServiceInterfaceMockRecorder) Flush(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockKafkaServiceInterface)(nil).Flush), ctx)
}

// Produce mocks base method.
func (m *MockKafkaServiceInterface) Produce(ctx context.Context, topic string, key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, topic, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockKafkaServiceInterfaceMockRecorder) Produce(ctx, topic, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockKafkaServiceInterface)(nil).Produce), ctx, topic, key, value)
}

// ProduceAsync mocks base method.
func (m *MockKafkaServiceInterface) ProduceAsync(ctx context.Context, topic string, key, value []byte, callback func(error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProduceAsync", ctx, topic, key, value, callback)
}

// ProduceAsync indicates an expected call of ProduceAsync.
func (mr *MockKafkaServiceInterfaceMockRecorder) ProduceAsync(ctx, topic, key, value, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceAsync", reflect.TypeOf((*MockKafkaServiceInterface)(nil).ProduceAsync), ctx, topic, key, value, callback)
}

// ProduceJSON mocks base method.
func (m *MockKafkaServiceInterface) ProduceJSON(ctx context.Context, topic string, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceJSON", ctx, topic, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceJSON indicates an expected call of ProduceJSON.
func (mr *MockKafkaServiceInterfaceMockRecorder) ProduceJSON(ctx, topic, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceJSON", reflect.TypeOf((*MockKafkaServiceInterface)(nil).ProduceJSON), ctx, topic, key, data)
}

// ProduceJSONAsync mocks base method.
func (m *MockKafkaServiceInterface) ProduceJSONAsync(ctx context.Context, topic string, key string, data any, callback func(error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProduceJSONAsync", ctx, topic, key, data, callback)
}

// ProduceJSONAsync indicates an expected call of ProduceJSONAsync.
func (mr *MockKafkaServiceInterfaceMockRecorder) ProduceJSONAsync(ctx, topic, key, data, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceJSONAsync", reflect.TypeOf((*MockKafkaServiceInterface)(nil).ProduceJSONAsync), ctx, topic, key, data, callback)
}

