// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/ota.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "aiot-backend/internal/model"
	service "aiot-backend/internal/service"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOTAServiceInterface is a mock of OTAServiceInterface interface.
type MockOTAServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOTAServiceInterfaceMockRecorder
}

// MockOTAServiceInterfaceMockRecorder is the mock recorder for MockOTAServiceInterface.
type MockOTAServiceInterfaceMockRecorder struct {
	mock *MockOTAServiceInterface
}

// NewMockOTAServiceInterface creates a new mock instance.
func NewMockOTAServiceInterface(ctrl *gomock.Controller) *MockOTAServiceInterface {
	mock := &MockOTAServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOTAServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTAServiceInterface) EXPECT() *MockOTAServiceInterfaceMockRecorder {
	return m.recorder
}

// BatchUpgrade mocks base method.
func (m *MockOTAServiceInterface) BatchUpgrade(ctx context.Context, uuid string, deviceKeys []string) (*model.UpgradeBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpgrade", ctx, uuid, deviceKeys)
	ret0, _ := ret[0].(*model.UpgradeBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpgrade indicates an expected call of BatchUpgrade.
func (mr *MockOTAServiceInterfaceMockRecorder) BatchUpgrade(ctx, uuid, deviceKeys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpgrade", reflect.TypeOf((*MockOTAServiceInterface)(nil).BatchUpgrade), ctx, uuid, deviceKeys)
}

// Batches mocks base method.
func (m *MockOTAServiceInterface) Batches(ctx context.Context, uuid string) ([]model.UpgradeBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batches", ctx, uuid)
	ret0, _ := ret[0].([]model.UpgradeBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Batches indicates an expected call of Batches.
func (mr *MockOTAServiceInterfaceMockRecorder) Batches(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batches", reflect.TypeOf((*MockOTAServiceInterface)(nil).Batches), ctx, uuid)
}

// CancelBatch mocks base method.
func (m *MockOTAServiceInterface) CancelBatch(ctx context.Context, uuid, batchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBatch", ctx, uuid, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBatch indicates an expected call of CancelBatch.
func (mr *MockOTAServiceInterfaceMockRecorder) CancelBatch(ctx, uuid, batchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBatch", reflect.TypeOf((*MockOTAServiceInterface)(nil).CancelBatch), ctx, uuid, batchID)
}

// Create mocks base method.
func (m *MockOTAServiceInterface) Create(ctx context.Context, pkg *model.OTAPackage, productKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pkg, productKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOTAServiceInterfaceMockRecorder) Create(ctx, pkg, productKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOTAServiceInterface)(nil).Create), ctx, pkg, productKey)
}

// Delete mocks base method.
func (m *MockOTAServiceInterface) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOTAServiceInterfaceMockRecorder) Delete(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOTAServiceInterface)(nil).Delete), ctx, uuid)
}

// Deployments mocks base method.
func (m *MockOTAServiceInterface) Deployments(ctx context.Context, uuid string, page, size int, status string, batchID ...string) ([]model.DeviceDeployment, int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, uuid, page, size, status}
	for _, a := range batchID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Deployments", varargs...)
	ret0, _ := ret[0].([]model.DeviceDeployment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Deployments indicates an expected call of Deployments.
func (mr *MockOTAServiceInterfaceMockRecorder) Deployments(ctx, uuid, page, size, status interface{}, batchID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, uuid, page, size, status}, batchID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deployments", reflect.TypeOf((*MockOTAServiceInterface)(nil).Deployments), varargs...)
}

// Get mocks base method.
func (m *MockOTAServiceInterface) Get(ctx context.Context, uuid string) (*model.OTAPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*model.OTAPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOTAServiceInterfaceMockRecorder) Get(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOTAServiceInterface)(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockOTAServiceInterface) List(ctx context.Context, page, size int) ([]model.OTAPackage, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size)
	ret0, _ := ret[0].([]model.OTAPackage)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOTAServiceInterfaceMockRecorder) List(ctx, page, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOTAServiceInterface)(nil).List), ctx, page, size)
}

// ReportBatchDevice mocks base method.
func (m *MockOTAServiceInterface) ReportBatchDevice(ctx context.Context, batchID, deviceKey, status, version string, progress int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportBatchDevice", ctx, batchID, deviceKey, status, version, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportBatchDevice indicates an expected call of ReportBatchDevice.
func (mr *MockOTAServiceInterfaceMockRecorder) ReportBatchDevice(ctx, batchID, deviceKey, status, version, progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBatchDevice", reflect.TypeOf((*MockOTAServiceInterface)(nil).ReportBatchDevice), ctx, batchID, deviceKey, status, version, progress)
}

// ReportStatus mocks base method.
func (m *MockOTAServiceInterface) ReportStatus(ctx context.Context, uuid, deviceKey, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportStatus", ctx, uuid, deviceKey, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportStatus indicates an expected call of ReportStatus.
func (mr *MockOTAServiceInterfaceMockRecorder) ReportStatus(ctx, uuid, deviceKey, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportStatus", reflect.TypeOf((*MockOTAServiceInterface)(nil).ReportStatus), ctx, uuid, deviceKey, status)
}

// RetryBatch mocks base method.
func (m *MockOTAServiceInterface) RetryBatch(ctx context.Context, uuid, batchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryBatch", ctx, uuid, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryBatch indicates an expected call of RetryBatch.
func (mr *MockOTAServiceInterfaceMockRecorder) RetryBatch(ctx, uuid, batchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryBatch", reflect.TypeOf((*MockOTAServiceInterface)(nil).RetryBatch), ctx, uuid, batchID)
}

// Statistics mocks base method.
func (m *MockOTAServiceInterface) Statistics(ctx context.Context, uuid string, batchID ...string) (service.UpgradeStatistics, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, uuid}
	for _, a := range batchID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Statistics", varargs...)
	ret0, _ := ret[0].(service.UpgradeStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Statistics indicates an expected call of Statistics.
func (mr *MockOTAServiceInterfaceMockRecorder) Statistics(ctx, uuid interface{}, batchID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, uuid}, batchID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statistics", reflect.TypeOf((*MockOTAServiceInterface)(nil).Statistics), varargs...)
}

// Update mocks base method.
func (m *MockOTAServiceInterface) Update(ctx context.Context, pkg *model.OTAPackage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pkg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOTAServiceInterfaceMockRecorder) Update(ctx, pkg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOTAServiceInterface)(nil).Update), ctx, pkg)
}
