// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/product_message_parser.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	messageparserv1 "aiot-backend/api/message_parser/v1"
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProductMessageParserServiceInterface is a mock of ProductMessageParserServiceInterface interface.
type MockProductMessageParserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductMessageParserServiceInterfaceMockRecorder
}

// MockProductMessageParserServiceInterfaceMockRecorder is the mock recorder for MockProductMessageParserServiceInterface.
type MockProductMessageParserServiceInterfaceMockRecorder struct {
	mock *MockProductMessageParserServiceInterface
}

// NewMockProductMessageParserServiceInterface creates a new mock instance.
func NewMockProductMessageParserServiceInterface(ctrl *gomock.Controller) *MockProductMessageParserServiceInterface {
	mock := &MockProductMessageParserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProductMessageParserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductMessageParserServiceInterface) EXPECT() *MockProductMessageParserServiceInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProductMessageParserServiceInterface) Execute(ctx context.Context, productKey string, request messageparserv1.ExecuteProductMessageParserRequest) (*messageparserv1.ExecuteProductMessageParserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, productKey, request)
	ret0, _ := ret[0].(*messageparserv1.ExecuteProductMessageParserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProductMessageParserServiceInterfaceMockRecorder) Execute(ctx, productKey, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProductMessageParserServiceInterface)(nil).Execute), ctx, productKey, request)
}

// Get mocks base method.
func (m *MockProductMessageParserServiceInterface) Get(ctx context.Context, productKey string) (*model.ProductMessageParser, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, productKey)
	ret0, _ := ret[0].(*model.ProductMessageParser)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockProductMessageParserServiceInterfaceMockRecorder) Get(ctx, productKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductMessageParserServiceInterface)(nil).Get), ctx, productKey)
}

// Save mocks base method.
func (m *MockProductMessageParserServiceInterface) Save(ctx context.Context, productKey, language, script string) (*model.ProductMessageParser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, productKey, language, script)
	ret0, _ := ret[0].(*model.ProductMessageParser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockProductMessageParserServiceInterfaceMockRecorder) Save(ctx, productKey, language, script interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProductMessageParserServiceInterface)(nil).Save), ctx, productKey, language, script)
}
