// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/scene_linkage.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSceneLinkageServiceInterface is a mock of SceneLinkageServiceInterface interface.
type MockSceneLinkageServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSceneLinkageServiceInterfaceMockRecorder
}

// MockSceneLinkageServiceInterfaceMockRecorder is the mock recorder for MockSceneLinkageServiceInterface.
type MockSceneLinkageServiceInterfaceMockRecorder struct {
	mock *MockSceneLinkageServiceInterface
}

// NewMockSceneLinkageServiceInterface creates a new mock instance.
func NewMockSceneLinkageServiceInterface(ctrl *gomock.Controller) *MockSceneLinkageServiceInterface {
	mock := &MockSceneLinkageServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSceneLinkageServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSceneLinkageServiceInterface) EXPECT() *MockSceneLinkageServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSceneLinkageServiceInterface) Create(ctx context.Context, scene *model.SceneLinkage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, scene)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSceneLinkageServiceInterfaceMockRecorder) Create(ctx, scene interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSceneLinkageServiceInterface)(nil).Create), ctx, scene)
}

// Delete mocks base method.
func (m *MockSceneLinkageServiceInterface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSceneLinkageServiceInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSceneLinkageServiceInterface)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockSceneLinkageServiceInterface) Get(ctx context.Context, id int64) (*model.SceneLinkage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.SceneLinkage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSceneLinkageServiceInterfaceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSceneLinkageServiceInterface)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockSceneLinkageServiceInterface) List(ctx context.Context, page, size int, search string, enable int) ([]model.SceneLinkage, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, search, enable)
	ret0, _ := ret[0].([]model.SceneLinkage)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSceneLinkageServiceInterfaceMockRecorder) List(ctx, page, size, search, enable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSceneLinkageServiceInterface)(nil).List), ctx, page, size, search, enable)
}

// Update mocks base method.
func (m *MockSceneLinkageServiceInterface) Update(ctx context.Context, scene *model.SceneLinkage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, scene)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSceneLinkageServiceInterfaceMockRecorder) Update(ctx, scene interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSceneLinkageServiceInterface)(nil).Update), ctx, scene)
}
