// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/scene_linkage_detail.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSceneLinkageDetailServiceInterface is a mock of SceneLinkageDetailServiceInterface interface.
type MockSceneLinkageDetailServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSceneLinkageDetailServiceInterfaceMockRecorder
}

// MockSceneLinkageDetailServiceInterfaceMockRecorder is the mock recorder for MockSceneLinkageDetailServiceInterface.
type MockSceneLinkageDetailServiceInterfaceMockRecorder struct {
	mock *MockSceneLinkageDetailServiceInterface
}

// NewMockSceneLinkageDetailServiceInterface creates a new mock instance.
func NewMockSceneLinkageDetailServiceInterface(ctrl *gomock.Controller) *MockSceneLinkageDetailServiceInterface {
	mock := &MockSceneLinkageDetailServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSceneLinkageDetailServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSceneLinkageDetailServiceInterface) EXPECT() *MockSceneLinkageDetailServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSceneLinkageDetailServiceInterface) Create(ctx context.Context, detail *model.SceneLinkageDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSceneLinkageDetailServiceInterfaceMockRecorder) Create(ctx, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSceneLinkageDetailServiceInterface)(nil).Create), ctx, detail)
}

// GetBySceneID mocks base method.
func (m *MockSceneLinkageDetailServiceInterface) GetBySceneID(ctx context.Context, sceneID int64) (*model.SceneLinkageDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySceneID", ctx, sceneID)
	ret0, _ := ret[0].(*model.SceneLinkageDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySceneID indicates an expected call of GetBySceneID.
func (mr *MockSceneLinkageDetailServiceInterfaceMockRecorder) GetBySceneID(ctx, sceneID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySceneID", reflect.TypeOf((*MockSceneLinkageDetailServiceInterface)(nil).GetBySceneID), ctx, sceneID)
}

// Update mocks base method.
func (m *MockSceneLinkageDetailServiceInterface) Update(ctx context.Context, detail *model.SceneLinkageDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSceneLinkageDetailServiceInterfaceMockRecorder) Update(ctx, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSceneLinkageDetailServiceInterface)(nil).Update), ctx, detail)
}
