// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things-backend/internal/handler"
	"0things-backend/internal/job"
	"0things-backend/internal/repository"
	"0things-backend/internal/router"
	"0things-backend/internal/server"
	"0things-backend/internal/service"
	"0things-backend/pkg/app"
	"0things-backend/pkg/jwt"
	"0things-backend/pkg/log"
	"0things-backend/pkg/server/http"
	"0things-backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	ioTDB := repository.NewIoTDB(viperViper, logger)
	productRepository := repository.NewProductRepository(ioTDB)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(handlerHandler, productService)
	productTSLRepository := repository.NewProductTSLRepository(ioTDB)
	productTSLService := service.NewProductTSLService(productRepository, productTSLRepository)
	productTSLHandler := handler.NewProductTSLHandler(handlerHandler, productTSLService)
	ioTRedis := repository.NewIoTRedis(viperViper)
	deviceRepository := repository.NewDeviceRepository(ioTDB, ioTRedis)
	deviceTagRepository := repository.NewDeviceTagRepository(ioTDB)
	deviceShadowRepository := repository.NewDeviceShadowRepository(ioTDB)
	pushRecordRepository := repository.NewPushRecordRepository(ioTDB)
	deviceService := service.NewDeviceService(deviceRepository, productRepository, deviceTagRepository, deviceShadowRepository, pushRecordRepository)
	deviceHandler := handler.NewDeviceHandler(handlerHandler, deviceService, viperViper)
	ruleRepository := repository.NewRuleRepository(ioTDB)
	ruleService := service.NewRuleService(ruleRepository)
	ruleHandler := handler.NewRuleHandler(handlerHandler, ruleService)
	alertRepository := repository.NewAlertRepository(ioTDB)
	alertService := service.NewAlertService(alertRepository)
	alertHandler := handler.NewAlertHandler(handlerHandler, alertService)
	otaRepository := repository.NewOTARepository(ioTDB)
	otaService := service.NewOTAService(otaRepository, productRepository)
	otaHandler := handler.NewOTAHandler(handlerHandler, otaService)
	deviceEventRepository := repository.NewDeviceEventRepository(ioTDB)
	deviceEventService := service.NewDeviceEventService(deviceEventRepository, deviceRepository)
	deviceEventHandler := handler.NewDeviceEventHandler(handlerHandler, deviceEventService)
	deviceEventConsumer, err := job.NewDeviceEventConsumer(viperViper, deviceEventService, logger)
	if err != nil { return nil, nil, err }
	routerDeps := router.RouterDeps{
		Logger:            logger,
		Config:            viperViper,
		JWT:               jwtJWT,
		UserHandler:       userHandler,
		ProductHandler:    productHandler,
		ProductTSLHandler: productTSLHandler,
		DeviceHandler:     deviceHandler,
		RuleHandler:       ruleHandler,
		AlertHandler:      alertHandler,
		OTAHandler:        otaHandler,
		DeviceEventHandler: deviceEventHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob, deviceEventConsumer)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewIoTDB, repository.NewIoTRedis, repository.NewProductRepository, repository.NewProductTSLRepository, repository.NewDeviceRepository, repository.NewDeviceTagRepository, repository.NewDeviceShadowRepository, repository.NewPushRecordRepository, repository.NewRuleRepository, repository.NewAlertRepository, repository.NewOTARepository, repository.NewDeviceEventRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewProductService, service.NewProductTSLService, service.NewDeviceService, service.NewRuleService, service.NewAlertService, service.NewOTAService, service.NewDeviceEventService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewProductHandler, handler.NewProductTSLHandler, handler.NewDeviceHandler, handler.NewRuleHandler, handler.NewAlertHandler, handler.NewOTAHandler, handler.NewDeviceEventHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob, job.NewDeviceEventConsumer)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
