// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/device.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "0things-backend/internal/model"
	service "0things-backend/internal/service"
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceServiceInterface is a mock of DeviceServiceInterface interface.
type MockDeviceServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceServiceInterfaceMockRecorder
}

// MockDeviceServiceInterfaceMockRecorder is the mock recorder for MockDeviceServiceInterface.
type MockDeviceServiceInterfaceMockRecorder struct {
	mock *MockDeviceServiceInterface
}

// NewMockDeviceServiceInterface creates a new mock instance.
func NewMockDeviceServiceInterface(ctrl *gomock.Controller) *MockDeviceServiceInterface {
	mock := &MockDeviceServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeviceServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceServiceInterface) EXPECT() *MockDeviceServiceInterfaceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockDeviceServiceInterface) Activate(ctx context.Context, id int64) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, id)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activate indicates an expected call of Activate.
func (mr *MockDeviceServiceInterfaceMockRecorder) Activate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Activate), ctx, id)
}

// BatchCreate mocks base method.
func (m *MockDeviceServiceInterface) BatchCreate(ctx context.Context, content []byte) (int, []service.BatchUploadError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, content)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]service.BatchUploadError)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockDeviceServiceInterfaceMockRecorder) BatchCreate(ctx, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockDeviceServiceInterface)(nil).BatchCreate), ctx, content)
}

// BatchTemplate mocks base method.
func (m *MockDeviceServiceInterface) BatchTemplate() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchTemplate")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchTemplate indicates an expected call of BatchTemplate.
func (mr *MockDeviceServiceInterfaceMockRecorder) BatchTemplate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchTemplate", reflect.TypeOf((*MockDeviceServiceInterface)(nil).BatchTemplate))
}

// ClearPushRecords mocks base method.
func (m *MockDeviceServiceInterface) ClearPushRecords(ctx context.Context, deviceKey string, before *time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPushRecords", ctx, deviceKey, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearPushRecords indicates an expected call of ClearPushRecords.
func (mr *MockDeviceServiceInterfaceMockRecorder) ClearPushRecords(ctx, deviceKey, before interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPushRecords", reflect.TypeOf((*MockDeviceServiceInterface)(nil).ClearPushRecords), ctx, deviceKey, before)
}

// CreateDevice mocks base method.
func (m *MockDeviceServiceInterface) CreateDevice(ctx context.Context, d *model.Device) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", ctx, d)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockDeviceServiceInterfaceMockRecorder) CreateDevice(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockDeviceServiceInterface)(nil).CreateDevice), ctx, d)
}

// DeleteDevice mocks base method.
func (m *MockDeviceServiceInterface) DeleteDevice(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDeviceServiceInterfaceMockRecorder) DeleteDevice(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDeviceServiceInterface)(nil).DeleteDevice), ctx, id)
}

// Device mocks base method.
func (m *MockDeviceServiceInterface) Device(ctx context.Context, id int64) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Device", ctx, id)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Device indicates an expected call of Device.
func (mr *MockDeviceServiceInterfaceMockRecorder) Device(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Device", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Device), ctx, id)
}

// DeviceByKey mocks base method.
func (m *MockDeviceServiceInterface) DeviceByKey(ctx context.Context, key string) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceByKey", ctx, key)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceByKey indicates an expected call of DeviceByKey.
func (mr *MockDeviceServiceInterfaceMockRecorder) DeviceByKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceByKey", reflect.TypeOf((*MockDeviceServiceInterface)(nil).DeviceByKey), ctx, key)
}

// ListDevices mocks base method.
func (m *MockDeviceServiceInterface) ListDevices(ctx context.Context, page, size int, productID int64, states []string, enabled *bool, search string) ([]model.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", ctx, page, size, productID, states, enabled, search)
	ret0, _ := ret[0].([]model.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockDeviceServiceInterfaceMockRecorder) ListDevices(ctx, page, size, productID, states, enabled, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockDeviceServiceInterface)(nil).ListDevices), ctx, page, size, productID, states, enabled, search)
}

// ListPushRecords mocks base method.
func (m *MockDeviceServiceInterface) ListPushRecords(ctx context.Context, deviceKey string, page, size int, operationType, status string) ([]model.DevicePushRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPushRecords", ctx, deviceKey, page, size, operationType, status)
	ret0, _ := ret[0].([]model.DevicePushRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPushRecords indicates an expected call of ListPushRecords.
func (mr *MockDeviceServiceInterfaceMockRecorder) ListPushRecords(ctx, deviceKey, page, size, operationType, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPushRecords", reflect.TypeOf((*MockDeviceServiceInterface)(nil).ListPushRecords), ctx, deviceKey, page, size, operationType, status)
}

// MQTT mocks base method.
func (m *MockDeviceServiceInterface) MQTT(ctx context.Context, key string) (service.MQTTParameters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MQTT", ctx, key)
	ret0, _ := ret[0].(service.MQTTParameters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MQTT indicates an expected call of MQTT.
func (mr *MockDeviceServiceInterfaceMockRecorder) MQTT(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MQTT", reflect.TypeOf((*MockDeviceServiceInterface)(nil).MQTT), ctx, key)
}

// MockKafka mocks base method.
func (m *MockDeviceServiceInterface) MockKafka(ctx context.Context, brokers []string, topic, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MockKafka", ctx, brokers, topic, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// MockKafka indicates an expected call of MockKafka.
func (mr *MockDeviceServiceInterfaceMockRecorder) MockKafka(ctx, brokers, topic, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MockKafka", reflect.TypeOf((*MockDeviceServiceInterface)(nil).MockKafka), ctx, brokers, topic, data)
}

// MutateShadow mocks base method.
func (m *MockDeviceServiceInterface) MutateShadow(ctx context.Context, key string, version int64, source string, desired, reported *map[string]any, clear bool) (*model.DeviceShadow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MutateShadow", ctx, key, version, source, desired, reported, clear)
	ret0, _ := ret[0].(*model.DeviceShadow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MutateShadow indicates an expected call of MutateShadow.
func (mr *MockDeviceServiceInterfaceMockRecorder) MutateShadow(ctx, key, version, source, desired, reported, clear interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MutateShadow", reflect.TypeOf((*MockDeviceServiceInterface)(nil).MutateShadow), ctx, key, version, source, desired, reported, clear)
}

// PushRecord mocks base method.
func (m *MockDeviceServiceInterface) PushRecord(ctx context.Context, id int64) (*model.DevicePushRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushRecord", ctx, id)
	ret0, _ := ret[0].(*model.DevicePushRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushRecord indicates an expected call of PushRecord.
func (mr *MockDeviceServiceInterfaceMockRecorder) PushRecord(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushRecord", reflect.TypeOf((*MockDeviceServiceInterface)(nil).PushRecord), ctx, id)
}

// RemoveTags mocks base method.
func (m *MockDeviceServiceInterface) RemoveTags(ctx context.Context, key string, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTags", ctx, key, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTags indicates an expected call of RemoveTags.
func (mr *MockDeviceServiceInterfaceMockRecorder) RemoveTags(ctx, key, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTags", reflect.TypeOf((*MockDeviceServiceInterface)(nil).RemoveTags), ctx, key, keys)
}

// RestoreDevice mocks base method.
func (m *MockDeviceServiceInterface) RestoreDevice(ctx context.Context, id int64) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDevice", ctx, id)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDevice indicates an expected call of RestoreDevice.
func (mr *MockDeviceServiceInterfaceMockRecorder) RestoreDevice(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDevice", reflect.TypeOf((*MockDeviceServiceInterface)(nil).RestoreDevice), ctx, id)
}

// SetEnabled mocks base method.
func (m *MockDeviceServiceInterface) SetEnabled(ctx context.Context, id int64, v bool) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", ctx, id, v)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockDeviceServiceInterfaceMockRecorder) SetEnabled(ctx, id, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockDeviceServiceInterface)(nil).SetEnabled), ctx, id, v)
}

// SetTags mocks base method.
func (m *MockDeviceServiceInterface) SetTags(ctx context.Context, key string, tags map[string]string, replace bool) ([]model.DeviceTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTags", ctx, key, tags, replace)
	ret0, _ := ret[0].([]model.DeviceTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTags indicates an expected call of SetTags.
func (mr *MockDeviceServiceInterfaceMockRecorder) SetTags(ctx, key, tags, replace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockDeviceServiceInterface)(nil).SetTags), ctx, key, tags, replace)
}

// Shadow mocks base method.
func (m *MockDeviceServiceInterface) Shadow(ctx context.Context, key string) (*model.DeviceShadow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shadow", ctx, key)
	ret0, _ := ret[0].(*model.DeviceShadow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shadow indicates an expected call of Shadow.
func (mr *MockDeviceServiceInterfaceMockRecorder) Shadow(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shadow", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Shadow), ctx, key)
}

// ShadowHistory mocks base method.
func (m *MockDeviceServiceInterface) ShadowHistory(ctx context.Context, key string) ([]model.DeviceShadowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShadowHistory", ctx, key)
	ret0, _ := ret[0].([]model.DeviceShadowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShadowHistory indicates an expected call of ShadowHistory.
func (mr *MockDeviceServiceInterfaceMockRecorder) ShadowHistory(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShadowHistory", reflect.TypeOf((*MockDeviceServiceInterface)(nil).ShadowHistory), ctx, key)
}

// SimulatePush mocks base method.
func (m *MockDeviceServiceInterface) SimulatePush(ctx context.Context, deviceKey, payload, createdBy string) (*model.DevicePushRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulatePush", ctx, deviceKey, payload, createdBy)
	ret0, _ := ret[0].(*model.DevicePushRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulatePush indicates an expected call of SimulatePush.
func (mr *MockDeviceServiceInterfaceMockRecorder) SimulatePush(ctx, deviceKey, payload, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulatePush", reflect.TypeOf((*MockDeviceServiceInterface)(nil).SimulatePush), ctx, deviceKey, payload, createdBy)
}

// Stats mocks base method.
func (m *MockDeviceServiceInterface) Stats(ctx context.Context) (service.DeviceStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx)
	ret0, _ := ret[0].(service.DeviceStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockDeviceServiceInterfaceMockRecorder) Stats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Stats), ctx)
}

// Tags mocks base method.
func (m *MockDeviceServiceInterface) Tags(ctx context.Context, key string) ([]model.DeviceTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tags", ctx, key)
	ret0, _ := ret[0].([]model.DeviceTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tags indicates an expected call of Tags.
func (mr *MockDeviceServiceInterfaceMockRecorder) Tags(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tags", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Tags), ctx, key)
}

// Telemetry mocks base method.
func (m *MockDeviceServiceInterface) Telemetry(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Telemetry", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Telemetry indicates an expected call of Telemetry.
func (mr *MockDeviceServiceInterfaceMockRecorder) Telemetry(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Telemetry", reflect.TypeOf((*MockDeviceServiceInterface)(nil).Telemetry), ctx, key)
}

// UpdateDevice mocks base method.
func (m *MockDeviceServiceInterface) UpdateDevice(ctx context.Context, id int64, name, state string, metadata json.RawMessage) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, id, name, state, metadata)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockDeviceServiceInterfaceMockRecorder) UpdateDevice(ctx, id, name, state, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockDeviceServiceInterface)(nil).UpdateDevice), ctx, id, name, state, metadata)
}
