// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/rule.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "0things-backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRuleServiceInterface is a mock of RuleServiceInterface interface.
type MockRuleServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRuleServiceInterfaceMockRecorder
}

// MockRuleServiceInterfaceMockRecorder is the mock recorder for MockRuleServiceInterface.
type MockRuleServiceInterfaceMockRecorder struct {
	mock *MockRuleServiceInterface
}

// NewMockRuleServiceInterface creates a new mock instance.
func NewMockRuleServiceInterface(ctrl *gomock.Controller) *MockRuleServiceInterface {
	mock := &MockRuleServiceInterface{ctrl: ctrl}
	mock.recorder = &MockRuleServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleServiceInterface) EXPECT() *MockRuleServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRuleServiceInterface) Create(ctx context.Context, rule *model.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRuleServiceInterfaceMockRecorder) Create(ctx, rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuleServiceInterface)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockRuleServiceInterface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleServiceInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleServiceInterface)(nil).Delete), ctx, id)
}

// Evaluate mocks base method.
func (m *MockRuleServiceInterface) Evaluate(ctx context.Context, id int64) (*model.RuleExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, id)
	ret0, _ := ret[0].(*model.RuleExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockRuleServiceInterfaceMockRecorder) Evaluate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockRuleServiceInterface)(nil).Evaluate), ctx, id)
}

// Get mocks base method.
func (m *MockRuleServiceInterface) Get(ctx context.Context, id int64) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRuleServiceInterfaceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRuleServiceInterface)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRuleServiceInterface) List(ctx context.Context, page, size int, ruleType, status, search string) ([]model.Rule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, ruleType, status, search)
	ret0, _ := ret[0].([]model.Rule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRuleServiceInterfaceMockRecorder) List(ctx, page, size, ruleType, status, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRuleServiceInterface)(nil).List), ctx, page, size, ruleType, status, search)
}

// ListExecutions mocks base method.
func (m *MockRuleServiceInterface) ListExecutions(ctx context.Context, id int64, page, size int) ([]model.RuleExecution, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecutions", ctx, id, page, size)
	ret0, _ := ret[0].([]model.RuleExecution)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExecutions indicates an expected call of ListExecutions.
func (mr *MockRuleServiceInterfaceMockRecorder) ListExecutions(ctx, id, page, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecutions", reflect.TypeOf((*MockRuleServiceInterface)(nil).ListExecutions), ctx, id, page, size)
}

// SetStatus mocks base method.
func (m *MockRuleServiceInterface) SetStatus(ctx context.Context, id int64, status string) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockRuleServiceInterfaceMockRecorder) SetStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockRuleServiceInterface)(nil).SetStatus), ctx, id, status)
}

// Update mocks base method.
func (m *MockRuleServiceInterface) Update(ctx context.Context, rule *model.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRuleServiceInterfaceMockRecorder) Update(ctx, rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleServiceInterface)(nil).Update), ctx, rule)
}
