// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-mqtt/internal/consumer"
	"transport-mqtt/internal/handler"
	"transport-mqtt/internal/server"
	"transport-mqtt/pkg/app"
	"transport-mqtt/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	wireEventBusHolder, cleanup, err := provideEventBus(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	producer := provideEventProducer(wireEventBusHolder)
	ingressHandler := handler.NewIngressHandler(producer, logger)
	client, err := server.NewMQTTClient(viperViper, logger, ingressHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventConsumer := provideEventConsumer(wireEventBusHolder)
	otaCommandConsumer := consumer.NewOTACommandConsumer(client, logger)
	manager := consumer.NewManager(eventConsumer, otaCommandConsumer, logger)
	mqttServer := server.NewMQTTServer(client, logger, manager)
	appApp := newApp(mqttServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

type eventBusHolder struct {
	producer event.Producer
	consumer event.Consumer
}

func provideEventBus(conf *viper.Viper, logger *log.Logger) (*eventBusHolder, func(), error) {
	pub, sub, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	producer := event.NewProducer(pub)
	consumer2 := event.NewConsumer(sub, logger.Logger)
	cleanup := func() {
		_ = producer.Close()
		_ = consumer2.Close()
	}
	return &eventBusHolder{producer: producer, consumer: consumer2}, cleanup, nil
}

func provideEventProducer(holder *eventBusHolder) event.Producer {
	return holder.producer
}

func provideEventConsumer(holder *eventBusHolder) event.Consumer {
	return holder.consumer
}

var serverSet = wire.NewSet(handler.NewIngressHandler, consumer.NewOTACommandConsumer, consumer.NewManager, server.NewMQTTClient, server.NewMQTTServer)

func newApp(
	mqttServer *server.MQTTServer,
) *app.App {
	return app.NewApp(app.WithServer(mqttServer), app.WithName("0things-transport-mqtt"))
}
