// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-mqtt/internal/server"
	"transport-mqtt/pkg/app"
	"transport-mqtt/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	producer, cleanup, err := provideEventProducer(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	mqttServer, err := server.NewMQTTServer(viperViper, logger, producer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appApp := newApp(mqttServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideEventProducer(conf *viper.Viper, logger *log.Logger) (event.Producer, func(), error) {
	pub, _, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	producer := event.NewProducer(pub)
	cleanup := func() {
		_ = producer.Close()
	}
	return producer, cleanup, nil
}

var serverSet = wire.NewSet(server.NewMQTTServer)

func newApp(
	mqttServer *server.MQTTServer,
) *app.App {
	return app.NewApp(app.WithServer(mqttServer), app.WithName("0things-transport-mqtt"))
}
