{{- if .Values.clusterIssuer }}
apiVersion: v1
kind: Secret
metadata:
  name: alidns-credentials
type: Opaque
stringData:
  accessKeyID: {{ required "clusterIssuer.accessKeyID is required" .Values.clusterIssuer.accessKeyID | quote }}
  accessKeySecret: {{ required "clusterIssuer.accessKeySecret is required" .Values.clusterIssuer.accessKeySecret | quote }}
{{- end }}
