// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"aiot-backend/internal/server"
	"aiot-backend/pkg/app"
	"aiot-backend/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	taskServer := server.NewTaskServer(logger)
	appApp := newApp(taskServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewTaskServer)

// build App
func newApp(
	task *server.TaskServer,
) *app.App {
	return app.NewApp(app.WithServer(task), app.WithName("demo-task"))
}
