{{/* Chart name. */}}
{{- define "0things.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Release-scoped full name. */}}
{{- define "0things.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := include "0things.name" . -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/* Chart label value. */}}
{{- define "0things.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Name for one release component. */}}
{{- define "0things.componentName" -}}
{{- printf "%s-%s" (include "0things.fullname" .root) .component | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Recommended labels shared by all resources. */}}
{{- define "0things.labels" -}}
helm.sh/chart: {{ include "0things.chart" .root }}
{{ include "0things.selectorLabels" . }}
app.kubernetes.io/version: {{ .root.Chart.AppVersion | quote }}
app.kubernetes.io/part-of: {{ include "0things.name" .root }}
app.kubernetes.io/managed-by: {{ .root.Release.Service }}
{{- with .root.Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end -}}

{{/* Immutable selector labels. */}}
{{- define "0things.selectorLabels" -}}
app.kubernetes.io/name: {{ include "0things.name" .root }}
app.kubernetes.io/instance: {{ .root.Release.Name }}
app.kubernetes.io/component: {{ .component }}
{{- end -}}

{{/* Registry secret generated by this chart. */}}
{{- define "0things.registrySecretName" -}}
{{- default (printf "%s-registry" (include "0things.fullname" .)) .Values.registry.existingSecret | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Resolve a chart-created or pre-existing secret name. */}}
{{- define "0things.secretName" -}}
{{- if .create -}}
{{- include "0things.componentName" (dict "root" .root "component" .component) -}}
{{- else -}}
{{- required (printf "%s.existingSecret is required when secret creation is disabled" .valuePath) .existingSecret -}}
{{- end -}}
{{- end -}}

{{/* Render image pull secrets only when configured. */}}
{{- define "0things.imagePullSecrets" -}}
{{- if or .Values.registry.create .Values.imagePullSecrets }}
imagePullSecrets:
  {{- if .Values.registry.create }}
  - name: {{ include "0things.registrySecretName" . }}
  {{- end }}
  {{- range .Values.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end -}}

{{/* Shared pod security context. */}}
{{- define "0things.podSecurityContext" -}}
{{- with .Values.podSecurityContext }}
securityContext:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end -}}

{{/* Shared container security context. */}}
{{- define "0things.containerSecurityContext" -}}
{{- with .Values.containerSecurityContext }}
securityContext:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end -}}

{{/* Optional storage class stanza for volumeClaimTemplates. */}}
{{- define "0things.storageClass" -}}
{{- if .storageClass }}
storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end -}}
