env: local

mqtt:
  broker: "ssl://127.0.0.1:8883"
  client_id: "0things-mqtt-transport"
  username: ""
  password: ""
  tls:
    ca_file: ""
    cert_file: ""
    key_file: ""


log:
  log_level: debug
  mode: console
  encoding: console
  log_file_name: "./storage/logs/mqtt-transport.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
