// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-coap/internal/server"
	"transport-coap/pkg/app"
	"transport-coap/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	producer, cleanup, err := provideEventProducer(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	coAPServer := server.NewCoAPServer(viperViper, logger, producer)
	appApp := newApp(coAPServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideEventProducer(conf *viper.Viper, logger *log.Logger) (event.Producer, func(), error) {
	pub, _, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	producer := event.NewProducer(pub)
	cleanup := func() {
		_ = producer.Close()
	}
	return producer, cleanup, nil
}

var serverSet = wire.NewSet(server.NewCoAPServer)

func newApp(
	coapServer *server.CoAPServer,
) *app.App {
	return app.NewApp(app.WithServer(coapServer), app.WithName("0things-transport-coap"))
}
