// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-coap/internal/server"
	"transport-coap/pkg/app"
	"transport-coap/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	coAPServer := server.NewCoAPServer(viperViper, logger)
	appApp := newApp(coAPServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewCoAPServer)

func newApp(
	coapServer *server.CoAPServer,
) *app.App {
	return app.NewApp(app.WithServer(coapServer), app.WithName("0things-transport-coap"))
}
