// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"0things-backend/internal/model"
)

func newDevicePushRecord(db *gorm.DB, opts ...gen.DOOption) devicePushRecord {
	_devicePushRecord := devicePushRecord{}

	_devicePushRecord.devicePushRecordDo.UseDB(db, opts...)
	_devicePushRecord.devicePushRecordDo.UseModel(&model.DevicePushRecord{})

	tableName := _devicePushRecord.devicePushRecordDo.TableName()
	_devicePushRecord.ALL = field.NewAsterisk(tableName)
	_devicePushRecord.ID = field.NewInt64(tableName, "id")
	_devicePushRecord.DeviceID = field.NewInt64(tableName, "device_id")
	_devicePushRecord.OperationType = field.NewString(tableName, "operation_type")
	_devicePushRecord.OperationName = field.NewString(tableName, "operation_name")
	_devicePushRecord.Payload = field.NewString(tableName, "payload")
	_devicePushRecord.Status = field.NewString(tableName, "status")
	_devicePushRecord.ErrorMessage = field.NewString(tableName, "error_message")
	_devicePushRecord.CreatedBy = field.NewString(tableName, "created_by")
	_devicePushRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_devicePushRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_devicePushRecord.fillFieldMap()

	return _devicePushRecord
}

type devicePushRecord struct {
	devicePushRecordDo devicePushRecordDo

	ALL           field.Asterisk
	ID            field.Int64
	DeviceID      field.Int64
	OperationType field.String
	OperationName field.String
	Payload       field.String
	Status        field.String
	ErrorMessage  field.String
	CreatedBy     field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (d devicePushRecord) Table(newTableName string) *devicePushRecord {
	d.devicePushRecordDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d devicePushRecord) As(alias string) *devicePushRecord {
	d.devicePushRecordDo.DO = *(d.devicePushRecordDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *devicePushRecord) updateTableName(table string) *devicePushRecord {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceID = field.NewInt64(table, "device_id")
	d.OperationType = field.NewString(table, "operation_type")
	d.OperationName = field.NewString(table, "operation_name")
	d.Payload = field.NewString(table, "payload")
	d.Status = field.NewString(table, "status")
	d.ErrorMessage = field.NewString(table, "error_message")
	d.CreatedBy = field.NewString(table, "created_by")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *devicePushRecord) WithContext(ctx context.Context) *devicePushRecordDo {
	return d.devicePushRecordDo.WithContext(ctx)
}

func (d devicePushRecord) TableName() string { return d.devicePushRecordDo.TableName() }

func (d devicePushRecord) Alias() string { return d.devicePushRecordDo.Alias() }

func (d devicePushRecord) Columns(cols ...field.Expr) gen.Columns {
	return d.devicePushRecordDo.Columns(cols...)
}

func (d *devicePushRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *devicePushRecord) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["operation_type"] = d.OperationType
	d.fieldMap["operation_name"] = d.OperationName
	d.fieldMap["payload"] = d.Payload
	d.fieldMap["status"] = d.Status
	d.fieldMap["error_message"] = d.ErrorMessage
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d devicePushRecord) clone(db *gorm.DB) devicePushRecord {
	d.devicePushRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d devicePushRecord) replaceDB(db *gorm.DB) devicePushRecord {
	d.devicePushRecordDo.ReplaceDB(db)
	return d
}

type devicePushRecordDo struct{ gen.DO }

func (d devicePushRecordDo) Debug() *devicePushRecordDo {
	return d.withDO(d.DO.Debug())
}

func (d devicePushRecordDo) WithContext(ctx context.Context) *devicePushRecordDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d devicePushRecordDo) ReadDB() *devicePushRecordDo {
	return d.Clauses(dbresolver.Read)
}

func (d devicePushRecordDo) WriteDB() *devicePushRecordDo {
	return d.Clauses(dbresolver.Write)
}

func (d devicePushRecordDo) Session(config *gorm.Session) *devicePushRecordDo {
	return d.withDO(d.DO.Session(config))
}

func (d devicePushRecordDo) Clauses(conds ...clause.Expression) *devicePushRecordDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d devicePushRecordDo) Returning(value interface{}, columns ...string) *devicePushRecordDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d devicePushRecordDo) Not(conds ...gen.Condition) *devicePushRecordDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d devicePushRecordDo) Or(conds ...gen.Condition) *devicePushRecordDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d devicePushRecordDo) Select(conds ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d devicePushRecordDo) Where(conds ...gen.Condition) *devicePushRecordDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d devicePushRecordDo) Order(conds ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d devicePushRecordDo) Distinct(cols ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d devicePushRecordDo) Omit(cols ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d devicePushRecordDo) Join(table schema.Tabler, on ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d devicePushRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d devicePushRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d devicePushRecordDo) Group(cols ...field.Expr) *devicePushRecordDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d devicePushRecordDo) Having(conds ...gen.Condition) *devicePushRecordDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d devicePushRecordDo) Limit(limit int) *devicePushRecordDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d devicePushRecordDo) Offset(offset int) *devicePushRecordDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d devicePushRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *devicePushRecordDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d devicePushRecordDo) Unscoped() *devicePushRecordDo {
	return d.withDO(d.DO.Unscoped())
}

func (d devicePushRecordDo) Create(values ...*model.DevicePushRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d devicePushRecordDo) CreateInBatches(values []*model.DevicePushRecord, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d devicePushRecordDo) Save(values ...*model.DevicePushRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d devicePushRecordDo) First() (*model.DevicePushRecord, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DevicePushRecord), nil
	}
}

func (d devicePushRecordDo) Take() (*model.DevicePushRecord, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DevicePushRecord), nil
	}
}

func (d devicePushRecordDo) Last() (*model.DevicePushRecord, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DevicePushRecord), nil
	}
}

func (d devicePushRecordDo) Find() ([]*model.DevicePushRecord, error) {
	result, err := d.DO.Find()
	return result.([]*model.DevicePushRecord), err
}

func (d devicePushRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DevicePushRecord, err error) {
	buf := make([]*model.DevicePushRecord, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d devicePushRecordDo) FindInBatches(result *[]*model.DevicePushRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d devicePushRecordDo) Attrs(attrs ...field.AssignExpr) *devicePushRecordDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d devicePushRecordDo) Assign(attrs ...field.AssignExpr) *devicePushRecordDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d devicePushRecordDo) Joins(fields ...field.RelationField) *devicePushRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d devicePushRecordDo) Preload(fields ...field.RelationField) *devicePushRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d devicePushRecordDo) FirstOrInit() (*model.DevicePushRecord, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DevicePushRecord), nil
	}
}

func (d devicePushRecordDo) FirstOrCreate() (*model.DevicePushRecord, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DevicePushRecord), nil
	}
}

func (d devicePushRecordDo) FindByPage(offset int, limit int) (result []*model.DevicePushRecord, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d devicePushRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d devicePushRecordDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d devicePushRecordDo) Delete(models ...*model.DevicePushRecord) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *devicePushRecordDo) withDO(do gen.Dao) *devicePushRecordDo {
	d.DO = *do.(*gen.DO)
	return d
}
