// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"0things-backend/internal/model"
)

func newOTAPackage(db *gorm.DB, opts ...gen.DOOption) oTAPackage {
	_oTAPackage := oTAPackage{}

	_oTAPackage.oTAPackageDo.UseDB(db, opts...)
	_oTAPackage.oTAPackageDo.UseModel(&model.OTAPackage{})

	tableName := _oTAPackage.oTAPackageDo.TableName()
	_oTAPackage.ALL = field.NewAsterisk(tableName)
	_oTAPackage.ID = field.NewInt64(tableName, "id")
	_oTAPackage.PackageName = field.NewString(tableName, "package_name")
	_oTAPackage.Version = field.NewString(tableName, "version")
	_oTAPackage.ProductID = field.NewInt64(tableName, "product_id")
	_oTAPackage.TenantID = field.NewInt64(tableName, "tenant_id")
	_oTAPackage.PackageType = field.NewString(tableName, "package_type")
	_oTAPackage.Status = field.NewString(tableName, "status")
	_oTAPackage.UploadType = field.NewString(tableName, "upload_type")
	_oTAPackage.FileURL = field.NewString(tableName, "file_url")
	_oTAPackage.FileSize = field.NewInt64(tableName, "file_size")
	_oTAPackage.Checksum = field.NewString(tableName, "checksum")
	_oTAPackage.Description = field.NewString(tableName, "description")
	_oTAPackage.ReleaseNotes = field.NewString(tableName, "release_notes")
	_oTAPackage.DeletedAt = field.NewField(tableName, "deleted_at")
	_oTAPackage.CreatedAt = field.NewTime(tableName, "created_at")
	_oTAPackage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_oTAPackage.ReleasedAt = field.NewTime(tableName, "released_at")

	_oTAPackage.fillFieldMap()

	return _oTAPackage
}

type oTAPackage struct {
	oTAPackageDo oTAPackageDo

	ALL          field.Asterisk
	ID           field.Int64
	PackageName  field.String
	Version      field.String
	ProductID    field.Int64
	TenantID     field.Int64
	PackageType  field.String
	Status       field.String
	UploadType   field.String
	FileURL      field.String
	FileSize     field.Int64
	Checksum     field.String
	Description  field.String
	ReleaseNotes field.String
	DeletedAt    field.Field
	CreatedAt    field.Time
	UpdatedAt    field.Time
	ReleasedAt   field.Time

	fieldMap map[string]field.Expr
}

func (o oTAPackage) Table(newTableName string) *oTAPackage {
	o.oTAPackageDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oTAPackage) As(alias string) *oTAPackage {
	o.oTAPackageDo.DO = *(o.oTAPackageDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oTAPackage) updateTableName(table string) *oTAPackage {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.PackageName = field.NewString(table, "package_name")
	o.Version = field.NewString(table, "version")
	o.ProductID = field.NewInt64(table, "product_id")
	o.TenantID = field.NewInt64(table, "tenant_id")
	o.PackageType = field.NewString(table, "package_type")
	o.Status = field.NewString(table, "status")
	o.UploadType = field.NewString(table, "upload_type")
	o.FileURL = field.NewString(table, "file_url")
	o.FileSize = field.NewInt64(table, "file_size")
	o.Checksum = field.NewString(table, "checksum")
	o.Description = field.NewString(table, "description")
	o.ReleaseNotes = field.NewString(table, "release_notes")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.ReleasedAt = field.NewTime(table, "released_at")

	o.fillFieldMap()

	return o
}

func (o *oTAPackage) WithContext(ctx context.Context) *oTAPackageDo {
	return o.oTAPackageDo.WithContext(ctx)
}

func (o oTAPackage) TableName() string { return o.oTAPackageDo.TableName() }

func (o oTAPackage) Alias() string { return o.oTAPackageDo.Alias() }

func (o oTAPackage) Columns(cols ...field.Expr) gen.Columns { return o.oTAPackageDo.Columns(cols...) }

func (o *oTAPackage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oTAPackage) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 18)
	o.fieldMap["id"] = o.ID
	o.fieldMap["package_name"] = o.PackageName
	o.fieldMap["version"] = o.Version
	o.fieldMap["product_id"] = o.ProductID
	o.fieldMap["tenant_id"] = o.TenantID
	o.fieldMap["package_type"] = o.PackageType
	o.fieldMap["status"] = o.Status
	o.fieldMap["upload_type"] = o.UploadType
	o.fieldMap["file_url"] = o.FileURL
	o.fieldMap["file_size"] = o.FileSize
	o.fieldMap["checksum"] = o.Checksum
	o.fieldMap["description"] = o.Description
	o.fieldMap["release_notes"] = o.ReleaseNotes
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["released_at"] = o.ReleasedAt
}

func (o oTAPackage) clone(db *gorm.DB) oTAPackage {
	o.oTAPackageDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oTAPackage) replaceDB(db *gorm.DB) oTAPackage {
	o.oTAPackageDo.ReplaceDB(db)
	return o
}

type oTAPackageDo struct{ gen.DO }

func (o oTAPackageDo) Debug() *oTAPackageDo {
	return o.withDO(o.DO.Debug())
}

func (o oTAPackageDo) WithContext(ctx context.Context) *oTAPackageDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oTAPackageDo) ReadDB() *oTAPackageDo {
	return o.Clauses(dbresolver.Read)
}

func (o oTAPackageDo) WriteDB() *oTAPackageDo {
	return o.Clauses(dbresolver.Write)
}

func (o oTAPackageDo) Session(config *gorm.Session) *oTAPackageDo {
	return o.withDO(o.DO.Session(config))
}

func (o oTAPackageDo) Clauses(conds ...clause.Expression) *oTAPackageDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oTAPackageDo) Returning(value interface{}, columns ...string) *oTAPackageDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oTAPackageDo) Not(conds ...gen.Condition) *oTAPackageDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oTAPackageDo) Or(conds ...gen.Condition) *oTAPackageDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oTAPackageDo) Select(conds ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oTAPackageDo) Where(conds ...gen.Condition) *oTAPackageDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oTAPackageDo) Order(conds ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oTAPackageDo) Distinct(cols ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oTAPackageDo) Omit(cols ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oTAPackageDo) Join(table schema.Tabler, on ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oTAPackageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oTAPackageDo) RightJoin(table schema.Tabler, on ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oTAPackageDo) Group(cols ...field.Expr) *oTAPackageDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oTAPackageDo) Having(conds ...gen.Condition) *oTAPackageDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oTAPackageDo) Limit(limit int) *oTAPackageDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oTAPackageDo) Offset(offset int) *oTAPackageDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oTAPackageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oTAPackageDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oTAPackageDo) Unscoped() *oTAPackageDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oTAPackageDo) Create(values ...*model.OTAPackage) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oTAPackageDo) CreateInBatches(values []*model.OTAPackage, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oTAPackageDo) Save(values ...*model.OTAPackage) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oTAPackageDo) First() (*model.OTAPackage, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAPackage), nil
	}
}

func (o oTAPackageDo) Take() (*model.OTAPackage, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAPackage), nil
	}
}

func (o oTAPackageDo) Last() (*model.OTAPackage, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAPackage), nil
	}
}

func (o oTAPackageDo) Find() ([]*model.OTAPackage, error) {
	result, err := o.DO.Find()
	return result.([]*model.OTAPackage), err
}

func (o oTAPackageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OTAPackage, err error) {
	buf := make([]*model.OTAPackage, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oTAPackageDo) FindInBatches(result *[]*model.OTAPackage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oTAPackageDo) Attrs(attrs ...field.AssignExpr) *oTAPackageDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oTAPackageDo) Assign(attrs ...field.AssignExpr) *oTAPackageDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oTAPackageDo) Joins(fields ...field.RelationField) *oTAPackageDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oTAPackageDo) Preload(fields ...field.RelationField) *oTAPackageDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oTAPackageDo) FirstOrInit() (*model.OTAPackage, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAPackage), nil
	}
}

func (o oTAPackageDo) FirstOrCreate() (*model.OTAPackage, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAPackage), nil
	}
}

func (o oTAPackageDo) FindByPage(offset int, limit int) (result []*model.OTAPackage, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oTAPackageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oTAPackageDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oTAPackageDo) Delete(models ...*model.OTAPackage) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oTAPackageDo) withDO(do gen.Dao) *oTAPackageDo {
	o.DO = *do.(*gen.DO)
	return o
}
