// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"0things-backend/internal/model"
)

func newRule(db *gorm.DB, opts ...gen.DOOption) rule {
	_rule := rule{}

	_rule.ruleDo.UseDB(db, opts...)
	_rule.ruleDo.UseModel(&model.Rule{})

	tableName := _rule.ruleDo.TableName()
	_rule.ALL = field.NewAsterisk(tableName)
	_rule.ID = field.NewInt64(tableName, "id")
	_rule.Name = field.NewString(tableName, "name")
	_rule.Description = field.NewString(tableName, "description")
	_rule.Type = field.NewString(tableName, "type")
	_rule.Status = field.NewString(tableName, "status")
	_rule.ProductID = field.NewInt64(tableName, "product_id")
	_rule.Priority = field.NewInt(tableName, "priority")
	_rule.TriggerConfig = field.NewBytes(tableName, "trigger_config")
	_rule.ConditionConfig = field.NewBytes(tableName, "condition_config")
	_rule.ActionConfig = field.NewBytes(tableName, "action_config")
	_rule.SQLConfig = field.NewBytes(tableName, "sql_config")
	_rule.ExecutionCount = field.NewInt64(tableName, "execution_count")
	_rule.SuccessCount = field.NewInt64(tableName, "success_count")
	_rule.FailureCount = field.NewInt64(tableName, "failure_count")
	_rule.LastExecutionStatus = field.NewString(tableName, "last_execution_status")
	_rule.CreatedBy = field.NewString(tableName, "created_by")
	_rule.Tags = field.NewBytes(tableName, "tags")
	_rule.LastExecutedAt = field.NewTime(tableName, "last_executed_at")
	_rule.CreatedAt = field.NewTime(tableName, "created_at")
	_rule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rule.fillFieldMap()

	return _rule
}

type rule struct {
	ruleDo ruleDo

	ALL                 field.Asterisk
	ID                  field.Int64
	Name                field.String
	Description         field.String
	Type                field.String
	Status              field.String
	ProductID           field.Int64
	Priority            field.Int
	TriggerConfig       field.Bytes
	ConditionConfig     field.Bytes
	ActionConfig        field.Bytes
	SQLConfig           field.Bytes
	ExecutionCount      field.Int64
	SuccessCount        field.Int64
	FailureCount        field.Int64
	LastExecutionStatus field.String
	CreatedBy           field.String
	Tags                field.Bytes
	LastExecutedAt      field.Time
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (r rule) Table(newTableName string) *rule {
	r.ruleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rule) As(alias string) *rule {
	r.ruleDo.DO = *(r.ruleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rule) updateTableName(table string) *rule {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Name = field.NewString(table, "name")
	r.Description = field.NewString(table, "description")
	r.Type = field.NewString(table, "type")
	r.Status = field.NewString(table, "status")
	r.ProductID = field.NewInt64(table, "product_id")
	r.Priority = field.NewInt(table, "priority")
	r.TriggerConfig = field.NewBytes(table, "trigger_config")
	r.ConditionConfig = field.NewBytes(table, "condition_config")
	r.ActionConfig = field.NewBytes(table, "action_config")
	r.SQLConfig = field.NewBytes(table, "sql_config")
	r.ExecutionCount = field.NewInt64(table, "execution_count")
	r.SuccessCount = field.NewInt64(table, "success_count")
	r.FailureCount = field.NewInt64(table, "failure_count")
	r.LastExecutionStatus = field.NewString(table, "last_execution_status")
	r.CreatedBy = field.NewString(table, "created_by")
	r.Tags = field.NewBytes(table, "tags")
	r.LastExecutedAt = field.NewTime(table, "last_executed_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rule) WithContext(ctx context.Context) *ruleDo { return r.ruleDo.WithContext(ctx) }

func (r rule) TableName() string { return r.ruleDo.TableName() }

func (r rule) Alias() string { return r.ruleDo.Alias() }

func (r rule) Columns(cols ...field.Expr) gen.Columns { return r.ruleDo.Columns(cols...) }

func (r *rule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rule) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 20)
	r.fieldMap["id"] = r.ID
	r.fieldMap["name"] = r.Name
	r.fieldMap["description"] = r.Description
	r.fieldMap["type"] = r.Type
	r.fieldMap["status"] = r.Status
	r.fieldMap["product_id"] = r.ProductID
	r.fieldMap["priority"] = r.Priority
	r.fieldMap["trigger_config"] = r.TriggerConfig
	r.fieldMap["condition_config"] = r.ConditionConfig
	r.fieldMap["action_config"] = r.ActionConfig
	r.fieldMap["sql_config"] = r.SQLConfig
	r.fieldMap["execution_count"] = r.ExecutionCount
	r.fieldMap["success_count"] = r.SuccessCount
	r.fieldMap["failure_count"] = r.FailureCount
	r.fieldMap["last_execution_status"] = r.LastExecutionStatus
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["tags"] = r.Tags
	r.fieldMap["last_executed_at"] = r.LastExecutedAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rule) clone(db *gorm.DB) rule {
	r.ruleDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rule) replaceDB(db *gorm.DB) rule {
	r.ruleDo.ReplaceDB(db)
	return r
}

type ruleDo struct{ gen.DO }

func (r ruleDo) Debug() *ruleDo {
	return r.withDO(r.DO.Debug())
}

func (r ruleDo) WithContext(ctx context.Context) *ruleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ruleDo) ReadDB() *ruleDo {
	return r.Clauses(dbresolver.Read)
}

func (r ruleDo) WriteDB() *ruleDo {
	return r.Clauses(dbresolver.Write)
}

func (r ruleDo) Session(config *gorm.Session) *ruleDo {
	return r.withDO(r.DO.Session(config))
}

func (r ruleDo) Clauses(conds ...clause.Expression) *ruleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ruleDo) Returning(value interface{}, columns ...string) *ruleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ruleDo) Not(conds ...gen.Condition) *ruleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ruleDo) Or(conds ...gen.Condition) *ruleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ruleDo) Select(conds ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ruleDo) Where(conds ...gen.Condition) *ruleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ruleDo) Order(conds ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ruleDo) Distinct(cols ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ruleDo) Omit(cols ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ruleDo) Join(table schema.Tabler, on ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ruleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ruleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ruleDo) RightJoin(table schema.Tabler, on ...field.Expr) *ruleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ruleDo) Group(cols ...field.Expr) *ruleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ruleDo) Having(conds ...gen.Condition) *ruleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ruleDo) Limit(limit int) *ruleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ruleDo) Offset(offset int) *ruleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ruleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ruleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ruleDo) Unscoped() *ruleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ruleDo) Create(values ...*model.Rule) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ruleDo) CreateInBatches(values []*model.Rule, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ruleDo) Save(values ...*model.Rule) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ruleDo) First() (*model.Rule, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rule), nil
	}
}

func (r ruleDo) Take() (*model.Rule, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rule), nil
	}
}

func (r ruleDo) Last() (*model.Rule, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rule), nil
	}
}

func (r ruleDo) Find() ([]*model.Rule, error) {
	result, err := r.DO.Find()
	return result.([]*model.Rule), err
}

func (r ruleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Rule, err error) {
	buf := make([]*model.Rule, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ruleDo) FindInBatches(result *[]*model.Rule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ruleDo) Attrs(attrs ...field.AssignExpr) *ruleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ruleDo) Assign(attrs ...field.AssignExpr) *ruleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ruleDo) Joins(fields ...field.RelationField) *ruleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ruleDo) Preload(fields ...field.RelationField) *ruleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ruleDo) FirstOrInit() (*model.Rule, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rule), nil
	}
}

func (r ruleDo) FirstOrCreate() (*model.Rule, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rule), nil
	}
}

func (r ruleDo) FindByPage(offset int, limit int) (result []*model.Rule, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ruleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ruleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ruleDo) Delete(models ...*model.Rule) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ruleDo) withDO(do gen.Dao) *ruleDo {
	r.DO = *do.(*gen.DO)
	return r
}
