// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"0things-backend/internal/model"
)

func newRuleExecution(db *gorm.DB, opts ...gen.DOOption) ruleExecution {
	_ruleExecution := ruleExecution{}

	_ruleExecution.ruleExecutionDo.UseDB(db, opts...)
	_ruleExecution.ruleExecutionDo.UseModel(&model.RuleExecution{})

	tableName := _ruleExecution.ruleExecutionDo.TableName()
	_ruleExecution.ALL = field.NewAsterisk(tableName)
	_ruleExecution.ID = field.NewInt64(tableName, "id")
	_ruleExecution.RuleID = field.NewInt64(tableName, "rule_id")
	_ruleExecution.RuleName = field.NewString(tableName, "rule_name")
	_ruleExecution.Status = field.NewString(tableName, "status")
	_ruleExecution.TriggerData = field.NewBytes(tableName, "trigger_data")
	_ruleExecution.ConditionResult = field.NewBool(tableName, "condition_result")
	_ruleExecution.Duration = field.NewInt(tableName, "duration")
	_ruleExecution.Error = field.NewString(tableName, "error")
	_ruleExecution.TriggeredAt = field.NewTime(tableName, "triggered_at")
	_ruleExecution.CreatedAt = field.NewTime(tableName, "created_at")

	_ruleExecution.fillFieldMap()

	return _ruleExecution
}

type ruleExecution struct {
	ruleExecutionDo ruleExecutionDo

	ALL             field.Asterisk
	ID              field.Int64
	RuleID          field.Int64
	RuleName        field.String
	Status          field.String
	TriggerData     field.Bytes
	ConditionResult field.Bool
	Duration        field.Int
	Error           field.String
	TriggeredAt     field.Time
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (r ruleExecution) Table(newTableName string) *ruleExecution {
	r.ruleExecutionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ruleExecution) As(alias string) *ruleExecution {
	r.ruleExecutionDo.DO = *(r.ruleExecutionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ruleExecution) updateTableName(table string) *ruleExecution {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.RuleID = field.NewInt64(table, "rule_id")
	r.RuleName = field.NewString(table, "rule_name")
	r.Status = field.NewString(table, "status")
	r.TriggerData = field.NewBytes(table, "trigger_data")
	r.ConditionResult = field.NewBool(table, "condition_result")
	r.Duration = field.NewInt(table, "duration")
	r.Error = field.NewString(table, "error")
	r.TriggeredAt = field.NewTime(table, "triggered_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *ruleExecution) WithContext(ctx context.Context) *ruleExecutionDo {
	return r.ruleExecutionDo.WithContext(ctx)
}

func (r ruleExecution) TableName() string { return r.ruleExecutionDo.TableName() }

func (r ruleExecution) Alias() string { return r.ruleExecutionDo.Alias() }

func (r ruleExecution) Columns(cols ...field.Expr) gen.Columns {
	return r.ruleExecutionDo.Columns(cols...)
}

func (r *ruleExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ruleExecution) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["rule_id"] = r.RuleID
	r.fieldMap["rule_name"] = r.RuleName
	r.fieldMap["status"] = r.Status
	r.fieldMap["trigger_data"] = r.TriggerData
	r.fieldMap["condition_result"] = r.ConditionResult
	r.fieldMap["duration"] = r.Duration
	r.fieldMap["error"] = r.Error
	r.fieldMap["triggered_at"] = r.TriggeredAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r ruleExecution) clone(db *gorm.DB) ruleExecution {
	r.ruleExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ruleExecution) replaceDB(db *gorm.DB) ruleExecution {
	r.ruleExecutionDo.ReplaceDB(db)
	return r
}

type ruleExecutionDo struct{ gen.DO }

func (r ruleExecutionDo) Debug() *ruleExecutionDo {
	return r.withDO(r.DO.Debug())
}

func (r ruleExecutionDo) WithContext(ctx context.Context) *ruleExecutionDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ruleExecutionDo) ReadDB() *ruleExecutionDo {
	return r.Clauses(dbresolver.Read)
}

func (r ruleExecutionDo) WriteDB() *ruleExecutionDo {
	return r.Clauses(dbresolver.Write)
}

func (r ruleExecutionDo) Session(config *gorm.Session) *ruleExecutionDo {
	return r.withDO(r.DO.Session(config))
}

func (r ruleExecutionDo) Clauses(conds ...clause.Expression) *ruleExecutionDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ruleExecutionDo) Returning(value interface{}, columns ...string) *ruleExecutionDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ruleExecutionDo) Not(conds ...gen.Condition) *ruleExecutionDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ruleExecutionDo) Or(conds ...gen.Condition) *ruleExecutionDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ruleExecutionDo) Select(conds ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ruleExecutionDo) Where(conds ...gen.Condition) *ruleExecutionDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ruleExecutionDo) Order(conds ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ruleExecutionDo) Distinct(cols ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ruleExecutionDo) Omit(cols ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ruleExecutionDo) Join(table schema.Tabler, on ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ruleExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ruleExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ruleExecutionDo) Group(cols ...field.Expr) *ruleExecutionDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ruleExecutionDo) Having(conds ...gen.Condition) *ruleExecutionDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ruleExecutionDo) Limit(limit int) *ruleExecutionDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ruleExecutionDo) Offset(offset int) *ruleExecutionDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ruleExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ruleExecutionDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ruleExecutionDo) Unscoped() *ruleExecutionDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ruleExecutionDo) Create(values ...*model.RuleExecution) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ruleExecutionDo) CreateInBatches(values []*model.RuleExecution, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ruleExecutionDo) Save(values ...*model.RuleExecution) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ruleExecutionDo) First() (*model.RuleExecution, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleExecution), nil
	}
}

func (r ruleExecutionDo) Take() (*model.RuleExecution, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleExecution), nil
	}
}

func (r ruleExecutionDo) Last() (*model.RuleExecution, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleExecution), nil
	}
}

func (r ruleExecutionDo) Find() ([]*model.RuleExecution, error) {
	result, err := r.DO.Find()
	return result.([]*model.RuleExecution), err
}

func (r ruleExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RuleExecution, err error) {
	buf := make([]*model.RuleExecution, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ruleExecutionDo) FindInBatches(result *[]*model.RuleExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ruleExecutionDo) Attrs(attrs ...field.AssignExpr) *ruleExecutionDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ruleExecutionDo) Assign(attrs ...field.AssignExpr) *ruleExecutionDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ruleExecutionDo) Joins(fields ...field.RelationField) *ruleExecutionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ruleExecutionDo) Preload(fields ...field.RelationField) *ruleExecutionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ruleExecutionDo) FirstOrInit() (*model.RuleExecution, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleExecution), nil
	}
}

func (r ruleExecutionDo) FirstOrCreate() (*model.RuleExecution, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleExecution), nil
	}
}

func (r ruleExecutionDo) FindByPage(offset int, limit int) (result []*model.RuleExecution, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ruleExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ruleExecutionDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ruleExecutionDo) Delete(models ...*model.RuleExecution) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ruleExecutionDo) withDO(do gen.Dao) *ruleExecutionDo {
	r.DO = *do.(*gen.DO)
	return r
}
