// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"0things/pkg/tsdb"
	"data-engine/internal/consumer"
	"data-engine/internal/handler"
	"data-engine/internal/repository"
	"data-engine/internal/server"
	"data-engine/internal/service"
	"data-engine/pkg/app"
	"data-engine/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	wireEventBusHolder, cleanup, err := provideEventBus(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	eventConsumer := provideEventConsumer(wireEventBusHolder)
	zapLogger := provideZapLogger(logger)
	client, cleanup2, err := provideTSDBClient(viperViper, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	shadowRepository := repository.NewShadowRepository(viperViper, zapLogger)
	telemetryService := service.NewTelemetryService(viperViper, zapLogger, client, shadowRepository)
	telemetryHandler := handler.NewTelemetryHandler(telemetryService, zapLogger)
	telemetryConsumer := consumer.NewTelemetryConsumer(telemetryHandler)
	db, err := provideDB(viperViper, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(zapLogger, db)
	deviceEventRepository := repository.NewDeviceEventRepository(repositoryRepository)
	eventService := service.NewEventService(zapLogger, deviceEventRepository)
	eventHandler := handler.NewEventHandler(eventService, zapLogger)
	consumerEventConsumer := consumer.NewEventConsumer(eventHandler)
	deviceUpgradeStatusRepository := repository.NewDeviceUpgradeStatusRepository(repositoryRepository)
	otaService := service.NewOTAService(deviceUpgradeStatusRepository, zapLogger)
	otaHandler := handler.NewOTAHandler(otaService, zapLogger)
	otaProgressConsumer := consumer.NewOTAProgressConsumer(otaHandler)
	otaDeviceInfoConsumer := consumer.NewOTADeviceInfoConsumer(otaHandler)
	manager := consumer.NewManager(eventConsumer, telemetryConsumer, consumerEventConsumer, otaProgressConsumer, otaDeviceInfoConsumer, zapLogger)
	dataEngineServer := server.NewDataEngineServer(manager, logger)
	appApp := newApp(dataEngineServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideZapLogger(logger *log.Logger) *zap.Logger {
	return logger.Logger
}

func provideTSDBClient(conf *viper.Viper, logger *log.Logger) (tsdb.Client, func(), error) {
	client := tsdb.NewClient(conf, logger.Logger)
	cleanup := func() {
		client.Close()
	}
	return client, cleanup, nil
}

func provideDB(conf *viper.Viper, logger *log.Logger) (*gorm.DB, error) {
	return repository.NewDB(conf, logger.Logger)
}

type eventBusHolder struct {
	producer event.Producer
	consumer event.Consumer
}

func provideEventBus(conf *viper.Viper, logger *log.Logger) (*eventBusHolder, func(), error) {
	pub, sub, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	p := event.NewProducer(pub)
	c := event.NewConsumer(sub, logger.Logger)
	cleanup := func() {
		_ = p.Close()
		_ = c.Close()
	}
	return &eventBusHolder{producer: p, consumer: c}, cleanup, nil
}

func provideEventConsumer(holder *eventBusHolder) event.Consumer {
	return holder.consumer
}

func provideEventProducer(holder *eventBusHolder) event.Producer {
	return holder.producer
}

var repositorySet = wire.NewSet(
	provideDB, repository.NewRepository, repository.NewDeviceUpgradeStatusRepository, repository.NewDeviceEventRepository, repository.NewShadowRepository,
)

var serviceSet = wire.NewSet(service.NewTelemetryService, service.NewOTAService, service.NewEventService)

var consumerSet = wire.NewSet(consumer.NewTelemetryConsumer, consumer.NewEventConsumer, consumer.NewOTAProgressConsumer, consumer.NewOTADeviceInfoConsumer, consumer.NewManager)

var handlerSet = wire.NewSet(handler.NewTelemetryHandler, handler.NewEventHandler, handler.NewOTAHandler)

var serverSet = wire.NewSet(server.NewDataEngineServer)

func newApp(server2 *server.DataEngineServer,
) *app.App {
	return app.NewApp(app.WithServer(server2), app.WithName("0things-data-engine"))
}
