env: local

coap:
  addr: ":5683"

event:
  driver: "nats"
  nats:
    url: "nats://127.0.0.1:4222"

log:
  log_level: debug
  mode: console
  encoding: console
  log_file_name: "./storage/logs/transport-coap.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
