// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/organization_user.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "aiot-backend/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockOrganizationUserRepository is a mock of OrganizationUserRepository interface.
type MockOrganizationUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationUserRepositoryMockRecorder
}

// MockOrganizationUserRepositoryMockRecorder is the mock recorder for MockOrganizationUserRepository.
type MockOrganizationUserRepositoryMockRecorder struct {
	mock *MockOrganizationUserRepository
}

// NewMockOrganizationUserRepository creates a new mock instance.
func NewMockOrganizationUserRepository(ctrl *gomock.Controller) *MockOrganizationUserRepository {
	mock := &MockOrganizationUserRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationUserRepository) EXPECT() *MockOrganizationUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationUserRepository) Create(ctx context.Context, orgUser *model.OrganizationUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationUserRepositoryMockRecorder) Create(ctx, orgUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationUserRepository)(nil).Create), ctx, orgUser)
}

// GetByUserAndOrg mocks base method.
func (m *MockOrganizationUserRepository) GetByUserAndOrg(ctx context.Context, userID string, orgID int64) (*model.OrganizationUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndOrg", ctx, userID, orgID)
	ret0, _ := ret[0].(*model.OrganizationUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndOrg indicates an expected call of GetByUserAndOrg.
func (mr *MockOrganizationUserRepositoryMockRecorder) GetByUserAndOrg(ctx, userID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndOrg", reflect.TypeOf((*MockOrganizationUserRepository)(nil).GetByUserAndOrg), ctx, userID, orgID)
}

// IsMember mocks base method.
func (m *MockOrganizationUserRepository) IsMember(ctx context.Context, userID string, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, userID, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockOrganizationUserRepositoryMockRecorder) IsMember(ctx, userID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockOrganizationUserRepository)(nil).IsMember), ctx, userID, orgID)
}

// ListByUser mocks base method.
func (m *MockOrganizationUserRepository) ListByUser(ctx context.Context, userID string) ([]*model.OrganizationUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*model.OrganizationUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOrganizationUserRepositoryMockRecorder) ListByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOrganizationUserRepository)(nil).ListByUser), ctx, userID)
}

// ListOrgIDsByUser mocks base method.
func (m *MockOrganizationUserRepository) ListOrgIDsByUser(ctx context.Context, userID string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgIDsByUser", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgIDsByUser indicates an expected call of ListOrgIDsByUser.
func (mr *MockOrganizationUserRepositoryMockRecorder) ListOrgIDsByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgIDsByUser", reflect.TypeOf((*MockOrganizationUserRepository)(nil).ListOrgIDsByUser), ctx, userID)
}

// UpdateLastLogin mocks base method.
func (m *MockOrganizationUserRepository) UpdateLastLogin(ctx context.Context, userID string, orgID int64, loginTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, userID, orgID, loginTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockOrganizationUserRepositoryMockRecorder) UpdateLastLogin(ctx, userID, orgID, loginTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockOrganizationUserRepository)(nil).UpdateLastLogin), ctx, userID, orgID, loginTime)
}
