{{- if .Values.registry.create }}
{{- $registryUsername := required "registry.username is required when registry.create is true" .Values.registry.username -}}
{{- $registryPassword := required "registry.password is required when registry.create is true" .Values.registry.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: aiot-platform-registry-auth
  labels:
    {{- include "0things.labels" "registry" | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":%s,\"password\":%s,\"email\":%s,\"auth\":%s}}}" .Values.registry.server ($registryUsername | toJson) ($registryPassword | toJson) (.Values.registry.email | toJson) (printf "%s:%s" $registryUsername $registryPassword | b64enc | toJson) | b64enc | quote }}
{{- end }}
