// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"telemetry-service/internal/biz"
	"telemetry-service/internal/conf"
	"telemetry-service/internal/data"
	"telemetry-service/internal/data/kafka"
	"telemetry-service/internal/server"
	"telemetry-service/internal/service"
	"telemetry-service/internal/service/consumer"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	producer, cleanup2, err := kafka.NewProducer(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	telemetryService := service.NewTelemetryService(producer, logger)
	eventService := service.NewEventService(producer, logger)
	clientConnectStateService := service.NewClientConnectStateService(producer, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, telemetryService, eventService, clientConnectStateService, logger)
	telemetryEventRepo := data.NewTelemetryEventRepo(dataData, logger)
	telemetryUsecase := biz.NewTelemetryUsecase(telemetryEventRepo, logger)
	telemetryConsumer, cleanup3, err := consumer.NewTelemetryConsumer(telemetryUsecase, confData, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventRepo := data.NewEventRepo(dataData, logger)
	eventUsecase := biz.NewEventUsecase(eventRepo, logger)
	eventConsumer, cleanup4, err := consumer.NewEventConsumer(eventUsecase, confData, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientConnectStateRepo := data.NewClientConnectStateRepo(dataData, logger)
	clientConnectStateUsecase := biz.NewClientConnectStateUsecase(clientConnectStateRepo, logger)
	clientConnectStateConsumer, cleanup5, err := consumer.NewClientConnectStateConsumer(clientConnectStateUsecase, confData, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, telemetryConsumer, eventConsumer, clientConnectStateConsumer)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
