// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"aiot-backend/internal/handler"
	"aiot-backend/internal/job"
	"aiot-backend/internal/repository"
	"aiot-backend/internal/router"
	"aiot-backend/internal/server"
	"aiot-backend/internal/service"
	"aiot-backend/pkg/app"
	"aiot-backend/pkg/jwt"
	"aiot-backend/pkg/log"
	"aiot-backend/pkg/server/http"
	"aiot-backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	ioTDB := repository.NewIoTDB(viperViper, logger)
	productRepository := repository.NewProductRepository(ioTDB)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(handlerHandler, productService)
	productTSLRepository := repository.NewProductTSLRepository(ioTDB)
	productTSLService := service.NewProductTSLService(productRepository, productTSLRepository)
	productTSLHandler := handler.NewProductTSLHandler(handlerHandler, productTSLService)
	productMessageParserRepository := repository.NewProductMessageParserRepository(ioTDB)
	productMessageParserService := service.NewProductMessageParserService(productRepository, productMessageParserRepository)
	productMessageParserHandler := handler.NewProductMessageParserHandler(handlerHandler, productMessageParserService)
	ioTRedis := repository.NewIoTRedis(viperViper)
	deviceRepository := repository.NewDeviceRepository(ioTDB, ioTRedis)
	deviceTagRepository := repository.NewDeviceTagRepository(ioTDB)
	deviceShadowRepository := repository.NewDeviceShadowRepository(ioTDB)
	pushRecordRepository := repository.NewPushRecordRepository(ioTDB)
	deviceService := service.NewDeviceService(deviceRepository, productRepository, deviceTagRepository, deviceShadowRepository, pushRecordRepository)
	deviceHandler := handler.NewDeviceHandler(handlerHandler, deviceService, viperViper)
	sceneLinkageRepository := repository.NewSceneLinkageRepository(ioTDB)
	sceneLinkageService := service.NewSceneLinkageService(sceneLinkageRepository)
	sceneLinkageHandler := handler.NewSceneLinkageHandler(handlerHandler, sceneLinkageService)
	sceneLinkageDetailRepository := repository.NewSceneLinkageDetailRepository(ioTDB)
	sceneLinkageDetailService := service.NewSceneLinkageDetailService(sceneLinkageDetailRepository)
	sceneLinkageDetailHandler := handler.NewSceneLinkageDetailHandler(handlerHandler, sceneLinkageDetailService)
	otaRepository := repository.NewOTARepository(ioTDB)
	otaService := service.NewOTAService(otaRepository, productRepository, deviceRepository)
	otaHandler := handler.NewOTAHandler(handlerHandler, otaService)
	fileService := service.NewFileService(viperViper)
	fileHandler := handler.NewFileHandler(handlerHandler, fileService)
	deviceEventRepository := repository.NewDeviceEventRepository(ioTDB)
	deviceEventService := service.NewDeviceEventService(deviceEventRepository, deviceRepository)
	deviceEventHandler := handler.NewDeviceEventHandler(handlerHandler, deviceEventService)
	routerDeps := router.RouterDeps{
		Logger:                      logger,
		Config:                      viperViper,
		JWT:                         jwtJWT,
		UserHandler:                 userHandler,
		ProductHandler:              productHandler,
		ProductTSLHandler:           productTSLHandler,
		ProductMessageParserHandler: productMessageParserHandler,
		DeviceHandler:               deviceHandler,
		SceneLinkageHandler:         sceneLinkageHandler,
		SceneLinkageDetailHandler:   sceneLinkageDetailHandler,
		OTAHandler:                  otaHandler,
		FileHandler:                 fileHandler,
		DeviceEventHandler:          deviceEventHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	deviceEventConsumer, err := job.NewDeviceEventConsumer(viperViper, deviceEventService, logger)
	if err != nil {
		return nil, nil, err
	}
	jobServer := server.NewJobServer(logger, userJob, deviceEventConsumer)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewIoTDB, repository.NewIoTRedis, repository.NewProductRepository, repository.NewProductTSLRepository, repository.NewProductMessageParserRepository, repository.NewDeviceRepository, repository.NewDeviceTagRepository, repository.NewDeviceShadowRepository, repository.NewPushRecordRepository, repository.NewSceneLinkageRepository, repository.NewSceneLinkageDetailRepository, repository.NewOTARepository, repository.NewDeviceEventRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewProductService, service.NewProductTSLService, service.NewProductMessageParserService, service.NewDeviceService, service.NewSceneLinkageService, service.NewSceneLinkageDetailService, service.NewOTAService, service.NewFileService, service.NewDeviceEventService, wire.Bind(new(service.ProductServiceInterface), new(*service.ProductService)), wire.Bind(new(service.ProductTSLServiceInterface), new(*service.ProductTSLService)), wire.Bind(new(service.ProductMessageParserServiceInterface), new(*service.ProductMessageParserService)), wire.Bind(new(service.DeviceServiceInterface), new(*service.DeviceService)), wire.Bind(new(service.SceneLinkageServiceInterface), new(*service.SceneLinkageService)), wire.Bind(new(service.SceneLinkageDetailServiceInterface), new(*service.SceneLinkageDetailService)), wire.Bind(new(service.OTAServiceInterface), new(*service.OTAService)), wire.Bind(new(service.FileServiceInterface), new(*service.FileService)), wire.Bind(new(service.DeviceEventServiceInterface), new(*service.DeviceEventService)))

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewProductHandler, handler.NewProductTSLHandler, handler.NewProductMessageParserHandler, handler.NewDeviceHandler, handler.NewSceneLinkageHandler, handler.NewSceneLinkageDetailHandler, handler.NewOTAHandler, handler.NewFileHandler, handler.NewDeviceEventHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob, job.NewDeviceEventConsumer)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
