// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"aiot-backend/internal/handler"
	"aiot-backend/internal/repository"
	"aiot-backend/internal/router"
	"aiot-backend/internal/server"
	"aiot-backend/internal/service"
	"aiot-backend/pkg/app"
	"aiot-backend/pkg/jwt"
	"aiot-backend/pkg/log"
	"aiot-backend/pkg/server/http"
	"aiot-backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	organizationRepository := repository.NewOrganizationRepository(repositoryRepository)
	organizationUserRepository := repository.NewOrganizationUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, organizationRepository, organizationUserRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(handlerHandler, productService)
	categoryRepository := repository.NewCategoryRepository(db)
	categoryService := service.NewCategoryService(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(handlerHandler, categoryService)
	productTSLRepository := repository.NewProductTSLRepository(db)
	productTSLService := service.NewProductTSLService(productRepository, productTSLRepository)
	productTSLHandler := handler.NewProductTSLHandler(handlerHandler, productTSLService)
	productMessageParserRepository := repository.NewProductMessageParserRepository(db)
	productMessageParserService := service.NewProductMessageParserService(productRepository, productMessageParserRepository)
	productMessageParserHandler := handler.NewProductMessageParserHandler(handlerHandler, productMessageParserService)
	client := repository.NewRedis(viperViper, logger)
	deviceRepository := repository.NewDeviceRepository(db, client)
	deviceTagRepository := repository.NewDeviceTagRepository(db)
	deviceShadowRepository := repository.NewDeviceShadowRepository(db)
	pushRecordRepository := repository.NewPushRecordRepository(db)
	deviceService := service.NewDeviceService(deviceRepository, productRepository, deviceTagRepository, deviceShadowRepository, pushRecordRepository)
	deviceHandler := handler.NewDeviceHandler(handlerHandler, deviceService, viperViper)
	sceneLinkageRepository := repository.NewSceneLinkageRepository(db)
	sceneLinkageService := service.NewSceneLinkageService(sceneLinkageRepository)
	sceneLinkageHandler := handler.NewSceneLinkageHandler(handlerHandler, sceneLinkageService)
	sceneLinkageDetailRepository := repository.NewSceneLinkageDetailRepository(db)
	sceneLinkageDetailService := service.NewSceneLinkageDetailService(sceneLinkageDetailRepository)
	sceneLinkageDetailHandler := handler.NewSceneLinkageDetailHandler(handlerHandler, sceneLinkageDetailService)
	otaRepository := repository.NewOTARepository(db)
	kafkaService, cleanup, err := service.NewKafkaService(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	protocolRepository := repository.NewProtocolRepository(db)
	otaService := provideOTAService(otaRepository, productRepository, deviceRepository, kafkaService, protocolRepository)
	otaHandler := handler.NewOTAHandler(handlerHandler, otaService)
	fileService := service.NewFileService(viperViper)
	fileHandler := handler.NewFileHandler(handlerHandler, fileService)
	deviceEventRepository := repository.NewDeviceEventRepository(db)
	deviceEventService := service.NewDeviceEventService(deviceEventRepository, deviceRepository)
	deviceEventHandler := handler.NewDeviceEventHandler(handlerHandler, deviceEventService)
	deviceServiceInvocationRepository := repository.NewDeviceServiceInvocationRepository(db)
	deviceServiceInvocationService := service.NewDeviceServiceInvocationService(deviceServiceInvocationRepository, deviceRepository)
	deviceServiceInvocationHandler := handler.NewDeviceServiceInvocationHandler(handlerHandler, deviceServiceInvocationService)
	protocolService := provideProtocolService(protocolRepository, viperViper)
	protocolHandler := handler.NewProtocolHandler(handlerHandler, protocolService)
	deviceGroupRepository := repository.NewDeviceGroupRepository(db)
	deviceGroupService := service.NewDeviceGroupService(deviceGroupRepository, deviceRepository)
	deviceGroupHandler := handler.NewDeviceGroupHandler(handlerHandler, deviceGroupService)
	telemetryRepository := repository.NewTelemetryRepository(viperViper, logger)
	telemetryService := service.NewTelemetryService(telemetryRepository, logger)
	telemetryHandler := handler.NewTelemetryHandler(telemetryService, logger)
	routerDeps := router.RouterDeps{
		Logger:                         logger,
		Config:                         viperViper,
		JWT:                            jwtJWT,
		UserHandler:                    userHandler,
		ProductHandler:                 productHandler,
		CategoryHandler:                categoryHandler,
		ProductTSLHandler:              productTSLHandler,
		ProductMessageParserHandler:    productMessageParserHandler,
		DeviceHandler:                  deviceHandler,
		SceneLinkageHandler:            sceneLinkageHandler,
		SceneLinkageDetailHandler:      sceneLinkageDetailHandler,
		OTAHandler:                     otaHandler,
		FileHandler:                    fileHandler,
		DeviceEventHandler:             deviceEventHandler,
		DeviceServiceInvocationHandler: deviceServiceInvocationHandler,
		ProtocolHandler:                protocolHandler,
		DeviceGroupHandler:             deviceGroupHandler,
		TelemetryHandler:               telemetryHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobServer := server.NewJobServer(logger)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewRedis, repository.NewProductRepository, repository.NewCategoryRepository, repository.NewProductTSLRepository, repository.NewProductMessageParserRepository, repository.NewDeviceRepository, repository.NewDeviceGroupRepository, repository.NewDeviceTagRepository, repository.NewDeviceShadowRepository, repository.NewPushRecordRepository, repository.NewSceneLinkageRepository, repository.NewSceneLinkageDetailRepository, repository.NewOTARepository, repository.NewDeviceEventRepository, repository.NewDeviceServiceInvocationRepository, repository.NewProtocolRepository, repository.NewTelemetryRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewOrganizationRepository, repository.NewOrganizationUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewProductService, service.NewCategoryService, service.NewProductTSLService, service.NewProductMessageParserService, service.NewDeviceService, service.NewDeviceGroupService, service.NewKafkaService, service.NewMQTTService, service.NewSceneLinkageService, service.NewSceneLinkageDetailService, service.NewTelemetryService, provideOTAService, service.NewFileService, service.NewDeviceEventService, service.NewDeviceServiceInvocationService, provideProtocolService, wire.Bind(new(service.ProductServiceInterface), new(*service.ProductService)), wire.Bind(new(service.CategoryServiceInterface), new(*service.CategoryService)), wire.Bind(new(service.ProductTSLServiceInterface), new(*service.ProductTSLService)), wire.Bind(new(service.ProductMessageParserServiceInterface), new(*service.ProductMessageParserService)), wire.Bind(new(service.DeviceServiceInterface), new(*service.DeviceService)), wire.Bind(new(service.DeviceGroupServiceInterface), new(*service.DeviceGroupService)), wire.Bind(new(service.KafkaServiceInterface), new(*service.KafkaService)), wire.Bind(new(service.MQTTServiceInterface), new(*service.MQTTService)), wire.Bind(new(service.SceneLinkageServiceInterface), new(*service.SceneLinkageService)), wire.Bind(new(service.SceneLinkageDetailServiceInterface), new(*service.SceneLinkageDetailService)), wire.Bind(new(service.TelemetryServiceInterface), new(*service.TelemetryService)), wire.Bind(new(service.OTAServiceInterface), new(*service.OTAService)), wire.Bind(new(service.FileServiceInterface), new(*service.FileService)), wire.Bind(new(service.DeviceEventServiceInterface), new(*service.DeviceEventService)), wire.Bind(new(service.DeviceServiceInvocationServiceInterface), new(*service.DeviceServiceInvocationService)), wire.Bind(new(service.ProtocolServiceInterface), new(*service.ProtocolService)))

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewProductHandler, handler.NewCategoryHandler, handler.NewProductTSLHandler, handler.NewProductMessageParserHandler, handler.NewDeviceHandler, handler.NewDeviceGroupHandler, handler.NewSceneLinkageHandler, handler.NewSceneLinkageDetailHandler, handler.NewOTAHandler, handler.NewFileHandler, handler.NewDeviceEventHandler, handler.NewDeviceServiceInvocationHandler, handler.NewProtocolHandler, handler.NewTelemetryHandler)

func provideOTAService(repo *repository.OTARepository, productRepo *repository.ProductRepository, deviceRepo *repository.DeviceRepository, kafka service.KafkaServiceInterface, protocols *repository.ProtocolRepository) *service.OTAService {
	return service.NewOTAServiceWithProtocol(repo, productRepo, deviceRepo, kafka, protocols)
}

func provideProtocolService(repo *repository.ProtocolRepository, config *viper.Viper) *service.ProtocolService {
	return service.NewProtocolService(repo, config)
}

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("0things-backend"))
}
