// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"aiot-backend/internal/handler"
	"aiot-backend/internal/repository"
	"aiot-backend/internal/router"
	"aiot-backend/internal/server"
	"aiot-backend/internal/service"
	"aiot-backend/pkg/app"
	"aiot-backend/pkg/log"
	"aiot-backend/pkg/logto"
	"aiot-backend/pkg/server/http"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	verifier, err := provideLogtoVerifier(viperViper)
	if err != nil {
		return nil, nil, err
	}
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(handlerHandler, productService)
	categoryRepository := repository.NewCategoryRepository(db)
	categoryService := service.NewCategoryService(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(handlerHandler, categoryService)
	productTSLRepository := repository.NewProductTSLRepository(db)
	productTSLService := service.NewProductTSLService(productRepository, productTSLRepository)
	productTSLHandler := handler.NewProductTSLHandler(handlerHandler, productTSLService)
	productMessageParserRepository := repository.NewProductMessageParserRepository(db)
	productMessageParserService := service.NewProductMessageParserService(productRepository, productMessageParserRepository)
	productMessageParserHandler := handler.NewProductMessageParserHandler(handlerHandler, productMessageParserService)
	client := repository.NewRedis(viperViper, logger)
	deviceRepository := repository.NewDeviceRepository(db, client)
	deviceTagRepository := repository.NewDeviceTagRepository(db)
	deviceShadowRepository := repository.NewDeviceShadowRepository(db)
	pushRecordRepository := repository.NewPushRecordRepository(db)
	deviceService := service.NewDeviceService(deviceRepository, productRepository, deviceTagRepository, deviceShadowRepository, pushRecordRepository)
	deviceHandler := handler.NewDeviceHandler(handlerHandler, deviceService, viperViper)
	otaRepository := repository.NewOTARepository(db)
	producer, cleanup, err := provideEventProducer(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	otaService := service.NewOTAService(otaRepository, productRepository, deviceRepository, producer)
	otaHandler := handler.NewOTAHandler(handlerHandler, otaService)
	fileService := service.NewFileService(viperViper)
	fileHandler := handler.NewFileHandler(handlerHandler, fileService)
	deviceEventRepository := repository.NewDeviceEventRepository(db)
	deviceEventService := service.NewDeviceEventService(deviceEventRepository)
	deviceEventHandler := handler.NewDeviceEventHandler(handlerHandler, deviceEventService)
	deviceServiceInvocationRepository := repository.NewDeviceServiceInvocationRepository(db)
	telemetryRepository := repository.NewTelemetryRepository(viperViper, logger)
	thingModelDataService := service.NewThingModelDataService(deviceServiceInvocationRepository, deviceRepository, productTSLRepository, telemetryRepository)
	thingModelDataHandler := handler.NewThingModelDataHandler(handlerHandler, thingModelDataService)
	protocolRepository := repository.NewProtocolRepository(db)
	protocolService := provideProtocolService(protocolRepository, viperViper)
	protocolHandler := handler.NewProtocolHandler(handlerHandler, protocolService)
	deviceGroupRepository := repository.NewDeviceGroupRepository(db)
	deviceGroupService := service.NewDeviceGroupService(deviceGroupRepository, deviceRepository)
	deviceGroupHandler := handler.NewDeviceGroupHandler(handlerHandler, deviceGroupService)
	telemetryService := service.NewTelemetryService(telemetryRepository, logger)
	telemetryHandler := handler.NewTelemetryHandler(telemetryService, logger)
	ruleNodeDefinitionRepository := repository.NewRuleNodeDefinitionRepository(db)
	ruleNodeDefinitionService := service.NewRuleNodeDefinitionService(ruleNodeDefinitionRepository)
	ruleNodeDefinitionHandler := handler.NewRuleNodeDefinitionHandler(handlerHandler, ruleNodeDefinitionService)
	ruleChainRepository := repository.NewRuleChainRepository(db)
	ruleChainService := service.NewRuleChainService(ruleChainRepository)
	ruleChainHandler := handler.NewRuleChainHandler(handlerHandler, ruleChainService)
	managementClient, err := provideLogtoManagementClient(viperViper)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	organizationProvisioningService := service.NewOrganizationProvisioningService(managementClient)
	organizationHandler := handler.NewOrganizationHandler(handlerHandler, organizationProvisioningService)
	routerDeps := router.RouterDeps{
		Logger:                      logger,
		Config:                      viperViper,
		Logto:                       verifier,
		ProductHandler:              productHandler,
		CategoryHandler:             categoryHandler,
		ProductTSLHandler:           productTSLHandler,
		ProductMessageParserHandler: productMessageParserHandler,
		DeviceHandler:               deviceHandler,
		OTAHandler:                  otaHandler,
		FileHandler:                 fileHandler,
		DeviceEventHandler:          deviceEventHandler,
		ThingModelDataHandler:       thingModelDataHandler,
		ProtocolHandler:             protocolHandler,
		DeviceGroupHandler:          deviceGroupHandler,
		TelemetryHandler:            telemetryHandler,
		RuleNodeDefinitionHandler:   ruleNodeDefinitionHandler,
		RuleChainHandler:            ruleChainHandler,
		OrganizationHandler:         organizationHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobServer := server.NewJobServer(logger)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewRedis, repository.NewProductRepository, repository.NewCategoryRepository, repository.NewProductTSLRepository, repository.NewProductMessageParserRepository, repository.NewDeviceRepository, repository.NewDeviceGroupRepository, repository.NewDeviceTagRepository, repository.NewDeviceShadowRepository, repository.NewPushRecordRepository, repository.NewOTARepository, repository.NewDeviceEventRepository, repository.NewDeviceServiceInvocationRepository, repository.NewProtocolRepository, repository.NewTelemetryRepository, repository.NewTransaction, repository.NewRuleNodeDefinitionRepository, repository.NewRuleChainRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewProductService, service.NewCategoryService, service.NewProductTSLService, service.NewProductMessageParserService, service.NewDeviceService, service.NewDeviceGroupService, service.NewMQTTService, service.NewTelemetryService, service.NewOTAService, service.NewFileService, service.NewDeviceEventService, service.NewThingModelDataService, provideProtocolService,
	provideEventProducer, service.NewRuleNodeDefinitionService, service.NewRuleChainService, service.NewOrganizationProvisioningService, wire.Bind(new(service.ProductServiceInterface), new(*service.ProductService)), wire.Bind(new(service.CategoryServiceInterface), new(*service.CategoryService)), wire.Bind(new(service.ProductTSLServiceInterface), new(*service.ProductTSLService)), wire.Bind(new(service.ProductMessageParserServiceInterface), new(*service.ProductMessageParserService)), wire.Bind(new(service.DeviceServiceInterface), new(*service.DeviceService)), wire.Bind(new(service.DeviceGroupServiceInterface), new(*service.DeviceGroupService)), wire.Bind(new(service.MQTTServiceInterface), new(*service.MQTTService)), wire.Bind(new(service.TelemetryServiceInterface), new(*service.TelemetryService)), wire.Bind(new(service.OTAServiceInterface), new(*service.OTAService)), wire.Bind(new(service.FileServiceInterface), new(*service.FileService)), wire.Bind(new(service.DeviceEventServiceInterface), new(*service.DeviceEventService)), wire.Bind(new(service.ThingModelDataServiceInterface), new(*service.ThingModelDataService)), wire.Bind(new(service.ProtocolServiceInterface), new(*service.ProtocolService)), wire.Bind(new(service.RuleNodeDefinitionServiceInterface), new(*service.RuleNodeDefinitionService)), wire.Bind(new(service.RuleChainServiceInterface), new(*service.RuleChainService)), wire.Bind(new(service.OrganizationProvisioningServiceInterface), new(*service.OrganizationProvisioningService)),
)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewProductHandler, handler.NewCategoryHandler, handler.NewProductTSLHandler, handler.NewProductMessageParserHandler, handler.NewDeviceHandler, handler.NewDeviceGroupHandler, handler.NewOTAHandler, handler.NewFileHandler, handler.NewDeviceEventHandler, handler.NewThingModelDataHandler, handler.NewProtocolHandler, handler.NewTelemetryHandler, handler.NewRuleNodeDefinitionHandler, handler.NewRuleChainHandler, handler.NewOrganizationHandler)

func provideProtocolService(repo *repository.ProtocolRepository, config *viper.Viper) *service.ProtocolService {
	return service.NewProtocolService(repo, config)
}

func provideLogtoVerifier(config *viper.Viper) (*logto.Verifier, error) {
	return logto.NewVerifier(config)
}

func provideLogtoManagementClient(config *viper.Viper) (*logto.ManagementClient, error) {
	return logto.NewManagementClient(config)
}

func provideEventProducer(conf *viper.Viper, logger *log.Logger) (event.Producer, func(), error) {
	pub, _, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	producer := event.NewProducer(pub)
	cleanup := func() {
		_ = producer.Close()
	}
	return producer, cleanup, nil
}

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("0things-backend"))
}
