// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		Device:              newDevice(db, opts...),
		DeviceUpgradeStatus: newDeviceUpgradeStatus(db, opts...),
		UpgradeBatch:        newUpgradeBatch(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Device              device
	DeviceUpgradeStatus deviceUpgradeStatus
	UpgradeBatch        upgradeBatch
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Device:              q.Device.clone(db),
		DeviceUpgradeStatus: q.DeviceUpgradeStatus.clone(db),
		UpgradeBatch:        q.UpgradeBatch.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Device:              q.Device.replaceDB(db),
		DeviceUpgradeStatus: q.DeviceUpgradeStatus.replaceDB(db),
		UpgradeBatch:        q.UpgradeBatch.replaceDB(db),
	}
}

type queryCtx struct {
	Device              *deviceDo
	DeviceUpgradeStatus *deviceUpgradeStatusDo
	UpgradeBatch        *upgradeBatchDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Device:              q.Device.WithContext(ctx),
		DeviceUpgradeStatus: q.DeviceUpgradeStatus.WithContext(ctx),
		UpgradeBatch:        q.UpgradeBatch.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
