// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"data-engine/internal/model"
)

func newOTADeviceUpgradeStatus(db *gorm.DB, opts ...gen.DOOption) oTADeviceUpgradeStatus {
	_oTADeviceUpgradeStatus := oTADeviceUpgradeStatus{}

	_oTADeviceUpgradeStatus.oTADeviceUpgradeStatusDo.UseDB(db, opts...)
	_oTADeviceUpgradeStatus.oTADeviceUpgradeStatusDo.UseModel(&model.OTADeviceUpgradeStatus{})

	tableName := _oTADeviceUpgradeStatus.oTADeviceUpgradeStatusDo.TableName()
	_oTADeviceUpgradeStatus.ALL = field.NewAsterisk(tableName)
	_oTADeviceUpgradeStatus.ID = field.NewInt64(tableName, "id")
	_oTADeviceUpgradeStatus.DeviceID = field.NewInt64(tableName, "device_id")
	_oTADeviceUpgradeStatus.OTAPackageID = field.NewString(tableName, "ota_package_id")
	_oTADeviceUpgradeStatus.UpgradeBatchID = field.NewString(tableName, "upgrade_batch_id")
	_oTADeviceUpgradeStatus.Status = field.NewString(tableName, "status")
	_oTADeviceUpgradeStatus.Module = field.NewString(tableName, "module")
	_oTADeviceUpgradeStatus.TargetVersion = field.NewString(tableName, "target_version")
	_oTADeviceUpgradeStatus.Progress = field.NewInt32(tableName, "progress")
	_oTADeviceUpgradeStatus.DispatchAttempts = field.NewInt32(tableName, "dispatch_attempts")
	_oTADeviceUpgradeStatus.LastDispatchError = field.NewString(tableName, "last_dispatch_error")
	_oTADeviceUpgradeStatus.FirstProgressAt = field.NewInt64(tableName, "first_progress_at")
	_oTADeviceUpgradeStatus.LastReportAt = field.NewInt64(tableName, "last_report_at")
	_oTADeviceUpgradeStatus.TimeoutSeconds = field.NewInt32(tableName, "timeout_seconds")
	_oTADeviceUpgradeStatus.MaxRetries = field.NewInt32(tableName, "max_retries")
	_oTADeviceUpgradeStatus.CurrentVersion = field.NewString(tableName, "current_version")
	_oTADeviceUpgradeStatus.LastStatusChangeTime = field.NewInt64(tableName, "last_status_change_ts")
	_oTADeviceUpgradeStatus.CreatedAt = field.NewTime(tableName, "created_at")
	_oTADeviceUpgradeStatus.UpdatedAt = field.NewTime(tableName, "updated_at")

	_oTADeviceUpgradeStatus.fillFieldMap()

	return _oTADeviceUpgradeStatus
}

type oTADeviceUpgradeStatus struct {
	oTADeviceUpgradeStatusDo oTADeviceUpgradeStatusDo

	ALL                  field.Asterisk
	ID                   field.Int64
	DeviceID             field.Int64
	OTAPackageID         field.String
	UpgradeBatchID       field.String
	Status               field.String
	Module               field.String
	TargetVersion        field.String
	Progress             field.Int32
	DispatchAttempts     field.Int32
	LastDispatchError    field.String
	FirstProgressAt      field.Int64
	LastReportAt         field.Int64
	TimeoutSeconds       field.Int32
	MaxRetries           field.Int32
	CurrentVersion       field.String
	LastStatusChangeTime field.Int64
	CreatedAt            field.Time
	UpdatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (o oTADeviceUpgradeStatus) Table(newTableName string) *oTADeviceUpgradeStatus {
	o.oTADeviceUpgradeStatusDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oTADeviceUpgradeStatus) As(alias string) *oTADeviceUpgradeStatus {
	o.oTADeviceUpgradeStatusDo.DO = *(o.oTADeviceUpgradeStatusDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oTADeviceUpgradeStatus) updateTableName(table string) *oTADeviceUpgradeStatus {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.DeviceID = field.NewInt64(table, "device_id")
	o.OTAPackageID = field.NewString(table, "ota_package_id")
	o.UpgradeBatchID = field.NewString(table, "upgrade_batch_id")
	o.Status = field.NewString(table, "status")
	o.Module = field.NewString(table, "module")
	o.TargetVersion = field.NewString(table, "target_version")
	o.Progress = field.NewInt32(table, "progress")
	o.DispatchAttempts = field.NewInt32(table, "dispatch_attempts")
	o.LastDispatchError = field.NewString(table, "last_dispatch_error")
	o.FirstProgressAt = field.NewInt64(table, "first_progress_at")
	o.LastReportAt = field.NewInt64(table, "last_report_at")
	o.TimeoutSeconds = field.NewInt32(table, "timeout_seconds")
	o.MaxRetries = field.NewInt32(table, "max_retries")
	o.CurrentVersion = field.NewString(table, "current_version")
	o.LastStatusChangeTime = field.NewInt64(table, "last_status_change_ts")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *oTADeviceUpgradeStatus) WithContext(ctx context.Context) *oTADeviceUpgradeStatusDo {
	return o.oTADeviceUpgradeStatusDo.WithContext(ctx)
}

func (o oTADeviceUpgradeStatus) TableName() string { return o.oTADeviceUpgradeStatusDo.TableName() }

func (o oTADeviceUpgradeStatus) Alias() string { return o.oTADeviceUpgradeStatusDo.Alias() }

func (o oTADeviceUpgradeStatus) Columns(cols ...field.Expr) gen.Columns {
	return o.oTADeviceUpgradeStatusDo.Columns(cols...)
}

func (o *oTADeviceUpgradeStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oTADeviceUpgradeStatus) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 18)
	o.fieldMap["id"] = o.ID
	o.fieldMap["device_id"] = o.DeviceID
	o.fieldMap["ota_package_id"] = o.OTAPackageID
	o.fieldMap["upgrade_batch_id"] = o.UpgradeBatchID
	o.fieldMap["status"] = o.Status
	o.fieldMap["module"] = o.Module
	o.fieldMap["target_version"] = o.TargetVersion
	o.fieldMap["progress"] = o.Progress
	o.fieldMap["dispatch_attempts"] = o.DispatchAttempts
	o.fieldMap["last_dispatch_error"] = o.LastDispatchError
	o.fieldMap["first_progress_at"] = o.FirstProgressAt
	o.fieldMap["last_report_at"] = o.LastReportAt
	o.fieldMap["timeout_seconds"] = o.TimeoutSeconds
	o.fieldMap["max_retries"] = o.MaxRetries
	o.fieldMap["current_version"] = o.CurrentVersion
	o.fieldMap["last_status_change_ts"] = o.LastStatusChangeTime
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o oTADeviceUpgradeStatus) clone(db *gorm.DB) oTADeviceUpgradeStatus {
	o.oTADeviceUpgradeStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oTADeviceUpgradeStatus) replaceDB(db *gorm.DB) oTADeviceUpgradeStatus {
	o.oTADeviceUpgradeStatusDo.ReplaceDB(db)
	return o
}

type oTADeviceUpgradeStatusDo struct{ gen.DO }

func (o oTADeviceUpgradeStatusDo) Debug() *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Debug())
}

func (o oTADeviceUpgradeStatusDo) WithContext(ctx context.Context) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oTADeviceUpgradeStatusDo) ReadDB() *oTADeviceUpgradeStatusDo {
	return o.Clauses(dbresolver.Read)
}

func (o oTADeviceUpgradeStatusDo) WriteDB() *oTADeviceUpgradeStatusDo {
	return o.Clauses(dbresolver.Write)
}

func (o oTADeviceUpgradeStatusDo) Session(config *gorm.Session) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Session(config))
}

func (o oTADeviceUpgradeStatusDo) Clauses(conds ...clause.Expression) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oTADeviceUpgradeStatusDo) Returning(value interface{}, columns ...string) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oTADeviceUpgradeStatusDo) Not(conds ...gen.Condition) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oTADeviceUpgradeStatusDo) Or(conds ...gen.Condition) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oTADeviceUpgradeStatusDo) Select(conds ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oTADeviceUpgradeStatusDo) Where(conds ...gen.Condition) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oTADeviceUpgradeStatusDo) Order(conds ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oTADeviceUpgradeStatusDo) Distinct(cols ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oTADeviceUpgradeStatusDo) Omit(cols ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oTADeviceUpgradeStatusDo) Join(table schema.Tabler, on ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oTADeviceUpgradeStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oTADeviceUpgradeStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oTADeviceUpgradeStatusDo) Group(cols ...field.Expr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oTADeviceUpgradeStatusDo) Having(conds ...gen.Condition) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oTADeviceUpgradeStatusDo) Limit(limit int) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oTADeviceUpgradeStatusDo) Offset(offset int) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oTADeviceUpgradeStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oTADeviceUpgradeStatusDo) Unscoped() *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oTADeviceUpgradeStatusDo) Create(values ...*model.OTADeviceUpgradeStatus) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oTADeviceUpgradeStatusDo) CreateInBatches(values []*model.OTADeviceUpgradeStatus, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oTADeviceUpgradeStatusDo) Save(values ...*model.OTADeviceUpgradeStatus) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oTADeviceUpgradeStatusDo) First() (*model.OTADeviceUpgradeStatus, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTADeviceUpgradeStatus), nil
	}
}

func (o oTADeviceUpgradeStatusDo) Take() (*model.OTADeviceUpgradeStatus, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTADeviceUpgradeStatus), nil
	}
}

func (o oTADeviceUpgradeStatusDo) Last() (*model.OTADeviceUpgradeStatus, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTADeviceUpgradeStatus), nil
	}
}

func (o oTADeviceUpgradeStatusDo) Find() ([]*model.OTADeviceUpgradeStatus, error) {
	result, err := o.DO.Find()
	return result.([]*model.OTADeviceUpgradeStatus), err
}

func (o oTADeviceUpgradeStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OTADeviceUpgradeStatus, err error) {
	buf := make([]*model.OTADeviceUpgradeStatus, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oTADeviceUpgradeStatusDo) FindInBatches(result *[]*model.OTADeviceUpgradeStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oTADeviceUpgradeStatusDo) Attrs(attrs ...field.AssignExpr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oTADeviceUpgradeStatusDo) Assign(attrs ...field.AssignExpr) *oTADeviceUpgradeStatusDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oTADeviceUpgradeStatusDo) Joins(fields ...field.RelationField) *oTADeviceUpgradeStatusDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oTADeviceUpgradeStatusDo) Preload(fields ...field.RelationField) *oTADeviceUpgradeStatusDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oTADeviceUpgradeStatusDo) FirstOrInit() (*model.OTADeviceUpgradeStatus, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTADeviceUpgradeStatus), nil
	}
}

func (o oTADeviceUpgradeStatusDo) FirstOrCreate() (*model.OTADeviceUpgradeStatus, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTADeviceUpgradeStatus), nil
	}
}

func (o oTADeviceUpgradeStatusDo) FindByPage(offset int, limit int) (result []*model.OTADeviceUpgradeStatus, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oTADeviceUpgradeStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oTADeviceUpgradeStatusDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oTADeviceUpgradeStatusDo) Delete(models ...*model.OTADeviceUpgradeStatus) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oTADeviceUpgradeStatusDo) withDO(do gen.Dao) *oTADeviceUpgradeStatusDo {
	o.DO = *do.(*gen.DO)
	return o
}
