CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_APP_MQTT=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_NET_BUF_DATA_SIZE=512
CONFIG_NET_QEMU_USER=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_ETH_VIRTIO_NET=y
CONFIG_APP_BROKER="10.0.2.2"
CONFIG_NET_QEMU_DEVICE_EXTRA_ARGS="bus=virtio-mmio-bus.0"
