/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authCallbackRouteImport } from './routes/(auth)/callback'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedRuleEngineRouteRouteImport } from './routes/_authenticated/rule-engine/route'
import { Route as AuthenticatedOperationsMonitoringRouteRouteImport } from './routes/_authenticated/operations-monitoring/route'
import { Route as AuthenticatedDeviceManagementRouteRouteImport } from './routes/_authenticated/device-management/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRuleEngineIndexRouteImport } from './routes/_authenticated/rule-engine/index'
import { Route as AuthenticatedIotDashboardIndexRouteImport } from './routes/_authenticated/iot-dashboard/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedRuleEngineRuleChainsIndexRouteImport } from './routes/_authenticated/rule-engine/rule-chains/index'
import { Route as AuthenticatedOperationsMonitoringEventsIndexRouteImport } from './routes/_authenticated/operations-monitoring/events/index'
import { Route as AuthenticatedDeviceManagementProductsIndexRouteImport } from './routes/_authenticated/device-management/products/index'
import { Route as AuthenticatedDeviceManagementGroupsIndexRouteImport } from './routes/_authenticated/device-management/groups/index'
import { Route as AuthenticatedDeviceManagementDevicesIndexRouteImport } from './routes/_authenticated/device-management/devices/index'
import { Route as AuthenticatedRuleEngineRuleChainsNewIndexRouteImport } from './routes/_authenticated/rule-engine/rule-chains/new/index'
import { Route as AuthenticatedRuleEngineRuleChainsUuidIndexRouteImport } from './routes/_authenticated/rule-engine/rule-chains/$uuid/index'
import { Route as AuthenticatedOperationsMonitoringOtaPackagesIndexRouteImport } from './routes/_authenticated/operations-monitoring/ota/packages/index'
import { Route as AuthenticatedOperationsMonitoringOtaAnalyticsIndexRouteImport } from './routes/_authenticated/operations-monitoring/ota/analytics/index'
import { Route as AuthenticatedDeviceManagementProductsProductKeyIndexRouteImport } from './routes/_authenticated/device-management/products/$productKey/index'
import { Route as AuthenticatedDeviceManagementGroupsUuidIndexRouteImport } from './routes/_authenticated/device-management/groups/$uuid/index'
import { Route as AuthenticatedDeviceManagementDevicesDeviceKeyIndexRouteImport } from './routes/_authenticated/device-management/devices/$deviceKey/index'
import { Route as AuthenticatedRuleEngineRuleChainsUuidEditIndexRouteImport } from './routes/_authenticated/rule-engine/rule-chains/$uuid/edit/index'
import { Route as AuthenticatedOperationsMonitoringOtaPackagesIdIndexRouteImport } from './routes/_authenticated/operations-monitoring/ota/packages/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authCallbackRoute = authCallbackRouteImport.update({
  id: '/(auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRuleEngineRouteRoute =
  AuthenticatedRuleEngineRouteRouteImport.update({
    id: '/rule-engine',
    path: '/rule-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsMonitoringRouteRoute =
  AuthenticatedOperationsMonitoringRouteRouteImport.update({
    id: '/operations-monitoring',
    path: '/operations-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceManagementRouteRoute =
  AuthenticatedDeviceManagementRouteRouteImport.update({
    id: '/device-management',
    path: '/device-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRuleEngineIndexRoute =
  AuthenticatedRuleEngineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRuleEngineRouteRoute,
  } as any)
const AuthenticatedIotDashboardIndexRoute =
  AuthenticatedIotDashboardIndexRouteImport.update({
    id: '/iot-dashboard/',
    path: '/iot-dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRuleEngineRuleChainsIndexRoute =
  AuthenticatedRuleEngineRuleChainsIndexRouteImport.update({
    id: '/rule-chains/',
    path: '/rule-chains/',
    getParentRoute: () => AuthenticatedRuleEngineRouteRoute,
  } as any)
const AuthenticatedOperationsMonitoringEventsIndexRoute =
  AuthenticatedOperationsMonitoringEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedOperationsMonitoringRouteRoute,
  } as any)
const AuthenticatedDeviceManagementProductsIndexRoute =
  AuthenticatedDeviceManagementProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedDeviceManagementGroupsIndexRoute =
  AuthenticatedDeviceManagementGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedDeviceManagementDevicesIndexRoute =
  AuthenticatedDeviceManagementDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedRuleEngineRuleChainsNewIndexRoute =
  AuthenticatedRuleEngineRuleChainsNewIndexRouteImport.update({
    id: '/rule-chains/new/',
    path: '/rule-chains/new/',
    getParentRoute: () => AuthenticatedRuleEngineRouteRoute,
  } as any)
const AuthenticatedRuleEngineRuleChainsUuidIndexRoute =
  AuthenticatedRuleEngineRuleChainsUuidIndexRouteImport.update({
    id: '/rule-chains/$uuid/',
    path: '/rule-chains/$uuid/',
    getParentRoute: () => AuthenticatedRuleEngineRouteRoute,
  } as any)
const AuthenticatedOperationsMonitoringOtaPackagesIndexRoute =
  AuthenticatedOperationsMonitoringOtaPackagesIndexRouteImport.update({
    id: '/ota/packages/',
    path: '/ota/packages/',
    getParentRoute: () => AuthenticatedOperationsMonitoringRouteRoute,
  } as any)
const AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute =
  AuthenticatedOperationsMonitoringOtaAnalyticsIndexRouteImport.update({
    id: '/ota/analytics/',
    path: '/ota/analytics/',
    getParentRoute: () => AuthenticatedOperationsMonitoringRouteRoute,
  } as any)
const AuthenticatedDeviceManagementProductsProductKeyIndexRoute =
  AuthenticatedDeviceManagementProductsProductKeyIndexRouteImport.update({
    id: '/products/$productKey/',
    path: '/products/$productKey/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedDeviceManagementGroupsUuidIndexRoute =
  AuthenticatedDeviceManagementGroupsUuidIndexRouteImport.update({
    id: '/groups/$uuid/',
    path: '/groups/$uuid/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute =
  AuthenticatedDeviceManagementDevicesDeviceKeyIndexRouteImport.update({
    id: '/devices/$deviceKey/',
    path: '/devices/$deviceKey/',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)
const AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute =
  AuthenticatedRuleEngineRuleChainsUuidEditIndexRouteImport.update({
    id: '/rule-chains/$uuid/edit/',
    path: '/rule-chains/$uuid/edit/',
    getParentRoute: () => AuthenticatedRuleEngineRouteRoute,
  } as any)
const AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute =
  AuthenticatedOperationsMonitoringOtaPackagesIdIndexRouteImport.update({
    id: '/ota/packages/$id/',
    path: '/ota/packages/$id/',
    getParentRoute: () => AuthenticatedOperationsMonitoringRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/operations-monitoring': typeof AuthenticatedOperationsMonitoringRouteRouteWithChildren
  '/rule-engine': typeof AuthenticatedRuleEngineRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/callback': typeof authCallbackRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/iot-dashboard': typeof AuthenticatedIotDashboardIndexRoute
  '/rule-engine/': typeof AuthenticatedRuleEngineIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/device-management/devices': typeof AuthenticatedDeviceManagementDevicesIndexRoute
  '/device-management/groups': typeof AuthenticatedDeviceManagementGroupsIndexRoute
  '/device-management/products': typeof AuthenticatedDeviceManagementProductsIndexRoute
  '/operations-monitoring/events': typeof AuthenticatedOperationsMonitoringEventsIndexRoute
  '/rule-engine/rule-chains': typeof AuthenticatedRuleEngineRuleChainsIndexRoute
  '/device-management/devices/$deviceKey': typeof AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute
  '/device-management/groups/$uuid': typeof AuthenticatedDeviceManagementGroupsUuidIndexRoute
  '/device-management/products/$productKey': typeof AuthenticatedDeviceManagementProductsProductKeyIndexRoute
  '/operations-monitoring/ota/analytics': typeof AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute
  '/operations-monitoring/ota/packages': typeof AuthenticatedOperationsMonitoringOtaPackagesIndexRoute
  '/rule-engine/rule-chains/$uuid': typeof AuthenticatedRuleEngineRuleChainsUuidIndexRoute
  '/rule-engine/rule-chains/new': typeof AuthenticatedRuleEngineRuleChainsNewIndexRoute
  '/operations-monitoring/ota/packages/$id': typeof AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute
  '/rule-engine/rule-chains/$uuid/edit': typeof AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute
}
export interface FileRoutesByTo {
  '/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/operations-monitoring': typeof AuthenticatedOperationsMonitoringRouteRouteWithChildren
  '/callback': typeof authCallbackRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/iot-dashboard': typeof AuthenticatedIotDashboardIndexRoute
  '/rule-engine': typeof AuthenticatedRuleEngineIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/device-management/devices': typeof AuthenticatedDeviceManagementDevicesIndexRoute
  '/device-management/groups': typeof AuthenticatedDeviceManagementGroupsIndexRoute
  '/device-management/products': typeof AuthenticatedDeviceManagementProductsIndexRoute
  '/operations-monitoring/events': typeof AuthenticatedOperationsMonitoringEventsIndexRoute
  '/rule-engine/rule-chains': typeof AuthenticatedRuleEngineRuleChainsIndexRoute
  '/device-management/devices/$deviceKey': typeof AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute
  '/device-management/groups/$uuid': typeof AuthenticatedDeviceManagementGroupsUuidIndexRoute
  '/device-management/products/$productKey': typeof AuthenticatedDeviceManagementProductsProductKeyIndexRoute
  '/operations-monitoring/ota/analytics': typeof AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute
  '/operations-monitoring/ota/packages': typeof AuthenticatedOperationsMonitoringOtaPackagesIndexRoute
  '/rule-engine/rule-chains/$uuid': typeof AuthenticatedRuleEngineRuleChainsUuidIndexRoute
  '/rule-engine/rule-chains/new': typeof AuthenticatedRuleEngineRuleChainsNewIndexRoute
  '/operations-monitoring/ota/packages/$id': typeof AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute
  '/rule-engine/rule-chains/$uuid/edit': typeof AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/_authenticated/operations-monitoring': typeof AuthenticatedOperationsMonitoringRouteRouteWithChildren
  '/_authenticated/rule-engine': typeof AuthenticatedRuleEngineRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/callback': typeof authCallbackRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/iot-dashboard/': typeof AuthenticatedIotDashboardIndexRoute
  '/_authenticated/rule-engine/': typeof AuthenticatedRuleEngineIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/device-management/devices/': typeof AuthenticatedDeviceManagementDevicesIndexRoute
  '/_authenticated/device-management/groups/': typeof AuthenticatedDeviceManagementGroupsIndexRoute
  '/_authenticated/device-management/products/': typeof AuthenticatedDeviceManagementProductsIndexRoute
  '/_authenticated/operations-monitoring/events/': typeof AuthenticatedOperationsMonitoringEventsIndexRoute
  '/_authenticated/rule-engine/rule-chains/': typeof AuthenticatedRuleEngineRuleChainsIndexRoute
  '/_authenticated/device-management/devices/$deviceKey/': typeof AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute
  '/_authenticated/device-management/groups/$uuid/': typeof AuthenticatedDeviceManagementGroupsUuidIndexRoute
  '/_authenticated/device-management/products/$productKey/': typeof AuthenticatedDeviceManagementProductsProductKeyIndexRoute
  '/_authenticated/operations-monitoring/ota/analytics/': typeof AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute
  '/_authenticated/operations-monitoring/ota/packages/': typeof AuthenticatedOperationsMonitoringOtaPackagesIndexRoute
  '/_authenticated/rule-engine/rule-chains/$uuid/': typeof AuthenticatedRuleEngineRuleChainsUuidIndexRoute
  '/_authenticated/rule-engine/rule-chains/new/': typeof AuthenticatedRuleEngineRuleChainsNewIndexRoute
  '/_authenticated/operations-monitoring/ota/packages/$id/': typeof AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute
  '/_authenticated/rule-engine/rule-chains/$uuid/edit/': typeof AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/device-management'
    | '/operations-monitoring'
    | '/rule-engine'
    | '/settings'
    | '/callback'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/iot-dashboard'
    | '/rule-engine/'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/device-management/devices'
    | '/device-management/groups'
    | '/device-management/products'
    | '/operations-monitoring/events'
    | '/rule-engine/rule-chains'
    | '/device-management/devices/$deviceKey'
    | '/device-management/groups/$uuid'
    | '/device-management/products/$productKey'
    | '/operations-monitoring/ota/analytics'
    | '/operations-monitoring/ota/packages'
    | '/rule-engine/rule-chains/$uuid'
    | '/rule-engine/rule-chains/new'
    | '/operations-monitoring/ota/packages/$id'
    | '/rule-engine/rule-chains/$uuid/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/device-management'
    | '/operations-monitoring'
    | '/callback'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/iot-dashboard'
    | '/rule-engine'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/device-management/devices'
    | '/device-management/groups'
    | '/device-management/products'
    | '/operations-monitoring/events'
    | '/rule-engine/rule-chains'
    | '/device-management/devices/$deviceKey'
    | '/device-management/groups/$uuid'
    | '/device-management/products/$productKey'
    | '/operations-monitoring/ota/analytics'
    | '/operations-monitoring/ota/packages'
    | '/rule-engine/rule-chains/$uuid'
    | '/rule-engine/rule-chains/new'
    | '/operations-monitoring/ota/packages/$id'
    | '/rule-engine/rule-chains/$uuid/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/device-management'
    | '/_authenticated/operations-monitoring'
    | '/_authenticated/rule-engine'
    | '/_authenticated/settings'
    | '/(auth)/callback'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/iot-dashboard/'
    | '/_authenticated/rule-engine/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/device-management/devices/'
    | '/_authenticated/device-management/groups/'
    | '/_authenticated/device-management/products/'
    | '/_authenticated/operations-monitoring/events/'
    | '/_authenticated/rule-engine/rule-chains/'
    | '/_authenticated/device-management/devices/$deviceKey/'
    | '/_authenticated/device-management/groups/$uuid/'
    | '/_authenticated/device-management/products/$productKey/'
    | '/_authenticated/operations-monitoring/ota/analytics/'
    | '/_authenticated/operations-monitoring/ota/packages/'
    | '/_authenticated/rule-engine/rule-chains/$uuid/'
    | '/_authenticated/rule-engine/rule-chains/new/'
    | '/_authenticated/operations-monitoring/ota/packages/$id/'
    | '/_authenticated/rule-engine/rule-chains/$uuid/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authCallbackRoute: typeof authCallbackRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rule-engine': {
      id: '/_authenticated/rule-engine'
      path: '/rule-engine'
      fullPath: '/rule-engine'
      preLoaderRoute: typeof AuthenticatedRuleEngineRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations-monitoring': {
      id: '/_authenticated/operations-monitoring'
      path: '/operations-monitoring'
      fullPath: '/operations-monitoring'
      preLoaderRoute: typeof AuthenticatedOperationsMonitoringRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-management': {
      id: '/_authenticated/device-management'
      path: '/device-management'
      fullPath: '/device-management'
      preLoaderRoute: typeof AuthenticatedDeviceManagementRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/rule-engine/': {
      id: '/_authenticated/rule-engine/'
      path: '/'
      fullPath: '/rule-engine/'
      preLoaderRoute: typeof AuthenticatedRuleEngineIndexRouteImport
      parentRoute: typeof AuthenticatedRuleEngineRouteRoute
    }
    '/_authenticated/iot-dashboard/': {
      id: '/_authenticated/iot-dashboard/'
      path: '/iot-dashboard'
      fullPath: '/iot-dashboard'
      preLoaderRoute: typeof AuthenticatedIotDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rule-engine/rule-chains/': {
      id: '/_authenticated/rule-engine/rule-chains/'
      path: '/rule-chains'
      fullPath: '/rule-engine/rule-chains'
      preLoaderRoute: typeof AuthenticatedRuleEngineRuleChainsIndexRouteImport
      parentRoute: typeof AuthenticatedRuleEngineRouteRoute
    }
    '/_authenticated/operations-monitoring/events/': {
      id: '/_authenticated/operations-monitoring/events/'
      path: '/events'
      fullPath: '/operations-monitoring/events'
      preLoaderRoute: typeof AuthenticatedOperationsMonitoringEventsIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsMonitoringRouteRoute
    }
    '/_authenticated/device-management/products/': {
      id: '/_authenticated/device-management/products/'
      path: '/products'
      fullPath: '/device-management/products'
      preLoaderRoute: typeof AuthenticatedDeviceManagementProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/device-management/groups/': {
      id: '/_authenticated/device-management/groups/'
      path: '/groups'
      fullPath: '/device-management/groups'
      preLoaderRoute: typeof AuthenticatedDeviceManagementGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/device-management/devices/': {
      id: '/_authenticated/device-management/devices/'
      path: '/devices'
      fullPath: '/device-management/devices'
      preLoaderRoute: typeof AuthenticatedDeviceManagementDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/rule-engine/rule-chains/new/': {
      id: '/_authenticated/rule-engine/rule-chains/new/'
      path: '/rule-chains/new'
      fullPath: '/rule-engine/rule-chains/new'
      preLoaderRoute: typeof AuthenticatedRuleEngineRuleChainsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRuleEngineRouteRoute
    }
    '/_authenticated/rule-engine/rule-chains/$uuid/': {
      id: '/_authenticated/rule-engine/rule-chains/$uuid/'
      path: '/rule-chains/$uuid'
      fullPath: '/rule-engine/rule-chains/$uuid'
      preLoaderRoute: typeof AuthenticatedRuleEngineRuleChainsUuidIndexRouteImport
      parentRoute: typeof AuthenticatedRuleEngineRouteRoute
    }
    '/_authenticated/operations-monitoring/ota/packages/': {
      id: '/_authenticated/operations-monitoring/ota/packages/'
      path: '/ota/packages'
      fullPath: '/operations-monitoring/ota/packages'
      preLoaderRoute: typeof AuthenticatedOperationsMonitoringOtaPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsMonitoringRouteRoute
    }
    '/_authenticated/operations-monitoring/ota/analytics/': {
      id: '/_authenticated/operations-monitoring/ota/analytics/'
      path: '/ota/analytics'
      fullPath: '/operations-monitoring/ota/analytics'
      preLoaderRoute: typeof AuthenticatedOperationsMonitoringOtaAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsMonitoringRouteRoute
    }
    '/_authenticated/device-management/products/$productKey/': {
      id: '/_authenticated/device-management/products/$productKey/'
      path: '/products/$productKey'
      fullPath: '/device-management/products/$productKey'
      preLoaderRoute: typeof AuthenticatedDeviceManagementProductsProductKeyIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/device-management/groups/$uuid/': {
      id: '/_authenticated/device-management/groups/$uuid/'
      path: '/groups/$uuid'
      fullPath: '/device-management/groups/$uuid'
      preLoaderRoute: typeof AuthenticatedDeviceManagementGroupsUuidIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/device-management/devices/$deviceKey/': {
      id: '/_authenticated/device-management/devices/$deviceKey/'
      path: '/devices/$deviceKey'
      fullPath: '/device-management/devices/$deviceKey'
      preLoaderRoute: typeof AuthenticatedDeviceManagementDevicesDeviceKeyIndexRouteImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteRoute
    }
    '/_authenticated/rule-engine/rule-chains/$uuid/edit/': {
      id: '/_authenticated/rule-engine/rule-chains/$uuid/edit/'
      path: '/rule-chains/$uuid/edit'
      fullPath: '/rule-engine/rule-chains/$uuid/edit'
      preLoaderRoute: typeof AuthenticatedRuleEngineRuleChainsUuidEditIndexRouteImport
      parentRoute: typeof AuthenticatedRuleEngineRouteRoute
    }
    '/_authenticated/operations-monitoring/ota/packages/$id/': {
      id: '/_authenticated/operations-monitoring/ota/packages/$id/'
      path: '/ota/packages/$id'
      fullPath: '/operations-monitoring/ota/packages/$id'
      preLoaderRoute: typeof AuthenticatedOperationsMonitoringOtaPackagesIdIndexRouteImport
      parentRoute: typeof AuthenticatedOperationsMonitoringRouteRoute
    }
  }
}

interface AuthenticatedDeviceManagementRouteRouteChildren {
  AuthenticatedDeviceManagementDevicesIndexRoute: typeof AuthenticatedDeviceManagementDevicesIndexRoute
  AuthenticatedDeviceManagementGroupsIndexRoute: typeof AuthenticatedDeviceManagementGroupsIndexRoute
  AuthenticatedDeviceManagementProductsIndexRoute: typeof AuthenticatedDeviceManagementProductsIndexRoute
  AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute: typeof AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute
  AuthenticatedDeviceManagementGroupsUuidIndexRoute: typeof AuthenticatedDeviceManagementGroupsUuidIndexRoute
  AuthenticatedDeviceManagementProductsProductKeyIndexRoute: typeof AuthenticatedDeviceManagementProductsProductKeyIndexRoute
}

const AuthenticatedDeviceManagementRouteRouteChildren: AuthenticatedDeviceManagementRouteRouteChildren =
  {
    AuthenticatedDeviceManagementDevicesIndexRoute:
      AuthenticatedDeviceManagementDevicesIndexRoute,
    AuthenticatedDeviceManagementGroupsIndexRoute:
      AuthenticatedDeviceManagementGroupsIndexRoute,
    AuthenticatedDeviceManagementProductsIndexRoute:
      AuthenticatedDeviceManagementProductsIndexRoute,
    AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute:
      AuthenticatedDeviceManagementDevicesDeviceKeyIndexRoute,
    AuthenticatedDeviceManagementGroupsUuidIndexRoute:
      AuthenticatedDeviceManagementGroupsUuidIndexRoute,
    AuthenticatedDeviceManagementProductsProductKeyIndexRoute:
      AuthenticatedDeviceManagementProductsProductKeyIndexRoute,
  }

const AuthenticatedDeviceManagementRouteRouteWithChildren =
  AuthenticatedDeviceManagementRouteRoute._addFileChildren(
    AuthenticatedDeviceManagementRouteRouteChildren,
  )

interface AuthenticatedOperationsMonitoringRouteRouteChildren {
  AuthenticatedOperationsMonitoringEventsIndexRoute: typeof AuthenticatedOperationsMonitoringEventsIndexRoute
  AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute: typeof AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute
  AuthenticatedOperationsMonitoringOtaPackagesIndexRoute: typeof AuthenticatedOperationsMonitoringOtaPackagesIndexRoute
  AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute: typeof AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute
}

const AuthenticatedOperationsMonitoringRouteRouteChildren: AuthenticatedOperationsMonitoringRouteRouteChildren =
  {
    AuthenticatedOperationsMonitoringEventsIndexRoute:
      AuthenticatedOperationsMonitoringEventsIndexRoute,
    AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute:
      AuthenticatedOperationsMonitoringOtaAnalyticsIndexRoute,
    AuthenticatedOperationsMonitoringOtaPackagesIndexRoute:
      AuthenticatedOperationsMonitoringOtaPackagesIndexRoute,
    AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute:
      AuthenticatedOperationsMonitoringOtaPackagesIdIndexRoute,
  }

const AuthenticatedOperationsMonitoringRouteRouteWithChildren =
  AuthenticatedOperationsMonitoringRouteRoute._addFileChildren(
    AuthenticatedOperationsMonitoringRouteRouteChildren,
  )

interface AuthenticatedRuleEngineRouteRouteChildren {
  AuthenticatedRuleEngineIndexRoute: typeof AuthenticatedRuleEngineIndexRoute
  AuthenticatedRuleEngineRuleChainsIndexRoute: typeof AuthenticatedRuleEngineRuleChainsIndexRoute
  AuthenticatedRuleEngineRuleChainsUuidIndexRoute: typeof AuthenticatedRuleEngineRuleChainsUuidIndexRoute
  AuthenticatedRuleEngineRuleChainsNewIndexRoute: typeof AuthenticatedRuleEngineRuleChainsNewIndexRoute
  AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute: typeof AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute
}

const AuthenticatedRuleEngineRouteRouteChildren: AuthenticatedRuleEngineRouteRouteChildren =
  {
    AuthenticatedRuleEngineIndexRoute: AuthenticatedRuleEngineIndexRoute,
    AuthenticatedRuleEngineRuleChainsIndexRoute:
      AuthenticatedRuleEngineRuleChainsIndexRoute,
    AuthenticatedRuleEngineRuleChainsUuidIndexRoute:
      AuthenticatedRuleEngineRuleChainsUuidIndexRoute,
    AuthenticatedRuleEngineRuleChainsNewIndexRoute:
      AuthenticatedRuleEngineRuleChainsNewIndexRoute,
    AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute:
      AuthenticatedRuleEngineRuleChainsUuidEditIndexRoute,
  }

const AuthenticatedRuleEngineRouteRouteWithChildren =
  AuthenticatedRuleEngineRouteRoute._addFileChildren(
    AuthenticatedRuleEngineRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeviceManagementRouteRoute: typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  AuthenticatedOperationsMonitoringRouteRoute: typeof AuthenticatedOperationsMonitoringRouteRouteWithChildren
  AuthenticatedRuleEngineRouteRoute: typeof AuthenticatedRuleEngineRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedIotDashboardIndexRoute: typeof AuthenticatedIotDashboardIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeviceManagementRouteRoute:
    AuthenticatedDeviceManagementRouteRouteWithChildren,
  AuthenticatedOperationsMonitoringRouteRoute:
    AuthenticatedOperationsMonitoringRouteRouteWithChildren,
  AuthenticatedRuleEngineRouteRoute:
    AuthenticatedRuleEngineRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedIotDashboardIndexRoute: AuthenticatedIotDashboardIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authCallbackRoute: authCallbackRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
