// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newDevice(db *gorm.DB, opts ...gen.DOOption) device {
	_device := device{}

	_device.deviceDo.UseDB(db, opts...)
	_device.deviceDo.UseModel(&model.Device{})

	tableName := _device.deviceDo.TableName()
	_device.ALL = field.NewAsterisk(tableName)
	_device.ID = field.NewInt64(tableName, "id")
	_device.DeviceKey = field.NewString(tableName, "device_key")
	_device.Name = field.NewString(tableName, "name")
	_device.ProductID = field.NewInt64(tableName, "product_id")
	_device.OrganizationID = field.NewInt64(tableName, "organization_id")
	_device.Enabled = field.NewBool(tableName, "enabled")
	_device.Metadata = field.NewString(tableName, "metadata")
	_device.DeletedAt = field.NewField(tableName, "deleted_at")
	_device.CreatedAt = field.NewTime(tableName, "created_at")
	_device.UpdatedAt = field.NewTime(tableName, "updated_at")
	_device.State = deviceHasOneState{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("State", "model.DeviceState"),
	}

	_device.Product = deviceBelongsToProduct{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Product", "model.Product"),
	}

	_device.fillFieldMap()

	return _device
}

type device struct {
	deviceDo deviceDo

	ALL       field.Asterisk
	ID        field.Int64
	DeviceKey field.String
	Name      field.String
	ProductID field.Int64
	OrganizationID  field.Int64
	Enabled   field.Bool
	Metadata  field.String
	DeletedAt field.Field
	CreatedAt field.Time
	UpdatedAt field.Time
	State     deviceHasOneState

	Product deviceBelongsToProduct

	fieldMap map[string]field.Expr
}

func (d device) Table(newTableName string) *device {
	d.deviceDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d device) As(alias string) *device {
	d.deviceDo.DO = *(d.deviceDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *device) updateTableName(table string) *device {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceKey = field.NewString(table, "device_key")
	d.Name = field.NewString(table, "name")
	d.ProductID = field.NewInt64(table, "product_id")
	d.OrganizationID = field.NewInt64(table, "organization_id")
	d.Enabled = field.NewBool(table, "enabled")
	d.Metadata = field.NewString(table, "metadata")
	d.DeletedAt = field.NewField(table, "deleted_at")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *device) WithContext(ctx context.Context) *deviceDo { return d.deviceDo.WithContext(ctx) }

func (d device) TableName() string { return d.deviceDo.TableName() }

func (d device) Alias() string { return d.deviceDo.Alias() }

func (d device) Columns(cols ...field.Expr) gen.Columns { return d.deviceDo.Columns(cols...) }

func (d *device) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *device) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 12)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_key"] = d.DeviceKey
	d.fieldMap["name"] = d.Name
	d.fieldMap["product_id"] = d.ProductID
	d.fieldMap["organization_id"] = d.OrganizationID
	d.fieldMap["enabled"] = d.Enabled
	d.fieldMap["metadata"] = d.Metadata
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d device) clone(db *gorm.DB) device {
	d.deviceDo.ReplaceConnPool(db.Statement.ConnPool)
	d.State.db = db.Session(&gorm.Session{Initialized: true})
	d.State.db.Statement.ConnPool = db.Statement.ConnPool
	d.Product.db = db.Session(&gorm.Session{Initialized: true})
	d.Product.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d device) replaceDB(db *gorm.DB) device {
	d.deviceDo.ReplaceDB(db)
	d.State.db = db.Session(&gorm.Session{})
	d.Product.db = db.Session(&gorm.Session{})
	return d
}

type deviceHasOneState struct {
	db *gorm.DB

	field.RelationField
}

func (a deviceHasOneState) Where(conds ...field.Expr) *deviceHasOneState {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceHasOneState) WithContext(ctx context.Context) *deviceHasOneState {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceHasOneState) Session(session *gorm.Session) *deviceHasOneState {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceHasOneState) Model(m *model.Device) *deviceHasOneStateTx {
	return &deviceHasOneStateTx{a.db.Model(m).Association(a.Name())}
}

func (a deviceHasOneState) Unscoped() *deviceHasOneState {
	a.db = a.db.Unscoped()
	return &a
}

type deviceHasOneStateTx struct{ tx *gorm.Association }

func (a deviceHasOneStateTx) Find() (result *model.DeviceState, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceHasOneStateTx) Append(values ...*model.DeviceState) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceHasOneStateTx) Replace(values ...*model.DeviceState) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceHasOneStateTx) Delete(values ...*model.DeviceState) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceHasOneStateTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceHasOneStateTx) Count() int64 {
	return a.tx.Count()
}

func (a deviceHasOneStateTx) Unscoped() *deviceHasOneStateTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deviceBelongsToProduct struct {
	db *gorm.DB

	field.RelationField
}

func (a deviceBelongsToProduct) Where(conds ...field.Expr) *deviceBelongsToProduct {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceBelongsToProduct) WithContext(ctx context.Context) *deviceBelongsToProduct {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceBelongsToProduct) Session(session *gorm.Session) *deviceBelongsToProduct {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceBelongsToProduct) Model(m *model.Device) *deviceBelongsToProductTx {
	return &deviceBelongsToProductTx{a.db.Model(m).Association(a.Name())}
}

func (a deviceBelongsToProduct) Unscoped() *deviceBelongsToProduct {
	a.db = a.db.Unscoped()
	return &a
}

type deviceBelongsToProductTx struct{ tx *gorm.Association }

func (a deviceBelongsToProductTx) Find() (result *model.Product, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceBelongsToProductTx) Append(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceBelongsToProductTx) Replace(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceBelongsToProductTx) Delete(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceBelongsToProductTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceBelongsToProductTx) Count() int64 {
	return a.tx.Count()
}

func (a deviceBelongsToProductTx) Unscoped() *deviceBelongsToProductTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deviceDo struct{ gen.DO }

func (d deviceDo) Debug() *deviceDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceDo) WithContext(ctx context.Context) *deviceDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceDo) ReadDB() *deviceDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceDo) WriteDB() *deviceDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceDo) Session(config *gorm.Session) *deviceDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceDo) Clauses(conds ...clause.Expression) *deviceDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceDo) Returning(value interface{}, columns ...string) *deviceDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceDo) Not(conds ...gen.Condition) *deviceDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceDo) Or(conds ...gen.Condition) *deviceDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceDo) Select(conds ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceDo) Where(conds ...gen.Condition) *deviceDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceDo) Order(conds ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceDo) Distinct(cols ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceDo) Omit(cols ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceDo) Join(table schema.Tabler, on ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deviceDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceDo) RightJoin(table schema.Tabler, on ...field.Expr) *deviceDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceDo) Group(cols ...field.Expr) *deviceDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceDo) Having(conds ...gen.Condition) *deviceDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceDo) Limit(limit int) *deviceDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceDo) Offset(offset int) *deviceDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deviceDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceDo) Unscoped() *deviceDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceDo) Create(values ...*model.Device) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceDo) CreateInBatches(values []*model.Device, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceDo) Save(values ...*model.Device) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceDo) First() (*model.Device, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Device), nil
	}
}

func (d deviceDo) Take() (*model.Device, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Device), nil
	}
}

func (d deviceDo) Last() (*model.Device, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Device), nil
	}
}

func (d deviceDo) Find() ([]*model.Device, error) {
	result, err := d.DO.Find()
	return result.([]*model.Device), err
}

func (d deviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Device, err error) {
	buf := make([]*model.Device, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceDo) FindInBatches(result *[]*model.Device, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceDo) Attrs(attrs ...field.AssignExpr) *deviceDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceDo) Assign(attrs ...field.AssignExpr) *deviceDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceDo) Joins(fields ...field.RelationField) *deviceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceDo) Preload(fields ...field.RelationField) *deviceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceDo) FirstOrInit() (*model.Device, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Device), nil
	}
}

func (d deviceDo) FirstOrCreate() (*model.Device, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Device), nil
	}
}

func (d deviceDo) FindByPage(offset int, limit int) (result []*model.Device, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceDo) Delete(models ...*model.Device) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceDo) withDO(do gen.Dao) *deviceDo {
	d.DO = *do.(*gen.DO)
	return d
}
