// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newDeviceEvent(db *gorm.DB, opts ...gen.DOOption) deviceEvent {
	_deviceEvent := deviceEvent{}

	_deviceEvent.deviceEventDo.UseDB(db, opts...)
	_deviceEvent.deviceEventDo.UseModel(&model.DeviceEvent{})

	tableName := _deviceEvent.deviceEventDo.TableName()
	_deviceEvent.ALL = field.NewAsterisk(tableName)
	_deviceEvent.ID = field.NewInt64(tableName, "id")
	_deviceEvent.DeviceID = field.NewInt64(tableName, "device_id")
	_deviceEvent.EventType = field.NewString(tableName, "event_type")
	_deviceEvent.EventAt = field.NewTime(tableName, "event_at")
	_deviceEvent.Data = field.NewString(tableName, "data")
	_deviceEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceEvent.DeviceKey = field.NewString(tableName, "device_key")
	_deviceEvent.DeviceName = field.NewString(tableName, "device_name")

	_deviceEvent.fillFieldMap()

	return _deviceEvent
}

type deviceEvent struct {
	deviceEventDo deviceEventDo

	ALL        field.Asterisk
	ID         field.Int64
	DeviceID   field.Int64
	EventType  field.String
	EventAt    field.Time
	Data       field.String
	CreatedAt  field.Time
	DeviceKey  field.String
	DeviceName field.String

	fieldMap map[string]field.Expr
}

func (d deviceEvent) Table(newTableName string) *deviceEvent {
	d.deviceEventDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceEvent) As(alias string) *deviceEvent {
	d.deviceEventDo.DO = *(d.deviceEventDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceEvent) updateTableName(table string) *deviceEvent {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceID = field.NewInt64(table, "device_id")
	d.EventType = field.NewString(table, "event_type")
	d.EventAt = field.NewTime(table, "event_at")
	d.Data = field.NewString(table, "data")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.DeviceKey = field.NewString(table, "device_key")
	d.DeviceName = field.NewString(table, "device_name")

	d.fillFieldMap()

	return d
}

func (d *deviceEvent) WithContext(ctx context.Context) *deviceEventDo {
	return d.deviceEventDo.WithContext(ctx)
}

func (d deviceEvent) TableName() string { return d.deviceEventDo.TableName() }

func (d deviceEvent) Alias() string { return d.deviceEventDo.Alias() }

func (d deviceEvent) Columns(cols ...field.Expr) gen.Columns { return d.deviceEventDo.Columns(cols...) }

func (d *deviceEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceEvent) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["event_type"] = d.EventType
	d.fieldMap["event_at"] = d.EventAt
	d.fieldMap["data"] = d.Data
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["device_key"] = d.DeviceKey
	d.fieldMap["device_name"] = d.DeviceName
}

func (d deviceEvent) clone(db *gorm.DB) deviceEvent {
	d.deviceEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceEvent) replaceDB(db *gorm.DB) deviceEvent {
	d.deviceEventDo.ReplaceDB(db)
	return d
}

type deviceEventDo struct{ gen.DO }

func (d deviceEventDo) Debug() *deviceEventDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceEventDo) WithContext(ctx context.Context) *deviceEventDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceEventDo) ReadDB() *deviceEventDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceEventDo) WriteDB() *deviceEventDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceEventDo) Session(config *gorm.Session) *deviceEventDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceEventDo) Clauses(conds ...clause.Expression) *deviceEventDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceEventDo) Returning(value interface{}, columns ...string) *deviceEventDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceEventDo) Not(conds ...gen.Condition) *deviceEventDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceEventDo) Or(conds ...gen.Condition) *deviceEventDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceEventDo) Select(conds ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceEventDo) Where(conds ...gen.Condition) *deviceEventDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceEventDo) Order(conds ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceEventDo) Distinct(cols ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceEventDo) Omit(cols ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceEventDo) Join(table schema.Tabler, on ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceEventDo) RightJoin(table schema.Tabler, on ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceEventDo) Group(cols ...field.Expr) *deviceEventDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceEventDo) Having(conds ...gen.Condition) *deviceEventDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceEventDo) Limit(limit int) *deviceEventDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceEventDo) Offset(offset int) *deviceEventDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deviceEventDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceEventDo) Unscoped() *deviceEventDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceEventDo) Create(values ...*model.DeviceEvent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceEventDo) CreateInBatches(values []*model.DeviceEvent, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceEventDo) Save(values ...*model.DeviceEvent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceEventDo) First() (*model.DeviceEvent, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceEvent), nil
	}
}

func (d deviceEventDo) Take() (*model.DeviceEvent, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceEvent), nil
	}
}

func (d deviceEventDo) Last() (*model.DeviceEvent, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceEvent), nil
	}
}

func (d deviceEventDo) Find() ([]*model.DeviceEvent, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceEvent), err
}

func (d deviceEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceEvent, err error) {
	buf := make([]*model.DeviceEvent, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceEventDo) FindInBatches(result *[]*model.DeviceEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceEventDo) Attrs(attrs ...field.AssignExpr) *deviceEventDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceEventDo) Assign(attrs ...field.AssignExpr) *deviceEventDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceEventDo) Joins(fields ...field.RelationField) *deviceEventDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceEventDo) Preload(fields ...field.RelationField) *deviceEventDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceEventDo) FirstOrInit() (*model.DeviceEvent, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceEvent), nil
	}
}

func (d deviceEventDo) FirstOrCreate() (*model.DeviceEvent, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceEvent), nil
	}
}

func (d deviceEventDo) FindByPage(offset int, limit int) (result []*model.DeviceEvent, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceEventDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceEventDo) Delete(models ...*model.DeviceEvent) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceEventDo) withDO(do gen.Dao) *deviceEventDo {
	d.DO = *do.(*gen.DO)
	return d
}
