// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newDeviceServiceInvocation(db *gorm.DB, opts ...gen.DOOption) deviceServiceInvocation {
	_deviceServiceInvocation := deviceServiceInvocation{}

	_deviceServiceInvocation.deviceServiceInvocationDo.UseDB(db, opts...)
	_deviceServiceInvocation.deviceServiceInvocationDo.UseModel(&model.DeviceServiceInvocation{})

	tableName := _deviceServiceInvocation.deviceServiceInvocationDo.TableName()
	_deviceServiceInvocation.ALL = field.NewAsterisk(tableName)
	_deviceServiceInvocation.ID = field.NewInt64(tableName, "id")
	_deviceServiceInvocation.UUID = field.NewString(tableName, "uuid")
	_deviceServiceInvocation.DeviceID = field.NewInt64(tableName, "device_id")
	_deviceServiceInvocation.ServiceIdentifier = field.NewString(tableName, "service_identifier")
	_deviceServiceInvocation.ServiceName = field.NewString(tableName, "service_name")
	_deviceServiceInvocation.InputParams = field.NewString(tableName, "input_params")
	_deviceServiceInvocation.OutputParams = field.NewString(tableName, "output_params")
	_deviceServiceInvocation.InvokedAt = field.NewTime(tableName, "invoked_at")
	_deviceServiceInvocation.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceServiceInvocation.UpdatedAt = field.NewTime(tableName, "updated_at")

	_deviceServiceInvocation.fillFieldMap()

	return _deviceServiceInvocation
}

type deviceServiceInvocation struct {
	deviceServiceInvocationDo deviceServiceInvocationDo

	ALL               field.Asterisk
	ID                field.Int64
	UUID              field.String
	DeviceID          field.Int64
	ServiceIdentifier field.String
	ServiceName       field.String
	InputParams       field.String
	OutputParams      field.String
	InvokedAt         field.Time
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (d deviceServiceInvocation) Table(newTableName string) *deviceServiceInvocation {
	d.deviceServiceInvocationDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceServiceInvocation) As(alias string) *deviceServiceInvocation {
	d.deviceServiceInvocationDo.DO = *(d.deviceServiceInvocationDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceServiceInvocation) updateTableName(table string) *deviceServiceInvocation {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.UUID = field.NewString(table, "uuid")
	d.DeviceID = field.NewInt64(table, "device_id")
	d.ServiceIdentifier = field.NewString(table, "service_identifier")
	d.ServiceName = field.NewString(table, "service_name")
	d.InputParams = field.NewString(table, "input_params")
	d.OutputParams = field.NewString(table, "output_params")
	d.InvokedAt = field.NewTime(table, "invoked_at")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceServiceInvocation) WithContext(ctx context.Context) *deviceServiceInvocationDo {
	return d.deviceServiceInvocationDo.WithContext(ctx)
}

func (d deviceServiceInvocation) TableName() string { return d.deviceServiceInvocationDo.TableName() }

func (d deviceServiceInvocation) Alias() string { return d.deviceServiceInvocationDo.Alias() }

func (d deviceServiceInvocation) Columns(cols ...field.Expr) gen.Columns {
	return d.deviceServiceInvocationDo.Columns(cols...)
}

func (d *deviceServiceInvocation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceServiceInvocation) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["uuid"] = d.UUID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["service_identifier"] = d.ServiceIdentifier
	d.fieldMap["service_name"] = d.ServiceName
	d.fieldMap["input_params"] = d.InputParams
	d.fieldMap["output_params"] = d.OutputParams
	d.fieldMap["invoked_at"] = d.InvokedAt
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceServiceInvocation) clone(db *gorm.DB) deviceServiceInvocation {
	d.deviceServiceInvocationDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceServiceInvocation) replaceDB(db *gorm.DB) deviceServiceInvocation {
	d.deviceServiceInvocationDo.ReplaceDB(db)
	return d
}

type deviceServiceInvocationDo struct{ gen.DO }

func (d deviceServiceInvocationDo) Debug() *deviceServiceInvocationDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceServiceInvocationDo) WithContext(ctx context.Context) *deviceServiceInvocationDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceServiceInvocationDo) ReadDB() *deviceServiceInvocationDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceServiceInvocationDo) WriteDB() *deviceServiceInvocationDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceServiceInvocationDo) Session(config *gorm.Session) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceServiceInvocationDo) Clauses(conds ...clause.Expression) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceServiceInvocationDo) Returning(value interface{}, columns ...string) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceServiceInvocationDo) Not(conds ...gen.Condition) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceServiceInvocationDo) Or(conds ...gen.Condition) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceServiceInvocationDo) Select(conds ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceServiceInvocationDo) Where(conds ...gen.Condition) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceServiceInvocationDo) Order(conds ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceServiceInvocationDo) Distinct(cols ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceServiceInvocationDo) Omit(cols ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceServiceInvocationDo) Join(table schema.Tabler, on ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceServiceInvocationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceServiceInvocationDo) RightJoin(table schema.Tabler, on ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceServiceInvocationDo) Group(cols ...field.Expr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceServiceInvocationDo) Having(conds ...gen.Condition) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceServiceInvocationDo) Limit(limit int) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceServiceInvocationDo) Offset(offset int) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceServiceInvocationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceServiceInvocationDo) Unscoped() *deviceServiceInvocationDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceServiceInvocationDo) Create(values ...*model.DeviceServiceInvocation) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceServiceInvocationDo) CreateInBatches(values []*model.DeviceServiceInvocation, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceServiceInvocationDo) Save(values ...*model.DeviceServiceInvocation) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceServiceInvocationDo) First() (*model.DeviceServiceInvocation, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceServiceInvocation), nil
	}
}

func (d deviceServiceInvocationDo) Take() (*model.DeviceServiceInvocation, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceServiceInvocation), nil
	}
}

func (d deviceServiceInvocationDo) Last() (*model.DeviceServiceInvocation, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceServiceInvocation), nil
	}
}

func (d deviceServiceInvocationDo) Find() ([]*model.DeviceServiceInvocation, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceServiceInvocation), err
}

func (d deviceServiceInvocationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceServiceInvocation, err error) {
	buf := make([]*model.DeviceServiceInvocation, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceServiceInvocationDo) FindInBatches(result *[]*model.DeviceServiceInvocation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceServiceInvocationDo) Attrs(attrs ...field.AssignExpr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceServiceInvocationDo) Assign(attrs ...field.AssignExpr) *deviceServiceInvocationDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceServiceInvocationDo) Joins(fields ...field.RelationField) *deviceServiceInvocationDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceServiceInvocationDo) Preload(fields ...field.RelationField) *deviceServiceInvocationDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceServiceInvocationDo) FirstOrInit() (*model.DeviceServiceInvocation, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceServiceInvocation), nil
	}
}

func (d deviceServiceInvocationDo) FirstOrCreate() (*model.DeviceServiceInvocation, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceServiceInvocation), nil
	}
}

func (d deviceServiceInvocationDo) FindByPage(offset int, limit int) (result []*model.DeviceServiceInvocation, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceServiceInvocationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceServiceInvocationDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceServiceInvocationDo) Delete(models ...*model.DeviceServiceInvocation) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceServiceInvocationDo) withDO(do gen.Dao) *deviceServiceInvocationDo {
	d.DO = *do.(*gen.DO)
	return d
}
