// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		Alert:                newAlert(db, opts...),
		Device:               newDevice(db, opts...),
		DeviceEvent:          newDeviceEvent(db, opts...),
		DevicePushRecord:     newDevicePushRecord(db, opts...),
		DeviceShadow:         newDeviceShadow(db, opts...),
		DeviceShadowHistory:  newDeviceShadowHistory(db, opts...),
		DeviceState:          newDeviceState(db, opts...),
		DeviceTag:            newDeviceTag(db, opts...),
		DeviceUpgradeStatus:  newDeviceUpgradeStatus(db, opts...),
		OTAPackage:           newOTAPackage(db, opts...),
		Product:              newProduct(db, opts...),
		ProductMessageParser: newProductMessageParser(db, opts...),
		ProductTSL:           newProductTSL(db, opts...),
		SceneLinkage:         newSceneLinkage(db, opts...),
		SceneLinkageDetail:   newSceneLinkageDetail(db, opts...),
		UpgradeBatch:         newUpgradeBatch(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Alert                alert
	Device               device
	DeviceEvent          deviceEvent
	DevicePushRecord     devicePushRecord
	DeviceShadow         deviceShadow
	DeviceShadowHistory  deviceShadowHistory
	DeviceState          deviceState
	DeviceTag            deviceTag
	DeviceUpgradeStatus  deviceUpgradeStatus
	OTAPackage           oTAPackage
	Product              product
	ProductMessageParser productMessageParser
	ProductTSL           productTSL
	SceneLinkage         sceneLinkage
	SceneLinkageDetail   sceneLinkageDetail
	UpgradeBatch         upgradeBatch
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		Alert:                q.Alert.clone(db),
		Device:               q.Device.clone(db),
		DeviceEvent:          q.DeviceEvent.clone(db),
		DevicePushRecord:     q.DevicePushRecord.clone(db),
		DeviceShadow:         q.DeviceShadow.clone(db),
		DeviceShadowHistory:  q.DeviceShadowHistory.clone(db),
		DeviceState:          q.DeviceState.clone(db),
		DeviceTag:            q.DeviceTag.clone(db),
		DeviceUpgradeStatus:  q.DeviceUpgradeStatus.clone(db),
		OTAPackage:           q.OTAPackage.clone(db),
		Product:              q.Product.clone(db),
		ProductMessageParser: q.ProductMessageParser.clone(db),
		ProductTSL:           q.ProductTSL.clone(db),
		SceneLinkage:         q.SceneLinkage.clone(db),
		SceneLinkageDetail:   q.SceneLinkageDetail.clone(db),
		UpgradeBatch:         q.UpgradeBatch.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		Alert:                q.Alert.replaceDB(db),
		Device:               q.Device.replaceDB(db),
		DeviceEvent:          q.DeviceEvent.replaceDB(db),
		DevicePushRecord:     q.DevicePushRecord.replaceDB(db),
		DeviceShadow:         q.DeviceShadow.replaceDB(db),
		DeviceShadowHistory:  q.DeviceShadowHistory.replaceDB(db),
		DeviceState:          q.DeviceState.replaceDB(db),
		DeviceTag:            q.DeviceTag.replaceDB(db),
		DeviceUpgradeStatus:  q.DeviceUpgradeStatus.replaceDB(db),
		OTAPackage:           q.OTAPackage.replaceDB(db),
		Product:              q.Product.replaceDB(db),
		ProductMessageParser: q.ProductMessageParser.replaceDB(db),
		ProductTSL:           q.ProductTSL.replaceDB(db),
		SceneLinkage:         q.SceneLinkage.replaceDB(db),
		SceneLinkageDetail:   q.SceneLinkageDetail.replaceDB(db),
		UpgradeBatch:         q.UpgradeBatch.replaceDB(db),
	}
}

type queryCtx struct {
	Alert                *alertDo
	Device               *deviceDo
	DeviceEvent          *deviceEventDo
	DevicePushRecord     *devicePushRecordDo
	DeviceShadow         *deviceShadowDo
	DeviceShadowHistory  *deviceShadowHistoryDo
	DeviceState          *deviceStateDo
	DeviceTag            *deviceTagDo
	DeviceUpgradeStatus  *deviceUpgradeStatusDo
	OTAPackage           *oTAPackageDo
	Product              *productDo
	ProductMessageParser *productMessageParserDo
	ProductTSL           *productTSLDo
	SceneLinkage         *sceneLinkageDo
	SceneLinkageDetail   *sceneLinkageDetailDo
	UpgradeBatch         *upgradeBatchDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Alert:                q.Alert.WithContext(ctx),
		Device:               q.Device.WithContext(ctx),
		DeviceEvent:          q.DeviceEvent.WithContext(ctx),
		DevicePushRecord:     q.DevicePushRecord.WithContext(ctx),
		DeviceShadow:         q.DeviceShadow.WithContext(ctx),
		DeviceShadowHistory:  q.DeviceShadowHistory.WithContext(ctx),
		DeviceState:          q.DeviceState.WithContext(ctx),
		DeviceTag:            q.DeviceTag.WithContext(ctx),
		DeviceUpgradeStatus:  q.DeviceUpgradeStatus.WithContext(ctx),
		OTAPackage:           q.OTAPackage.WithContext(ctx),
		Product:              q.Product.WithContext(ctx),
		ProductMessageParser: q.ProductMessageParser.WithContext(ctx),
		ProductTSL:           q.ProductTSL.WithContext(ctx),
		SceneLinkage:         q.SceneLinkage.WithContext(ctx),
		SceneLinkageDetail:   q.SceneLinkageDetail.WithContext(ctx),
		UpgradeBatch:         q.UpgradeBatch.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
