// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newOTAUpgradeBatch(db *gorm.DB, opts ...gen.DOOption) oTAUpgradeBatch {
	_oTAUpgradeBatch := oTAUpgradeBatch{}

	_oTAUpgradeBatch.oTAUpgradeBatchDo.UseDB(db, opts...)
	_oTAUpgradeBatch.oTAUpgradeBatchDo.UseModel(&model.OTAUpgradeBatch{})

	tableName := _oTAUpgradeBatch.oTAUpgradeBatchDo.TableName()
	_oTAUpgradeBatch.ALL = field.NewAsterisk(tableName)
	_oTAUpgradeBatch.ID = field.NewInt64(tableName, "id")
	_oTAUpgradeBatch.BatchID = field.NewString(tableName, "batch_id")
	_oTAUpgradeBatch.OTAPackageID = field.NewString(tableName, "ota_package_id")
	_oTAUpgradeBatch.BatchName = field.NewString(tableName, "batch_name")
	_oTAUpgradeBatch.UpgradeStrategy = field.NewString(tableName, "upgrade_strategy")
	_oTAUpgradeBatch.Status = field.NewString(tableName, "status")
	_oTAUpgradeBatch.TargetDeviceCount = field.NewInt32(tableName, "target_device_count")
	_oTAUpgradeBatch.CreatedAt = field.NewTime(tableName, "created_at")
	_oTAUpgradeBatch.UpdatedAt = field.NewTime(tableName, "updated_at")

	_oTAUpgradeBatch.fillFieldMap()

	return _oTAUpgradeBatch
}

type oTAUpgradeBatch struct {
	oTAUpgradeBatchDo oTAUpgradeBatchDo

	ALL               field.Asterisk
	ID                field.Int64
	BatchID           field.String
	OTAPackageID      field.String
	BatchName         field.String
	UpgradeStrategy   field.String
	Status            field.String
	TargetDeviceCount field.Int32
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (o oTAUpgradeBatch) Table(newTableName string) *oTAUpgradeBatch {
	o.oTAUpgradeBatchDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oTAUpgradeBatch) As(alias string) *oTAUpgradeBatch {
	o.oTAUpgradeBatchDo.DO = *(o.oTAUpgradeBatchDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oTAUpgradeBatch) updateTableName(table string) *oTAUpgradeBatch {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.BatchID = field.NewString(table, "batch_id")
	o.OTAPackageID = field.NewString(table, "ota_package_id")
	o.BatchName = field.NewString(table, "batch_name")
	o.UpgradeStrategy = field.NewString(table, "upgrade_strategy")
	o.Status = field.NewString(table, "status")
	o.TargetDeviceCount = field.NewInt32(table, "target_device_count")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *oTAUpgradeBatch) WithContext(ctx context.Context) *oTAUpgradeBatchDo {
	return o.oTAUpgradeBatchDo.WithContext(ctx)
}

func (o oTAUpgradeBatch) TableName() string { return o.oTAUpgradeBatchDo.TableName() }

func (o oTAUpgradeBatch) Alias() string { return o.oTAUpgradeBatchDo.Alias() }

func (o oTAUpgradeBatch) Columns(cols ...field.Expr) gen.Columns {
	return o.oTAUpgradeBatchDo.Columns(cols...)
}

func (o *oTAUpgradeBatch) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oTAUpgradeBatch) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 9)
	o.fieldMap["id"] = o.ID
	o.fieldMap["batch_id"] = o.BatchID
	o.fieldMap["ota_package_id"] = o.OTAPackageID
	o.fieldMap["batch_name"] = o.BatchName
	o.fieldMap["upgrade_strategy"] = o.UpgradeStrategy
	o.fieldMap["status"] = o.Status
	o.fieldMap["target_device_count"] = o.TargetDeviceCount
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o oTAUpgradeBatch) clone(db *gorm.DB) oTAUpgradeBatch {
	o.oTAUpgradeBatchDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oTAUpgradeBatch) replaceDB(db *gorm.DB) oTAUpgradeBatch {
	o.oTAUpgradeBatchDo.ReplaceDB(db)
	return o
}

type oTAUpgradeBatchDo struct{ gen.DO }

func (o oTAUpgradeBatchDo) Debug() *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Debug())
}

func (o oTAUpgradeBatchDo) WithContext(ctx context.Context) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oTAUpgradeBatchDo) ReadDB() *oTAUpgradeBatchDo {
	return o.Clauses(dbresolver.Read)
}

func (o oTAUpgradeBatchDo) WriteDB() *oTAUpgradeBatchDo {
	return o.Clauses(dbresolver.Write)
}

func (o oTAUpgradeBatchDo) Session(config *gorm.Session) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Session(config))
}

func (o oTAUpgradeBatchDo) Clauses(conds ...clause.Expression) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oTAUpgradeBatchDo) Returning(value interface{}, columns ...string) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oTAUpgradeBatchDo) Not(conds ...gen.Condition) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oTAUpgradeBatchDo) Or(conds ...gen.Condition) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oTAUpgradeBatchDo) Select(conds ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oTAUpgradeBatchDo) Where(conds ...gen.Condition) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oTAUpgradeBatchDo) Order(conds ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oTAUpgradeBatchDo) Distinct(cols ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oTAUpgradeBatchDo) Omit(cols ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oTAUpgradeBatchDo) Join(table schema.Tabler, on ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oTAUpgradeBatchDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oTAUpgradeBatchDo) RightJoin(table schema.Tabler, on ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oTAUpgradeBatchDo) Group(cols ...field.Expr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oTAUpgradeBatchDo) Having(conds ...gen.Condition) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oTAUpgradeBatchDo) Limit(limit int) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oTAUpgradeBatchDo) Offset(offset int) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oTAUpgradeBatchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oTAUpgradeBatchDo) Unscoped() *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oTAUpgradeBatchDo) Create(values ...*model.OTAUpgradeBatch) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oTAUpgradeBatchDo) CreateInBatches(values []*model.OTAUpgradeBatch, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oTAUpgradeBatchDo) Save(values ...*model.OTAUpgradeBatch) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oTAUpgradeBatchDo) First() (*model.OTAUpgradeBatch, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAUpgradeBatch), nil
	}
}

func (o oTAUpgradeBatchDo) Take() (*model.OTAUpgradeBatch, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAUpgradeBatch), nil
	}
}

func (o oTAUpgradeBatchDo) Last() (*model.OTAUpgradeBatch, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAUpgradeBatch), nil
	}
}

func (o oTAUpgradeBatchDo) Find() ([]*model.OTAUpgradeBatch, error) {
	result, err := o.DO.Find()
	return result.([]*model.OTAUpgradeBatch), err
}

func (o oTAUpgradeBatchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OTAUpgradeBatch, err error) {
	buf := make([]*model.OTAUpgradeBatch, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oTAUpgradeBatchDo) FindInBatches(result *[]*model.OTAUpgradeBatch, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oTAUpgradeBatchDo) Attrs(attrs ...field.AssignExpr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oTAUpgradeBatchDo) Assign(attrs ...field.AssignExpr) *oTAUpgradeBatchDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oTAUpgradeBatchDo) Joins(fields ...field.RelationField) *oTAUpgradeBatchDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oTAUpgradeBatchDo) Preload(fields ...field.RelationField) *oTAUpgradeBatchDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oTAUpgradeBatchDo) FirstOrInit() (*model.OTAUpgradeBatch, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAUpgradeBatch), nil
	}
}

func (o oTAUpgradeBatchDo) FirstOrCreate() (*model.OTAUpgradeBatch, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OTAUpgradeBatch), nil
	}
}

func (o oTAUpgradeBatchDo) FindByPage(offset int, limit int) (result []*model.OTAUpgradeBatch, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oTAUpgradeBatchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oTAUpgradeBatchDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oTAUpgradeBatchDo) Delete(models ...*model.OTAUpgradeBatch) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oTAUpgradeBatchDo) withDO(do gen.Dao) *oTAUpgradeBatchDo {
	o.DO = *do.(*gen.DO)
	return o
}
