// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newProductMessageParser(db *gorm.DB, opts ...gen.DOOption) productMessageParser {
	_productMessageParser := productMessageParser{}

	_productMessageParser.productMessageParserDo.UseDB(db, opts...)
	_productMessageParser.productMessageParserDo.UseModel(&model.ProductMessageParser{})

	tableName := _productMessageParser.productMessageParserDo.TableName()
	_productMessageParser.ALL = field.NewAsterisk(tableName)
	_productMessageParser.ID = field.NewInt64(tableName, "id")
	_productMessageParser.OrganizationID = field.NewInt64(tableName, "organization_id")
	_productMessageParser.ProductID = field.NewInt64(tableName, "product_id")
	_productMessageParser.Language = field.NewString(tableName, "language")
	_productMessageParser.Script = field.NewString(tableName, "script")
	_productMessageParser.CreatedAt = field.NewTime(tableName, "created_at")
	_productMessageParser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_productMessageParser.fillFieldMap()

	return _productMessageParser
}

type productMessageParser struct {
	productMessageParserDo productMessageParserDo

	ALL            field.Asterisk
	ID             field.Int64
	OrganizationID field.Int64
	ProductID      field.Int64
	Language       field.String
	Script         field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (p productMessageParser) Table(newTableName string) *productMessageParser {
	p.productMessageParserDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productMessageParser) As(alias string) *productMessageParser {
	p.productMessageParserDo.DO = *(p.productMessageParserDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productMessageParser) updateTableName(table string) *productMessageParser {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.OrganizationID = field.NewInt64(table, "organization_id")
	p.ProductID = field.NewInt64(table, "product_id")
	p.Language = field.NewString(table, "language")
	p.Script = field.NewString(table, "script")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *productMessageParser) WithContext(ctx context.Context) *productMessageParserDo {
	return p.productMessageParserDo.WithContext(ctx)
}

func (p productMessageParser) TableName() string { return p.productMessageParserDo.TableName() }

func (p productMessageParser) Alias() string { return p.productMessageParserDo.Alias() }

func (p productMessageParser) Columns(cols ...field.Expr) gen.Columns {
	return p.productMessageParserDo.Columns(cols...)
}

func (p *productMessageParser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productMessageParser) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["organization_id"] = p.OrganizationID
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["language"] = p.Language
	p.fieldMap["script"] = p.Script
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p productMessageParser) clone(db *gorm.DB) productMessageParser {
	p.productMessageParserDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productMessageParser) replaceDB(db *gorm.DB) productMessageParser {
	p.productMessageParserDo.ReplaceDB(db)
	return p
}

type productMessageParserDo struct{ gen.DO }

func (p productMessageParserDo) Debug() *productMessageParserDo {
	return p.withDO(p.DO.Debug())
}

func (p productMessageParserDo) WithContext(ctx context.Context) *productMessageParserDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productMessageParserDo) ReadDB() *productMessageParserDo {
	return p.Clauses(dbresolver.Read)
}

func (p productMessageParserDo) WriteDB() *productMessageParserDo {
	return p.Clauses(dbresolver.Write)
}

func (p productMessageParserDo) Session(config *gorm.Session) *productMessageParserDo {
	return p.withDO(p.DO.Session(config))
}

func (p productMessageParserDo) Clauses(conds ...clause.Expression) *productMessageParserDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productMessageParserDo) Returning(value interface{}, columns ...string) *productMessageParserDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productMessageParserDo) Not(conds ...gen.Condition) *productMessageParserDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productMessageParserDo) Or(conds ...gen.Condition) *productMessageParserDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productMessageParserDo) Select(conds ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productMessageParserDo) Where(conds ...gen.Condition) *productMessageParserDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productMessageParserDo) Order(conds ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productMessageParserDo) Distinct(cols ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productMessageParserDo) Omit(cols ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productMessageParserDo) Join(table schema.Tabler, on ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productMessageParserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productMessageParserDo) RightJoin(table schema.Tabler, on ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productMessageParserDo) Group(cols ...field.Expr) *productMessageParserDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productMessageParserDo) Having(conds ...gen.Condition) *productMessageParserDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productMessageParserDo) Limit(limit int) *productMessageParserDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productMessageParserDo) Offset(offset int) *productMessageParserDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productMessageParserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *productMessageParserDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productMessageParserDo) Unscoped() *productMessageParserDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productMessageParserDo) Create(values ...*model.ProductMessageParser) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productMessageParserDo) CreateInBatches(values []*model.ProductMessageParser, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productMessageParserDo) Save(values ...*model.ProductMessageParser) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productMessageParserDo) First() (*model.ProductMessageParser, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMessageParser), nil
	}
}

func (p productMessageParserDo) Take() (*model.ProductMessageParser, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMessageParser), nil
	}
}

func (p productMessageParserDo) Last() (*model.ProductMessageParser, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMessageParser), nil
	}
}

func (p productMessageParserDo) Find() ([]*model.ProductMessageParser, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductMessageParser), err
}

func (p productMessageParserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductMessageParser, err error) {
	buf := make([]*model.ProductMessageParser, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productMessageParserDo) FindInBatches(result *[]*model.ProductMessageParser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productMessageParserDo) Attrs(attrs ...field.AssignExpr) *productMessageParserDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productMessageParserDo) Assign(attrs ...field.AssignExpr) *productMessageParserDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productMessageParserDo) Joins(fields ...field.RelationField) *productMessageParserDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productMessageParserDo) Preload(fields ...field.RelationField) *productMessageParserDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productMessageParserDo) FirstOrInit() (*model.ProductMessageParser, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMessageParser), nil
	}
}

func (p productMessageParserDo) FirstOrCreate() (*model.ProductMessageParser, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMessageParser), nil
	}
}

func (p productMessageParserDo) FindByPage(offset int, limit int) (result []*model.ProductMessageParser, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productMessageParserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productMessageParserDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productMessageParserDo) Delete(models ...*model.ProductMessageParser) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productMessageParserDo) withDO(do gen.Dao) *productMessageParserDo {
	p.DO = *do.(*gen.DO)
	return p
}
