// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newSceneLinkageDetail(db *gorm.DB, opts ...gen.DOOption) sceneLinkageDetail {
	_sceneLinkageDetail := sceneLinkageDetail{}

	_sceneLinkageDetail.sceneLinkageDetailDo.UseDB(db, opts...)
	_sceneLinkageDetail.sceneLinkageDetailDo.UseModel(&model.SceneLinkageDetail{})

	tableName := _sceneLinkageDetail.sceneLinkageDetailDo.TableName()
	_sceneLinkageDetail.ALL = field.NewAsterisk(tableName)
	_sceneLinkageDetail.ID = field.NewInt64(tableName, "id")
	_sceneLinkageDetail.SceneID = field.NewInt64(tableName, "scene_id")
	_sceneLinkageDetail.TriggerConfig = field.NewBytes(tableName, "trigger_config")
	_sceneLinkageDetail.ActionConfig = field.NewBytes(tableName, "action_config")
	_sceneLinkageDetail.CreatedAt = field.NewTime(tableName, "created_at")
	_sceneLinkageDetail.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sceneLinkageDetail.fillFieldMap()

	return _sceneLinkageDetail
}

type sceneLinkageDetail struct {
	sceneLinkageDetailDo sceneLinkageDetailDo

	ALL           field.Asterisk
	ID            field.Int64
	SceneID       field.Int64
	TriggerConfig field.Bytes
	ActionConfig  field.Bytes
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s sceneLinkageDetail) Table(newTableName string) *sceneLinkageDetail {
	s.sceneLinkageDetailDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sceneLinkageDetail) As(alias string) *sceneLinkageDetail {
	s.sceneLinkageDetailDo.DO = *(s.sceneLinkageDetailDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sceneLinkageDetail) updateTableName(table string) *sceneLinkageDetail {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SceneID = field.NewInt64(table, "scene_id")
	s.TriggerConfig = field.NewBytes(table, "trigger_config")
	s.ActionConfig = field.NewBytes(table, "action_config")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sceneLinkageDetail) WithContext(ctx context.Context) *sceneLinkageDetailDo {
	return s.sceneLinkageDetailDo.WithContext(ctx)
}

func (s sceneLinkageDetail) TableName() string { return s.sceneLinkageDetailDo.TableName() }

func (s sceneLinkageDetail) Alias() string { return s.sceneLinkageDetailDo.Alias() }

func (s sceneLinkageDetail) Columns(cols ...field.Expr) gen.Columns {
	return s.sceneLinkageDetailDo.Columns(cols...)
}

func (s *sceneLinkageDetail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sceneLinkageDetail) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["scene_id"] = s.SceneID
	s.fieldMap["trigger_config"] = s.TriggerConfig
	s.fieldMap["action_config"] = s.ActionConfig
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sceneLinkageDetail) clone(db *gorm.DB) sceneLinkageDetail {
	s.sceneLinkageDetailDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sceneLinkageDetail) replaceDB(db *gorm.DB) sceneLinkageDetail {
	s.sceneLinkageDetailDo.ReplaceDB(db)
	return s
}

type sceneLinkageDetailDo struct{ gen.DO }

func (s sceneLinkageDetailDo) Debug() *sceneLinkageDetailDo {
	return s.withDO(s.DO.Debug())
}

func (s sceneLinkageDetailDo) WithContext(ctx context.Context) *sceneLinkageDetailDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sceneLinkageDetailDo) ReadDB() *sceneLinkageDetailDo {
	return s.Clauses(dbresolver.Read)
}

func (s sceneLinkageDetailDo) WriteDB() *sceneLinkageDetailDo {
	return s.Clauses(dbresolver.Write)
}

func (s sceneLinkageDetailDo) Session(config *gorm.Session) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Session(config))
}

func (s sceneLinkageDetailDo) Clauses(conds ...clause.Expression) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sceneLinkageDetailDo) Returning(value interface{}, columns ...string) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sceneLinkageDetailDo) Not(conds ...gen.Condition) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sceneLinkageDetailDo) Or(conds ...gen.Condition) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sceneLinkageDetailDo) Select(conds ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sceneLinkageDetailDo) Where(conds ...gen.Condition) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sceneLinkageDetailDo) Order(conds ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sceneLinkageDetailDo) Distinct(cols ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sceneLinkageDetailDo) Omit(cols ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sceneLinkageDetailDo) Join(table schema.Tabler, on ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sceneLinkageDetailDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sceneLinkageDetailDo) RightJoin(table schema.Tabler, on ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sceneLinkageDetailDo) Group(cols ...field.Expr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sceneLinkageDetailDo) Having(conds ...gen.Condition) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sceneLinkageDetailDo) Limit(limit int) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sceneLinkageDetailDo) Offset(offset int) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sceneLinkageDetailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sceneLinkageDetailDo) Unscoped() *sceneLinkageDetailDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sceneLinkageDetailDo) Create(values ...*model.SceneLinkageDetail) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sceneLinkageDetailDo) CreateInBatches(values []*model.SceneLinkageDetail, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sceneLinkageDetailDo) Save(values ...*model.SceneLinkageDetail) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sceneLinkageDetailDo) First() (*model.SceneLinkageDetail, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SceneLinkageDetail), nil
	}
}

func (s sceneLinkageDetailDo) Take() (*model.SceneLinkageDetail, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SceneLinkageDetail), nil
	}
}

func (s sceneLinkageDetailDo) Last() (*model.SceneLinkageDetail, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SceneLinkageDetail), nil
	}
}

func (s sceneLinkageDetailDo) Find() ([]*model.SceneLinkageDetail, error) {
	result, err := s.DO.Find()
	return result.([]*model.SceneLinkageDetail), err
}

func (s sceneLinkageDetailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SceneLinkageDetail, err error) {
	buf := make([]*model.SceneLinkageDetail, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sceneLinkageDetailDo) FindInBatches(result *[]*model.SceneLinkageDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sceneLinkageDetailDo) Attrs(attrs ...field.AssignExpr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sceneLinkageDetailDo) Assign(attrs ...field.AssignExpr) *sceneLinkageDetailDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sceneLinkageDetailDo) Joins(fields ...field.RelationField) *sceneLinkageDetailDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sceneLinkageDetailDo) Preload(fields ...field.RelationField) *sceneLinkageDetailDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sceneLinkageDetailDo) FirstOrInit() (*model.SceneLinkageDetail, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SceneLinkageDetail), nil
	}
}

func (s sceneLinkageDetailDo) FirstOrCreate() (*model.SceneLinkageDetail, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SceneLinkageDetail), nil
	}
}

func (s sceneLinkageDetailDo) FindByPage(offset int, limit int) (result []*model.SceneLinkageDetail, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sceneLinkageDetailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sceneLinkageDetailDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sceneLinkageDetailDo) Delete(models ...*model.SceneLinkageDetail) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sceneLinkageDetailDo) withDO(do gen.Dao) *sceneLinkageDetailDo {
	s.DO = *do.(*gen.DO)
	return s
}
