// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aiot-backend/internal/model"
)

func newUpgradeBatch(db *gorm.DB, opts ...gen.DOOption) upgradeBatch {
	_upgradeBatch := upgradeBatch{}

	_upgradeBatch.upgradeBatchDo.UseDB(db, opts...)
	_upgradeBatch.upgradeBatchDo.UseModel(&model.UpgradeBatch{})

	tableName := _upgradeBatch.upgradeBatchDo.TableName()
	_upgradeBatch.ALL = field.NewAsterisk(tableName)
	_upgradeBatch.ID = field.NewInt64(tableName, "id")
	_upgradeBatch.BatchID = field.NewString(tableName, "batch_id")
	_upgradeBatch.OTAPackageID = field.NewString(tableName, "ota_package_id")
	_upgradeBatch.BatchName = field.NewString(tableName, "batch_name")
	_upgradeBatch.BatchType = field.NewString(tableName, "batch_type")
	_upgradeBatch.UpgradeStrategy = field.NewString(tableName, "upgrade_strategy")
	_upgradeBatch.Status = field.NewString(tableName, "status")
	_upgradeBatch.TargetDeviceCount = field.NewInt32(tableName, "target_device_count")
	_upgradeBatch.CreatedAt = field.NewTime(tableName, "created_at")
	_upgradeBatch.UpdatedAt = field.NewTime(tableName, "updated_at")

	_upgradeBatch.fillFieldMap()

	return _upgradeBatch
}

type upgradeBatch struct {
	upgradeBatchDo upgradeBatchDo

	ALL               field.Asterisk
	ID                field.Int64
	BatchID           field.String
	OTAPackageID      field.String
	BatchName         field.String
	BatchType         field.String
	UpgradeStrategy   field.String
	Status            field.String
	TargetDeviceCount field.Int32
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (u upgradeBatch) Table(newTableName string) *upgradeBatch {
	u.upgradeBatchDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u upgradeBatch) As(alias string) *upgradeBatch {
	u.upgradeBatchDo.DO = *(u.upgradeBatchDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *upgradeBatch) updateTableName(table string) *upgradeBatch {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.BatchID = field.NewString(table, "batch_id")
	u.OTAPackageID = field.NewString(table, "ota_package_id")
	u.BatchName = field.NewString(table, "batch_name")
	u.BatchType = field.NewString(table, "batch_type")
	u.UpgradeStrategy = field.NewString(table, "upgrade_strategy")
	u.Status = field.NewString(table, "status")
	u.TargetDeviceCount = field.NewInt32(table, "target_device_count")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *upgradeBatch) WithContext(ctx context.Context) *upgradeBatchDo {
	return u.upgradeBatchDo.WithContext(ctx)
}

func (u upgradeBatch) TableName() string { return u.upgradeBatchDo.TableName() }

func (u upgradeBatch) Alias() string { return u.upgradeBatchDo.Alias() }

func (u upgradeBatch) Columns(cols ...field.Expr) gen.Columns {
	return u.upgradeBatchDo.Columns(cols...)
}

func (u *upgradeBatch) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *upgradeBatch) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["batch_id"] = u.BatchID
	u.fieldMap["ota_package_id"] = u.OTAPackageID
	u.fieldMap["batch_name"] = u.BatchName
	u.fieldMap["batch_type"] = u.BatchType
	u.fieldMap["upgrade_strategy"] = u.UpgradeStrategy
	u.fieldMap["status"] = u.Status
	u.fieldMap["target_device_count"] = u.TargetDeviceCount
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u upgradeBatch) clone(db *gorm.DB) upgradeBatch {
	u.upgradeBatchDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u upgradeBatch) replaceDB(db *gorm.DB) upgradeBatch {
	u.upgradeBatchDo.ReplaceDB(db)
	return u
}

type upgradeBatchDo struct{ gen.DO }

func (u upgradeBatchDo) Debug() *upgradeBatchDo {
	return u.withDO(u.DO.Debug())
}

func (u upgradeBatchDo) WithContext(ctx context.Context) *upgradeBatchDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u upgradeBatchDo) ReadDB() *upgradeBatchDo {
	return u.Clauses(dbresolver.Read)
}

func (u upgradeBatchDo) WriteDB() *upgradeBatchDo {
	return u.Clauses(dbresolver.Write)
}

func (u upgradeBatchDo) Session(config *gorm.Session) *upgradeBatchDo {
	return u.withDO(u.DO.Session(config))
}

func (u upgradeBatchDo) Clauses(conds ...clause.Expression) *upgradeBatchDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u upgradeBatchDo) Returning(value interface{}, columns ...string) *upgradeBatchDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u upgradeBatchDo) Not(conds ...gen.Condition) *upgradeBatchDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u upgradeBatchDo) Or(conds ...gen.Condition) *upgradeBatchDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u upgradeBatchDo) Select(conds ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u upgradeBatchDo) Where(conds ...gen.Condition) *upgradeBatchDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u upgradeBatchDo) Order(conds ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u upgradeBatchDo) Distinct(cols ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u upgradeBatchDo) Omit(cols ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u upgradeBatchDo) Join(table schema.Tabler, on ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u upgradeBatchDo) LeftJoin(table schema.Tabler, on ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u upgradeBatchDo) RightJoin(table schema.Tabler, on ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u upgradeBatchDo) Group(cols ...field.Expr) *upgradeBatchDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u upgradeBatchDo) Having(conds ...gen.Condition) *upgradeBatchDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u upgradeBatchDo) Limit(limit int) *upgradeBatchDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u upgradeBatchDo) Offset(offset int) *upgradeBatchDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u upgradeBatchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *upgradeBatchDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u upgradeBatchDo) Unscoped() *upgradeBatchDo {
	return u.withDO(u.DO.Unscoped())
}

func (u upgradeBatchDo) Create(values ...*model.UpgradeBatch) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u upgradeBatchDo) CreateInBatches(values []*model.UpgradeBatch, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u upgradeBatchDo) Save(values ...*model.UpgradeBatch) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u upgradeBatchDo) First() (*model.UpgradeBatch, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UpgradeBatch), nil
	}
}

func (u upgradeBatchDo) Take() (*model.UpgradeBatch, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UpgradeBatch), nil
	}
}

func (u upgradeBatchDo) Last() (*model.UpgradeBatch, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UpgradeBatch), nil
	}
}

func (u upgradeBatchDo) Find() ([]*model.UpgradeBatch, error) {
	result, err := u.DO.Find()
	return result.([]*model.UpgradeBatch), err
}

func (u upgradeBatchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UpgradeBatch, err error) {
	buf := make([]*model.UpgradeBatch, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u upgradeBatchDo) FindInBatches(result *[]*model.UpgradeBatch, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u upgradeBatchDo) Attrs(attrs ...field.AssignExpr) *upgradeBatchDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u upgradeBatchDo) Assign(attrs ...field.AssignExpr) *upgradeBatchDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u upgradeBatchDo) Joins(fields ...field.RelationField) *upgradeBatchDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u upgradeBatchDo) Preload(fields ...field.RelationField) *upgradeBatchDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u upgradeBatchDo) FirstOrInit() (*model.UpgradeBatch, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UpgradeBatch), nil
	}
}

func (u upgradeBatchDo) FirstOrCreate() (*model.UpgradeBatch, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UpgradeBatch), nil
	}
}

func (u upgradeBatchDo) FindByPage(offset int, limit int) (result []*model.UpgradeBatch, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u upgradeBatchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u upgradeBatchDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u upgradeBatchDo) Delete(models ...*model.UpgradeBatch) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *upgradeBatchDo) withDO(do gen.Dao) *upgradeBatchDo {
	u.DO = *do.(*gen.DO)
	return u
}
