// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-http/internal/handler"
	"transport-http/internal/router"
	"transport-http/internal/server"
	"transport-http/pkg/app"
	"transport-http/pkg/log"
	"transport-http/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	deviceHandler := handler.NewDeviceHandler(logger)
	routerRouter := router.NewRouter(deviceHandler, viperViper, logger)
	httpServer := server.NewHTTPServer(viperViper, logger, routerRouter)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var handlerSet = wire.NewSet(handler.NewDeviceHandler)

var routerSet = wire.NewSet(router.NewRouter)

var serverSet = wire.NewSet(server.NewHTTPServer)

func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("0things-transport-http"))
}
