// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"0things/pkg/event"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"transport-http/internal/handler"
	"transport-http/internal/router"
	"transport-http/internal/server"
	"transport-http/pkg/app"
	"transport-http/pkg/log"
	"transport-http/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	producer, cleanup, err := provideEventProducer(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	deviceHandler := handler.NewDeviceHandler(logger, producer)
	routerRouter := router.NewRouter(deviceHandler, viperViper, logger)
	httpServer := server.NewHTTPServer(viperViper, logger, routerRouter)
	appApp := newApp(httpServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideEventProducer(conf *viper.Viper, logger *log.Logger) (event.Producer, func(), error) {
	pub, _, err := event.NewBus(conf, logger.Logger)
	if err != nil {
		return nil, nil, err
	}
	producer := event.NewProducer(pub)
	cleanup := func() {
		_ = producer.Close()
	}
	return producer, cleanup, nil
}

var handlerSet = wire.NewSet(handler.NewDeviceHandler)

var routerSet = wire.NewSet(router.NewRouter)

var serverSet = wire.NewSet(server.NewHTTPServer)

func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("0things-transport-http"))
}
